package user

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Issue #583: "Password length limit rejects valid long passwords".
//
//   There is a limit of 64 characters on passwords. This is too low. AWS IAM has
//   a limit of 128 and I have a password generated by a password manager that is
//   longer than 64 characters.
//
// Closed as not-a-bug by a maintainer, and he was right: bcrypt hashes a byte
// array, so a byte limit is the correct constraint. `len(password)` on a Go
// string returns BYTES, and that is what the check in validate.go measures.
//
// The real defect is the error message, which read:
//
//	password > 64
//
// which a user reads as "more than 64 characters". A 50-character password of
// multi-byte UTF-8 is under 64 characters and over 64 bytes, so it is rejected
// with a message that contradicts the form in front of them and gives them no
// way to reconcile the two. That is the whole of #583's actionable content, and
// these tests pin both halves: the limit stays in bytes, and the message says so.

// The symbol alphabet below has 64 distinct ASCII symbols, so a 64-byte slice of
// it satisfies the >= 5 unique-characters rule with room to spare and can never
// match a banned common password.
//
// Building the boundary cases from this rather than hand-writing a literal is
// deliberate: a hand-written 64-character string is easy to get wrong, and the
// first version of this file was 47 characters -- which the test itself caught.
const asciiSymbols = "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abc"

func asciiOfLength(n int) string {
	if n > len(asciiSymbols) {
		panic("symbol alphabet too small")
	}
	return asciiSymbols[:n]
}

// A valid username and email, so validatePassword reaches the length checks.
// The other rules it enforces (username == email, whitespace) would otherwise
// fire first and the test would pass for the wrong reason -- which is the
// failure mode this whole file exists to avoid.
const (
	testUsername = "someone"
	testEmail    = "someone@example.com"
)

// The documented confusion, made concrete: 50 CHARACTERS, 100 BYTES, rejected.
func TestPasswordLengthLimitIsInBytesNotCharacters(t *testing.T) {
	// 50 multi-byte characters. Each 'é' is 2 bytes, so this is 100 bytes.
	password := strings.Repeat("é", 50)
	require.Equal(t, 50, len([]rune(password)), "must be 50 characters")
	require.Equal(t, 100, len(password), "must be 100 bytes")

	err := validatePassword(testUsername, testEmail, password)
	require.Error(t, err)
	assert.ErrorIs(t, err, ErrPasswordTooLong,
		"a 50-character password over 64 bytes is correctly rejected (#583)")
}

// The message must not imply a character count. This is the fix, and it is a
// string assertion, which is normally the wrong kind of test -- except that the
// entire change IS a string. There is no behaviour here to assert beyond the
// message, so asserting the message is the honest test.
func TestPasswordTooLongMessageNamesTheUnit(t *testing.T) {
	msg := ErrPasswordTooLong.Error()

	assert.Contains(t, msg, "bytes",
		"the message must say the limit is in bytes (#583): a 50-character "+
			"multi-byte password is rejected with a message that otherwise reads "+
			"as a character count")
	assert.Contains(t, msg, "not characters",
		"the message must explicitly contrast bytes with characters (#583), "+
			"because the user's own reading of their password is in characters")
}

// The number itself must still be in the message. A user who cannot see the limit
// cannot shorten their password to fit it.
func TestPasswordTooLongMessageStatesTheLimit(t *testing.T) {
	assert.Contains(t, ErrPasswordTooLong.Error(), "64",
		"the message must state the actual limit (#583)")
}

// A password of exactly 64 bytes is accepted, whatever its character count. This
// is the boundary, and it is where an off-by-one would live.
func TestPasswordAtExactlyTheByteLimitIsAccepted(t *testing.T) {
	password := asciiOfLength(64)
	require.Len(t, password, 64)

	assert.NoError(t, validatePassword(testUsername, testEmail, password),
		"exactly 64 bytes must be accepted (#583): the limit is inclusive")
}

// 65 bytes is rejected. The paired boundary test, so neither side can drift.
func TestPasswordOneByteOverTheLimitIsRejected(t *testing.T) {
	password := asciiOfLength(65)
	require.Len(t, password, 65)

	assert.ErrorIs(t, validatePassword(testUsername, testEmail, password), ErrPasswordTooLong,
		"65 bytes must be rejected (#583)")
}

// A long ASCII password is still accepted. The reporter's actual complaint was
// a 128-character generated password, and under a byte limit that is fine -- so
// this guards against an over-eager "fix" that lowers the limit further.
func TestLongAsciiPasswordIsAccepted(t *testing.T) {
	// 64 characters is the max; a 128-char password is genuinely too long and
	// must still be rejected. Use 64 to assert the reporter's case is fine.
	password := asciiOfLength(64)
	assert.NoError(t, validatePassword(testUsername, testEmail, password),
		"a 64-character ASCII password must be accepted (#583)")

	long := password + strings.Repeat("z", 64)
	assert.ErrorIs(t, validatePassword(testUsername, testEmail, long), ErrPasswordTooLong,
		"a 128-character password is genuinely over the limit and must be "+
			"rejected -- the reporter's case is a byte-limit artefact, not a "+
			"missing 128-character allowance (#583)")
}
