#import "../fragments/PerformerFragment.gql"

query EloLeaderboard($entityType: EloEntityType!, $limit: Int) {
  eloLeaderboard(entityType: $entityType, limit: $limit) {
    entityType
    entries {
      entityId
      rating
      deviation
      voteCount
      performer {
        ...PerformerFragment
      }
    }
  }
}
