query PublishedLists($perPage: Int, $page: Int) {
  publishedLists(perPage: $perPage, page: $page) {
    count
    lists {
      id
      name
      description
      publishedAt
      itemCount
      owner {
        id
        name
      }
    }
  }
}
