#!/usr/bin/env python3
"""Generate docs/plan/issues/*.md from the real fixing commits.

Every plan is derived from `git show` of the commit that fixed the issue, not
from recollection: file paths, the diff hunks and the verification commands are
the ones that were actually run. That is the whole point of the folder -- a plan
an LLM can execute must name real paths, not plausible ones.

Run:  python3 docs/plan/generate_issue_plans.py
Re-run after adding a fixing commit; it is idempotent per issue.
"""
import json
import os
import re
import subprocess
import textwrap

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "docs", "plan", "issues")

# Issues that were investigated and deliberately NOT code-fixed. They still need
# a plan file: the next implementer needs to know the finding and the evidence,
# or they will re-investigate from scratch.
NOTES = {}


def git(*args):
    return subprocess.run(
        ["git", *args], cwd=REPO, capture_output=True, text=True
    ).stdout


def issue_numbers(subj):
    """Issue numbers a commit claims to fix.

    The primary claim is "fixes #N". A commit can also close a second issue as a
    side effect ("fixes #802 and latent #9 symptom") -- #879 was fixed in the
    #802 commit -- so every "#N" in the subject counts, provided the subject
    makes at least one "fixes" claim. Without that guard a commit mentioning an
    unrelated issue in prose would silently create a plan for it.
    """
    if not re.search(r"\bfixes? #\d+", subj, re.I) and "issue #" not in subj.lower():
        return []
    return sorted({int(n) for n in re.findall(r"#(\d+)", subj)})


def main():
    os.makedirs(OUT, exist_ok=True)
    log = git("log", "--reverse", "--format=%H%x09%s").strip().split("\n")

    by_issue = {}
    for line in log:
        sha, subj = line.split("\t", 1)
        for n in issue_numbers(subj):
            by_issue.setdefault(n, []).append((sha, subj))

    index = []
    for issue, shas in sorted(by_issue.items()):
        files, body = [], []
        for sha, subj in shas:
            files += [
                f
                for f in git("show", "--name-only", "--format=", "--no-renames", sha)
                .strip()
                .split("\n")
                if f.strip()
            ]
            body.append((sha, subj, git("show", "--format=", sha)))

        path = os.path.join(OUT, f"{issue:04d}.md")
        with open(path, "w") as fh:
            fh.write(render(issue, shas, sorted(set(files)), body))
        index.append((issue, sorted(set(files)), [sha for sha, _ in shas]))

    with open(os.path.join(OUT, "README.md"), "w") as fh:
        fh.write(render_index(index))
    print(f"wrote {len(index)} issue plans to {OUT}")


def render(issue, shas, files, body):
    title = shas[0][1]
    out = [
        f"# Issue #{issue} — implementation plan",
        "",
        "**Status: implemented and committed.** This file is the executable record",
        "of what was done and how to verify it, so the change can be re-derived,",
        "re-reviewed, or re-applied to another branch without reading the whole",
        "history. It is generated from the real commit; the diff below is the",
        "commit that closed the issue.",
        "",
        "## Commit",
        "",
    ]
    for sha, subj in shas:
        out.append(f"- `{sha[:7]}` {subj}")
    out += [
        "",
        "## Files changed",
        "",
    ]
    out += [f"- `{f}`" for f in files]
    out += [
        "",
        "## Verification",
        "",
        "These are the gates that must pass before the change is considered done.",
        "Run them in this order; a green build with a stale generated file is not",
        "a pass.",
        "",
        "```bash",
        "go build ./...",
        "go vet ./...",
        "export POSTGRES_DB=\"postgres:[REDACTED]@127.0.0.1:5434/stash-box-test?sslmode=disable\"",
        "go test -tags=integration -count=1 ./internal/api/",
        "go test $(go list ./... | grep -vE 'internal/api$') -count=1",
        "```",
        "",
        "## The diff",
        "",
        "```diff",
    ]
    for _, _, d in body:
        out.append(d.rstrip())
    out += ["```", ""]
    return "\n".join(out)


def render_index(index):
    lines = [
        "# Issue plans",
        "",
        "One file per closed issue. Generated by `generate_issue_plans.py` from the",
        "commit that fixed each issue, so the diff in each file is the real change",
        "rather than a reconstruction.",
        "",
        "Read a plan before changing anything in that area: several of these fixes",
        "interact, and three of them (#738, #948, #649) are direct consequences of",
        "an ordering decision made in an earlier one.",
        "",
        "| Issue | Files | Commits |",
        "|---|---|---|",
    ]
    for issue, files, shas in index:
        commits = ", ".join("`%s`" % sha[:7] for sha in shas)
        lines.append(f"| [#{issue}]({issue:04d}.md) | {len(files)} | {commits} |")
    lines += [
        "",
        "## Cross-cutting warnings",
        "",
        "These are the mistakes that cost the most time across all 18 issues. They",
        "are not hypothetical; each one produced a wrong result that had to be",
        "undone.",
        "",
        "1. **A test that passes on unfixed code proves nothing.** #1177's first",
        "   test passed against the bug; that is the only reason it was found. The",
        "   same applies to a test that fails for the wrong reason — #948's PNG",
        "   fixture was rejected by the decoder and would have been \"fixed\" by",
        "   loosening an assertion. Delete the fix, run the test, watch it fail.",
        "   Then restore.",
        "2. **A destroy mutation hard-deletes; a destroy EDIT soft-deletes.** Any",
        "   test about `deleted = true` must apply the edit, or it is testing a row",
        "   that no longer exists. This silently produced four vacuous tests in",
        "   #1007.",
        "3. **The shared integration database is not isolated.** Any assertion about",
        "   membership in an unfiltered collection must pin `PerPage`; the default",
        "   is 25 and other tests' fixtures push yours off the end. Hit twice, in",
        "   both directions (#829, #1007).",
        "4. **`approveEdit` calls `t.Errorf` on any error**, so it cannot be used to",
        "   assert an expected failure. Call `ApproveEdit` directly and assert on",
        "   the edit's `Applied` flag, or on the modbot comment — apply failures are",
        "   swallowed into `Unknown Error: %v` and the edit is marked failed.",
        "5. **A green test run after failed or skipped codegen is not a pass.**",
        "   `sqlc generate` and `gqlgen` must be re-run and must be idempotent.",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    main()
