// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authored_quest.sql

package queries

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const addAuthoredQuestItem = `-- name: AddAuthoredQuestItem :one
INSERT INTO authored_quest_items (id, quest_id, entity_type, entity_id)
VALUES ($1, $2, $3, $4)
RETURNING id, quest_id, entity_type, entity_id, claimed_by, claimed_at, created_at
`

type AddAuthoredQuestItemParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	QuestID    uuid.UUID `db:"quest_id" json:"quest_id"`
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
}

func (q *Queries) AddAuthoredQuestItem(ctx context.Context, arg AddAuthoredQuestItemParams) (AuthoredQuestItem, error) {
	row := q.db.QueryRow(ctx, addAuthoredQuestItem,
		arg.ID,
		arg.QuestID,
		arg.EntityType,
		arg.EntityID,
	)
	var i AuthoredQuestItem
	err := row.Scan(
		&i.ID,
		&i.QuestID,
		&i.EntityType,
		&i.EntityID,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const claimAuthoredQuestItem = `-- name: ClaimAuthoredQuestItem :one
UPDATE authored_quest_items
SET claimed_by = $2,
    claimed_at = now()
WHERE id = $1
  AND (claimed_by IS NULL OR claimed_by = $2)
RETURNING id, quest_id, entity_type, entity_id, claimed_by, claimed_at, created_at
`

type ClaimAuthoredQuestItemParams struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	ClaimedBy uuid.NullUUID `db:"claimed_by" json:"claimed_by"`
}

// THE CLAIM. A guarded UPDATE, never a check-then-write.
//
// Two curators claiming the last item in a quest must not both get it, and
// SELECT-then-UPDATE cannot express that: both read "unclaimed", both write. The
// WHERE claimed_by IS NULL is the whole concurrency control, and it holds the gap
// shut because the UPDATE takes the row lock before evaluating it.
//
// An item already claimed by SOMEONE ELSE returns no rows (ErrNoRows), which the
// service reports as "already claimed" rather than as a failure. An item already
// claimed by the SAME curator returns the row, so claiming twice is idempotent --
// a retried request must not tell a curator they lost a race they won.
func (q *Queries) ClaimAuthoredQuestItem(ctx context.Context, arg ClaimAuthoredQuestItemParams) (AuthoredQuestItem, error) {
	row := q.db.QueryRow(ctx, claimAuthoredQuestItem, arg.ID, arg.ClaimedBy)
	var i AuthoredQuestItem
	err := row.Scan(
		&i.ID,
		&i.QuestID,
		&i.EntityType,
		&i.EntityID,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countAuthoredQuestItems = `-- name: CountAuthoredQuestItems :one
SELECT count(*) FROM authored_quest_items WHERE quest_id = $1
`

// The count of items a quest holds, used to refuse authoring more than the
// target rather than silently truncating.
func (q *Queries) CountAuthoredQuestItems(ctx context.Context, questID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthoredQuestItems, questID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthoredQuest = `-- name: CreateAuthoredQuest :one

INSERT INTO authored_quests (id, entity_type, field, target, bounty_points, reason, authored_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, entity_type, field, target, bounty_points, reason, authored_by, expires_at, created_at
`

type CreateAuthoredQuestParams struct {
	ID           uuid.UUID     `db:"id" json:"id"`
	EntityType   string        `db:"entity_type" json:"entity_type"`
	Field        string        `db:"field" json:"field"`
	Target       int           `db:"target" json:"target"`
	BountyPoints int           `db:"bounty_points" json:"bounty_points"`
	Reason       *string       `db:"reason" json:"reason"`
	AuthoredBy   uuid.NullUUID `db:"authored_by" json:"authored_by"`
	ExpiresAt    *time.Time    `db:"expires_at" json:"expires_at"`
}

// Authored quests, bounties and claiming (SPEC §7.7).
//
// GENERATED quests (internal/service/quest) are a pure function of the archive and
// deliberately never stored. These are the AUTHORED ones: a quest a person
// promised, carrying a bounty a generator must not be able to manufacture.
func (q *Queries) CreateAuthoredQuest(ctx context.Context, arg CreateAuthoredQuestParams) (AuthoredQuest, error) {
	row := q.db.QueryRow(ctx, createAuthoredQuest,
		arg.ID,
		arg.EntityType,
		arg.Field,
		arg.Target,
		arg.BountyPoints,
		arg.Reason,
		arg.AuthoredBy,
		arg.ExpiresAt,
	)
	var i AuthoredQuest
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.Field,
		&i.Target,
		&i.BountyPoints,
		&i.Reason,
		&i.AuthoredBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthoredQuest = `-- name: DeleteAuthoredQuest :exec
DELETE FROM authored_quests WHERE id = $1
`

func (q *Queries) DeleteAuthoredQuest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthoredQuest, id)
	return err
}

const expireStaleQuestClaims = `-- name: ExpireStaleQuestClaims :many
UPDATE authored_quest_items
SET claimed_by = NULL,
    claimed_at = NULL
WHERE claimed_by IS NOT NULL
  AND claimed_at < $1 - INTERVAL '1 hour'
RETURNING id, quest_id, entity_type, entity_id, claimed_by, claimed_at, created_at
`

// Expiring stale claims. A curator who abandoned work releases it themselves;
// this is the backstop for the ones who did not.
//
// Scoped by AGE as well as by the cutoff so it cannot strand a recent claim
// because the batch ran slowly.
func (q *Queries) ExpireStaleQuestClaims(ctx context.Context, dollar_1 interface{}) ([]AuthoredQuestItem, error) {
	rows, err := q.db.Query(ctx, expireStaleQuestClaims, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthoredQuestItem{}
	for rows.Next() {
		var i AuthoredQuestItem
		if err := rows.Scan(
			&i.ID,
			&i.QuestID,
			&i.EntityType,
			&i.EntityID,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findActiveAuthoredQuests = `-- name: FindActiveAuthoredQuests :many
SELECT id, entity_type, field, target, bounty_points, reason, authored_by, expires_at, created_at FROM authored_quests
WHERE expires_at IS NULL OR expires_at > now()
ORDER BY bounty_points DESC, created_at DESC
`

// The quest board. Active quests only, because an expired quest is not a quest
// anybody acts on, and the count of expired ones grows forever.
//
// The expiry filter lives HERE rather than in the client so "active" has one
// definition. A client-side expiry filter and a server-side one disagree the
// moment a clock is involved.
func (q *Queries) FindActiveAuthoredQuests(ctx context.Context) ([]AuthoredQuest, error) {
	rows, err := q.db.Query(ctx, findActiveAuthoredQuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthoredQuest{}
	for rows.Next() {
		var i AuthoredQuest
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Field,
			&i.Target,
			&i.BountyPoints,
			&i.Reason,
			&i.AuthoredBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAuthoredQuest = `-- name: FindAuthoredQuest :one
SELECT id, entity_type, field, target, bounty_points, reason, authored_by, expires_at, created_at FROM authored_quests WHERE id = $1
`

func (q *Queries) FindAuthoredQuest(ctx context.Context, id uuid.UUID) (AuthoredQuest, error) {
	row := q.db.QueryRow(ctx, findAuthoredQuest, id)
	var i AuthoredQuest
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.Field,
		&i.Target,
		&i.BountyPoints,
		&i.Reason,
		&i.AuthoredBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findAuthoredQuestByAuthor = `-- name: FindAuthoredQuestByAuthor :many
SELECT id, entity_type, field, target, bounty_points, reason, authored_by, expires_at, created_at FROM authored_quests
WHERE authored_by = $1
ORDER BY created_at DESC
`

func (q *Queries) FindAuthoredQuestByAuthor(ctx context.Context, authoredBy uuid.NullUUID) ([]AuthoredQuest, error) {
	rows, err := q.db.Query(ctx, findAuthoredQuestByAuthor, authoredBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthoredQuest{}
	for rows.Next() {
		var i AuthoredQuest
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.Field,
			&i.Target,
			&i.BountyPoints,
			&i.Reason,
			&i.AuthoredBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAuthoredQuestItems = `-- name: FindAuthoredQuestItems :many
SELECT
    i.id,
    i.quest_id,
    i.entity_type,
    i.entity_id,
    i.claimed_by,
    i.claimed_at,
    i.created_at,
    u.name AS claimed_by_name
FROM authored_quest_items i
LEFT JOIN users u ON u.id = i.claimed_by
WHERE i.quest_id = $1
ORDER BY i.claimed_at NULLS FIRST, i.created_at, i.id
`

type FindAuthoredQuestItemsRow struct {
	ID            uuid.UUID     `db:"id" json:"id"`
	QuestID       uuid.UUID     `db:"quest_id" json:"quest_id"`
	EntityType    string        `db:"entity_type" json:"entity_type"`
	EntityID      uuid.UUID     `db:"entity_id" json:"entity_id"`
	ClaimedBy     uuid.NullUUID `db:"claimed_by" json:"claimed_by"`
	ClaimedAt     *time.Time    `db:"claimed_at" json:"claimed_at"`
	CreatedAt     time.Time     `db:"created_at" json:"created_at"`
	ClaimedByName *string       `db:"claimed_by_name" json:"claimed_by_name"`
}

// The items of a quest, with the claim inlined.
//
// The LEFT JOIN to the claim is the "reconcile on read" the migration comment
// promises: a filled field does not DELETE the row, it just makes the item
// stop counting. Keeping the row is what lets the quest show "you did this one",
// which is most of why a curator comes back.
func (q *Queries) FindAuthoredQuestItems(ctx context.Context, questID uuid.UUID) ([]FindAuthoredQuestItemsRow, error) {
	rows, err := q.db.Query(ctx, findAuthoredQuestItems, questID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAuthoredQuestItemsRow{}
	for rows.Next() {
		var i FindAuthoredQuestItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestID,
			&i.EntityType,
			&i.EntityID,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.CreatedAt,
			&i.ClaimedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAuthoredQuestItemsByEntity = `-- name: FindAuthoredQuestItemsByEntity :many
SELECT id, quest_id, entity_type, entity_id, claimed_by, claimed_at, created_at FROM authored_quest_items
WHERE entity_type = $1
  AND entity_id = $2
`

type FindAuthoredQuestItemsByEntityParams struct {
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
}

// "Show me everything known about this entity" -- how an authored quest turns
// into a canonical link back to the entity's page.
func (q *Queries) FindAuthoredQuestItemsByEntity(ctx context.Context, arg FindAuthoredQuestItemsByEntityParams) ([]AuthoredQuestItem, error) {
	rows, err := q.db.Query(ctx, findAuthoredQuestItemsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthoredQuestItem{}
	for rows.Next() {
		var i AuthoredQuestItem
		if err := rows.Scan(
			&i.ID,
			&i.QuestID,
			&i.EntityType,
			&i.EntityID,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findClaimsByUser = `-- name: FindClaimsByUser :many
SELECT
    i.id,
    i.quest_id,
    i.entity_type,
    i.entity_id,
    i.claimed_by,
    i.claimed_at,
    q.field,
    q.target,
    q.bounty_points
FROM authored_quest_items i
JOIN authored_quests q ON q.id = i.quest_id
WHERE i.claimed_by = $1
ORDER BY i.claimed_at DESC
`

type FindClaimsByUserRow struct {
	ID           uuid.UUID     `db:"id" json:"id"`
	QuestID      uuid.UUID     `db:"quest_id" json:"quest_id"`
	EntityType   string        `db:"entity_type" json:"entity_type"`
	EntityID     uuid.UUID     `db:"entity_id" json:"entity_id"`
	ClaimedBy    uuid.NullUUID `db:"claimed_by" json:"claimed_by"`
	ClaimedAt    *time.Time    `db:"claimed_at" json:"claimed_at"`
	Field        string        `db:"field" json:"field"`
	Target       int           `db:"target" json:"target"`
	BountyPoints int           `db:"bounty_points" json:"bounty_points"`
}

// A curator's in-progress work, newest claim first. The "what am I working on"
// list, and the query an operator runs to find claims worth expiring.
func (q *Queries) FindClaimsByUser(ctx context.Context, claimedBy uuid.NullUUID) ([]FindClaimsByUserRow, error) {
	rows, err := q.db.Query(ctx, findClaimsByUser, claimedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindClaimsByUserRow{}
	for rows.Next() {
		var i FindClaimsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestID,
			&i.EntityType,
			&i.EntityID,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.Field,
			&i.Target,
			&i.BountyPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAuthoredQuestItem = `-- name: ReleaseAuthoredQuestItem :one
UPDATE authored_quest_items
SET claimed_by = NULL,
    claimed_at = NULL
WHERE id = $1
  AND claimed_by = $2
RETURNING id, quest_id, entity_type, entity_id, claimed_by, claimed_at, created_at
`

type ReleaseAuthoredQuestItemParams struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	ClaimedBy uuid.NullUUID `db:"claimed_by" json:"claimed_by"`
}

// Releasing a claim. Restricted to the claimer's own rows by the WHERE, so one
// curator cannot release another's work.
func (q *Queries) ReleaseAuthoredQuestItem(ctx context.Context, arg ReleaseAuthoredQuestItemParams) (AuthoredQuestItem, error) {
	row := q.db.QueryRow(ctx, releaseAuthoredQuestItem, arg.ID, arg.ClaimedBy)
	var i AuthoredQuestItem
	err := row.Scan(
		&i.ID,
		&i.QuestID,
		&i.EntityType,
		&i.EntityID,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}
