// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: collage.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignSnapshotsToCollage = `-- name: AssignSnapshotsToCollage :execrows
UPDATE scene_snapshots
SET collage_id = $1
WHERE id = ANY($2::UUID[])
  AND collage_id IS NULL
`

type AssignSnapshotsToCollageParams struct {
	CollageID   uuid.NullUUID `db:"collage_id" json:"collage_id"`
	SnapshotIds []uuid.UUID   `db:"snapshot_ids" json:"snapshot_ids"`
}

// Claims a set of snapshots for a collage.
//
// The WHERE clause on collage_id IS NULL is a claim, not a filter: if a snapshot
// was claimed by a concurrent generation between the SELECT and this UPDATE, the
// row does not match and is not taken. That is the optimistic-concurrency guard.
//
// :execrows rather than :exec, and that is load-bearing. Without the returned count
// the caller cannot tell a complete claim from a partial one, and a partial claim
// produces a collage with fewer frames than its own frame_count says -- a broken
// strip that renders as though it were fine. The caller compares the count against
// the number it asked for and rolls back on a shortfall.
//
// array_unnest over a UUID[] is how sqlc passes a set; there is no variadic form
// in Postgres and unnest is the idiomatic one.
func (q *Queries) AssignSnapshotsToCollage(ctx context.Context, arg AssignSnapshotsToCollageParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignSnapshotsToCollage, arg.CollageID, arg.SnapshotIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSceneSnapshots = `-- name: CountSceneSnapshots :one
SELECT count(*) FROM scene_snapshots WHERE scene_id = $1
`

func (q *Queries) CountSceneSnapshots(ctx context.Context, sceneID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSceneSnapshots, sceneID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollage = `-- name: CreateCollage :one
INSERT INTO collages (id, scene_id, frame_count, strategy, source_duration_ms, current_duration_ms)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, scene_id, frame_count, strategy, source_duration_ms, current_duration_ms, generated_at
`

type CreateCollageParams struct {
	ID                uuid.UUID   `db:"id" json:"id"`
	SceneID           uuid.UUID   `db:"scene_id" json:"scene_id"`
	FrameCount        int         `db:"frame_count" json:"frame_count"`
	Strategy          string      `db:"strategy" json:"strategy"`
	SourceDurationMs  pgtype.Int8 `db:"source_duration_ms" json:"source_duration_ms"`
	CurrentDurationMs pgtype.Int8 `db:"current_duration_ms" json:"current_duration_ms"`
}

// Creates the collage row. source_duration_ms is the duration the sampler
// believed; the scene's current duration is read by the caller and stored
// alongside it so a stale collage is diagnosable rather than merely wrong-looking.
func (q *Queries) CreateCollage(ctx context.Context, arg CreateCollageParams) (Collage, error) {
	row := q.db.QueryRow(ctx, createCollage,
		arg.ID,
		arg.SceneID,
		arg.FrameCount,
		arg.Strategy,
		arg.SourceDurationMs,
		arg.CurrentDurationMs,
	)
	var i Collage
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.FrameCount,
		&i.Strategy,
		&i.SourceDurationMs,
		&i.CurrentDurationMs,
		&i.GeneratedAt,
	)
	return i, err
}

const createSceneSnapshot = `-- name: CreateSceneSnapshot :one

INSERT INTO scene_snapshots (id, scene_id, timestamp_ms, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, scene_id, timestamp_ms, collage_id, created_by, created_at
`

type CreateSceneSnapshotParams struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	SceneID     uuid.UUID     `db:"scene_id" json:"scene_id"`
	TimestampMs int64         `db:"timestamp_ms" json:"timestamp_ms"`
	CreatedBy   uuid.NullUUID `db:"created_by" json:"created_by"`
}

// Snapshot collage queries (SPEC §8, migration 78).
//
// Two tables with a deliberate split: scene_snapshots is the source of truth
// (individual timestamped frames) and collages is a derived selection over them.
// See migration 78 for why the split exists and why a snapshot is a timestamp
// rather than a stored image.
// Adding a snapshot by hand or via the API. collage_id is left NULL: SPEC §8
// describes collages as GENERATED, so a snapshot exists in the pool before
// anything selects from it.
//
// The unique (scene_id, timestamp_ms) means a re-add of the same instant is a
// constraint violation rather than a duplicate frame that renders as one and
// counts twice toward the frame budget. Surfaced as ErrDuplicateSnapshot rather
// than a raw 23505 so the caller can say something useful.
func (q *Queries) CreateSceneSnapshot(ctx context.Context, arg CreateSceneSnapshotParams) (SceneSnapshot, error) {
	row := q.db.QueryRow(ctx, createSceneSnapshot,
		arg.ID,
		arg.SceneID,
		arg.TimestampMs,
		arg.CreatedBy,
	)
	var i SceneSnapshot
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.TimestampMs,
		&i.CollageID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCollage = `-- name: DeleteCollage :exec
DELETE FROM collages WHERE scene_id = $1
`

// Removing a collage. The snapshots it referenced are NOT deleted: the FK is ON
// DELETE SET NULL, so they return to the unassigned pool and a later generation can
// reuse them. Deleting a user's curated frames because someone re-rolled a collage
// would be data loss dressed up as a cascade.
func (q *Queries) DeleteCollage(ctx context.Context, sceneID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollage, sceneID)
	return err
}

const deleteCollageForScene = `-- name: DeleteCollageForScene :exec
UPDATE scene_snapshots
SET collage_id = NULL
WHERE scene_id = $1 AND collage_id IS NOT NULL
`

// Frees a collage's frames without removing the collage row, for the regeneration
// path: clear the assignment, sample again, reassign.
//
// Separate from DeleteCollage because the two are used at different times and
// conflating them is how a regeneration ends up deleting curated snapshots.
func (q *Queries) DeleteCollageForScene(ctx context.Context, sceneID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollageForScene, sceneID)
	return err
}

const deleteSceneSnapshot = `-- name: DeleteSceneSnapshot :exec
DELETE FROM scene_snapshots WHERE id = $1
`

func (q *Queries) DeleteSceneSnapshot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSceneSnapshot, id)
	return err
}

const findSceneDuration = `-- name: FindSceneDuration :one
SELECT duration FROM scenes WHERE id = $1 AND deleted = FALSE
`

// The scene's duration, for spacing a collage's frames.
//
// Returns only `duration`, deliberately. A sampler needs the length and nothing
// else, and selecting the whole scene row here would hand the caller a struct it
// has no business modifying.
//
// Deleted scenes are excluded so Generate can tell "this scene is gone" from "this
// scene has no duration" -- two different errors with two different fixes, and the
// distinction is worth a row.
func (q *Queries) FindSceneDuration(ctx context.Context, id uuid.UUID) (*int, error) {
	row := q.db.QueryRow(ctx, findSceneDuration, id)
	var duration *int
	err := row.Scan(&duration)
	return duration, err
}

const getCollageForScene = `-- name: GetCollageForScene :one
SELECT id, scene_id, frame_count, strategy, source_duration_ms, current_duration_ms, generated_at FROM collages WHERE scene_id = $1
`

func (q *Queries) GetCollageForScene(ctx context.Context, sceneID uuid.UUID) (Collage, error) {
	row := q.db.QueryRow(ctx, getCollageForScene, sceneID)
	var i Collage
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.FrameCount,
		&i.Strategy,
		&i.SourceDurationMs,
		&i.CurrentDurationMs,
		&i.GeneratedAt,
	)
	return i, err
}

const getSceneSnapshot = `-- name: GetSceneSnapshot :one
SELECT id, scene_id, timestamp_ms, collage_id, created_by, created_at FROM scene_snapshots WHERE id = $1
`

func (q *Queries) GetSceneSnapshot(ctx context.Context, id uuid.UUID) (SceneSnapshot, error) {
	row := q.db.QueryRow(ctx, getSceneSnapshot, id)
	var i SceneSnapshot
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.TimestampMs,
		&i.CollageID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listCollageSnapshots = `-- name: ListCollageSnapshots :many
SELECT s.id, s.scene_id, s.timestamp_ms, s.collage_id, s.created_by, s.created_at
FROM scene_snapshots s
JOIN collages c ON c.id = s.collage_id
WHERE c.scene_id = $1
  AND s.collage_id IS NOT NULL
ORDER BY s.timestamp_ms
`

// The frames of a collage, in playback order.
//
// The read path for rendering, covered by a partial index on
// (collage_id, timestamp_ms) so this is an index scan and not a sort of the
// scene's entire snapshot set.
func (q *Queries) ListCollageSnapshots(ctx context.Context, sceneID uuid.UUID) ([]SceneSnapshot, error) {
	rows, err := q.db.Query(ctx, listCollageSnapshots, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneSnapshot{}
	for rows.Next() {
		var i SceneSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.TimestampMs,
			&i.CollageID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSceneSnapshots = `-- name: ListSceneSnapshots :many
SELECT id, scene_id, timestamp_ms, collage_id, created_by, created_at FROM scene_snapshots
WHERE scene_id = $1
ORDER BY timestamp_ms
`

// Every snapshot for a scene, in order, whether or not it is in a collage.
//
// Ordered by timestamp so a caller rendering a scene's visual index gets frames in
// playback order for free, and so a client computing "how far apart are these"
// does not have to sort.
func (q *Queries) ListSceneSnapshots(ctx context.Context, sceneID uuid.UUID) ([]SceneSnapshot, error) {
	rows, err := q.db.Query(ctx, listSceneSnapshots, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneSnapshot{}
	for rows.Next() {
		var i SceneSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.TimestampMs,
			&i.CollageID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenesWithInsufficientSnapshots = `-- name: ListScenesWithInsufficientSnapshots :many
SELECT s.id, count(sn.id) AS snapshot_count
FROM scenes s
LEFT JOIN scene_snapshots sn ON sn.scene_id = s.id
WHERE s.deleted = FALSE
GROUP BY s.id
HAVING count(sn.id) < $1::INT
ORDER BY count(sn.id) ASC, s.id
LIMIT $2
`

type ListScenesWithInsufficientSnapshotsParams struct {
	MinSnapshots int   `db:"min_snapshots" json:"min_snapshots"`
	LimitCount   int32 `db:"limit_count" json:"limit_count"`
}

type ListScenesWithInsufficientSnapshotsRow struct {
	ID            uuid.UUID `db:"id" json:"id"`
	SnapshotCount int64     `db:"snapshot_count" json:"snapshot_count"`
}

// Scenes whose visual index is too thin to identify from -- the input to SPEC §8's
// curation and preservation quests ("this scene has only 2 snapshots").
//
// Counts snapshots per scene rather than collages: a scene with 40 snapshots and
// no collage is better identified than one with 3 and a 12-frame collage, because
// the snapshots are what a user can browse and the collage is a selection over
// them.
//
// Deleted scenes are excluded, matching every other performer/scene query.
func (q *Queries) ListScenesWithInsufficientSnapshots(ctx context.Context, arg ListScenesWithInsufficientSnapshotsParams) ([]ListScenesWithInsufficientSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listScenesWithInsufficientSnapshots, arg.MinSnapshots, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScenesWithInsufficientSnapshotsRow{}
	for rows.Next() {
		var i ListScenesWithInsufficientSnapshotsRow
		if err := rows.Scan(&i.ID, &i.SnapshotCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedSnapshots = `-- name: ListUnassignedSnapshots :many
SELECT id, scene_id, timestamp_ms, collage_id, created_by, created_at FROM scene_snapshots
WHERE scene_id = $1 AND collage_id IS NULL
ORDER BY timestamp_ms
`

// The pool a collage generation samples from.
//
// Excludes snapshots already committed to a collage. On a REgeneration the old
// collage's frames are freed first (see ClearCollage), so this returns the whole
// pool again -- which is what makes a re-roll able to pick different frames rather
// than only from whatever the last generation left behind.
func (q *Queries) ListUnassignedSnapshots(ctx context.Context, sceneID uuid.UUID) ([]SceneSnapshot, error) {
	rows, err := q.db.Query(ctx, listUnassignedSnapshots, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneSnapshot{}
	for rows.Next() {
		var i SceneSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.TimestampMs,
			&i.CollageID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
