// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: denylist.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

const listDeniedPerformerIDs = `-- name: ListDeniedPerformerIDs :many
SELECT "performer_id" FROM "content_denylist_performer"
`

func (q *Queries) ListDeniedPerformerIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDeniedPerformerIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var performer_id uuid.UUID
		if err := rows.Scan(&performer_id); err != nil {
			return nil, err
		}
		items = append(items, performer_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeniedStudioIDs = `-- name: ListDeniedStudioIDs :many
SELECT "studio_id" FROM "content_denylist_studio"
`

func (q *Queries) ListDeniedStudioIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDeniedStudioIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var studio_id uuid.UUID
		if err := rows.Scan(&studio_id); err != nil {
			return nil, err
		}
		items = append(items, studio_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeniedTagIDs = `-- name: ListDeniedTagIDs :many
SELECT "tag_id" FROM "content_denylist_tag"
`

// The tag half of the content denylist, for the access rule that IS enforced.
//
// Id only: the resolver maps a UUID straight into the rule's id set, and
// selecting `reason` would mean every read drags a column no caller uses. An
// operator audit reads the reason through a per-entity query, which is the
// right shape for "why is this one entity denied" anyway.
func (q *Queries) ListDeniedTagIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDeniedTagIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var tag_id uuid.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
