// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: elo.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/gofrs/uuid"
)

const countEloVotesForEntity = `-- name: CountEloVotesForEntity :one
SELECT count(*)
FROM elo_votes
WHERE (winner_type = $1 AND winner_id = $2)
   OR (loser_type = $1 AND loser_id = $2)
`

type CountEloVotesForEntityParams struct {
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
}

// How many votes an entity has taken part in, across both sides. Feeds the
// leaderboard's "needs more votes" marker and any minimum-confidence filter.
func (q *Queries) CountEloVotesForEntity(ctx context.Context, arg CountEloVotesForEntityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEloVotesForEntity, arg.EntityType, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTasteVector = `-- name: DeleteTasteVector :exec
DELETE FROM taste_vectors WHERE user_id = $1
`

// Only used by a rebuild, so the row can be recreated from scratch rather than
// merged. Merging a recomputed vector into an existing one would double-count
// every feature.
func (q *Queries) DeleteTasteVector(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTasteVector, userID)
	return err
}

const getEloRating = `-- name: GetEloRating :one

SELECT entity_type, entity_id, rating, deviation, last_rated_at FROM elo_ratings WHERE entity_type = $1 AND entity_id = $2
`

type GetEloRatingParams struct {
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
}

// Elo / Glicko-2 queries (SPEC §9, migration 77).
//
// elo_votes is the source of truth and is append-only; elo_ratings is a cache
// with a defined rebuild path. These queries are the only places allowed to
// write either table, for the same reason trust.sql owns trust_events and
// user_trust.
func (q *Queries) GetEloRating(ctx context.Context, arg GetEloRatingParams) (EloRating, error) {
	row := q.db.QueryRow(ctx, getEloRating, arg.EntityType, arg.EntityID)
	var i EloRating
	err := row.Scan(
		&i.EntityType,
		&i.EntityID,
		&i.Rating,
		&i.Deviation,
		&i.LastRatedAt,
	)
	return i, err
}

const getEloRatingsByIDs = `-- name: GetEloRatingsByIDs :many
SELECT entity_type, entity_id, rating, deviation, last_rated_at FROM elo_ratings WHERE entity_type = $1 AND entity_id = ANY($2::UUID[])
`

type GetEloRatingsByIDsParams struct {
	EntityType string      `db:"entity_type" json:"entity_type"`
	Column2    []uuid.UUID `db:"column_2" json:"column_2"`
}

// Takes a type plus a batch of ids, because ranking reads are always
// per-entity-kind ("the ratings for these 50 performers"), never across kinds.
func (q *Queries) GetEloRatingsByIDs(ctx context.Context, arg GetEloRatingsByIDsParams) ([]EloRating, error) {
	rows, err := q.db.Query(ctx, getEloRatingsByIDs, arg.EntityType, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EloRating{}
	for rows.Next() {
		var i EloRating
		if err := rows.Scan(
			&i.EntityType,
			&i.EntityID,
			&i.Rating,
			&i.Deviation,
			&i.LastRatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEloVotesForUser = `-- name: GetEloVotesForUser :many
SELECT id, user_id, winner_id, loser_id, winner_type, loser_type, picked_side, created_at FROM elo_votes WHERE user_id = $1 ORDER BY created_at DESC
`

// The user's own votes, newest first. Backs the taste vector (SPEC §2) and the
// voting-consistency signal in SPEC §6.
//
// Ordered by created_at so a rebuild is deterministic: two rebuilds of the same
// vote set must produce the same vector, and an unordered scan would let
// floating-point rounding differ between runs.
func (q *Queries) GetEloVotesForUser(ctx context.Context, userID uuid.UUID) ([]EloVote, error) {
	rows, err := q.db.Query(ctx, getEloVotesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EloVote{}
	for rows.Next() {
		var i EloVote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WinnerID,
			&i.LoserID,
			&i.WinnerType,
			&i.LoserType,
			&i.PickedSide,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasteVector = `-- name: GetTasteVector :one
SELECT user_id, vector, vote_count, updated_at FROM taste_vectors WHERE user_id = $1
`

func (q *Queries) GetTasteVector(ctx context.Context, userID uuid.UUID) (TasteVector, error) {
	row := q.db.QueryRow(ctx, getTasteVector, userID)
	var i TasteVector
	err := row.Scan(
		&i.UserID,
		&i.Vector,
		&i.VoteCount,
		&i.UpdatedAt,
	)
	return i, err
}

const recordEloVote = `-- name: RecordEloVote :one
INSERT INTO elo_votes (id, user_id, winner_id, loser_id, winner_type, loser_type, picked_side)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, winner_id, loser_id, winner_type, loser_type, picked_side, created_at
`

type RecordEloVoteParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	WinnerID   uuid.UUID `db:"winner_id" json:"winner_id"`
	LoserID    uuid.UUID `db:"loser_id" json:"loser_id"`
	WinnerType string    `db:"winner_type" json:"winner_type"`
	LoserType  string    `db:"loser_type" json:"loser_type"`
	PickedSide int16     `db:"picked_side" json:"picked_side"`
}

// No ON CONFLICT: elo_votes has no natural key beyond its own id, and a
// duplicate matchup is a legitimate thing for a user to do (they may change
// their mind about the same pair). Deduplicating identical votes would discard
// that signal, and the "don't double count" property comes from Glicko being
// applied to the rating, not from refusing to store the vote.
//
// Returning the row lets the service report the resulting rating to the voter
// without a second round trip.
func (q *Queries) RecordEloVote(ctx context.Context, arg RecordEloVoteParams) (EloVote, error) {
	row := q.db.QueryRow(ctx, recordEloVote,
		arg.ID,
		arg.UserID,
		arg.WinnerID,
		arg.LoserID,
		arg.WinnerType,
		arg.LoserType,
		arg.PickedSide,
	)
	var i EloVote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WinnerID,
		&i.LoserID,
		&i.WinnerType,
		&i.LoserType,
		&i.PickedSide,
		&i.CreatedAt,
	)
	return i, err
}

const upsertEloRating = `-- name: UpsertEloRating :one
INSERT INTO elo_ratings (entity_type, entity_id, rating, deviation, last_rated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (entity_type, entity_id) DO UPDATE
SET rating = EXCLUDED.rating,
    deviation = EXCLUDED.deviation,
    last_rated_at = NOW()
RETURNING entity_type, entity_id, rating, deviation, last_rated_at
`

type UpsertEloRatingParams struct {
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
	Rating     int       `db:"rating" json:"rating"`
	Deviation  float64   `db:"deviation" json:"deviation"`
}

// Creates the row on first use, which is what makes a performer created AFTER
// the migration work without a separate backfill: the seeding INSERT covers
// performers that predate it, and this covers everyone after.
//
// last_rated_at is set on update as well as insert, so a rating that is
// re-asserted with unchanged numbers still counts as "rated now" for the Glicko
// time constant.
func (q *Queries) UpsertEloRating(ctx context.Context, arg UpsertEloRatingParams) (EloRating, error) {
	row := q.db.QueryRow(ctx, upsertEloRating,
		arg.EntityType,
		arg.EntityID,
		arg.Rating,
		arg.Deviation,
	)
	var i EloRating
	err := row.Scan(
		&i.EntityType,
		&i.EntityID,
		&i.Rating,
		&i.Deviation,
		&i.LastRatedAt,
	)
	return i, err
}

const upsertTasteVector = `-- name: UpsertTasteVector :one
INSERT INTO taste_vectors (user_id, vector, vote_count, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id) DO UPDATE
SET vector = EXCLUDED.vector,
    vote_count = EXCLUDED.vote_count,
    updated_at = NOW()
RETURNING user_id, vector, vote_count, updated_at
`

type UpsertTasteVectorParams struct {
	UserID    uuid.UUID       `db:"user_id" json:"user_id"`
	Vector    json.RawMessage `db:"vector" json:"vector"`
	VoteCount int             `db:"vote_count" json:"vote_count"`
}

func (q *Queries) UpsertTasteVector(ctx context.Context, arg UpsertTasteVectorParams) (TasteVector, error) {
	row := q.db.QueryRow(ctx, upsertTasteVector, arg.UserID, arg.Vector, arg.VoteCount)
	var i TasteVector
	err := row.Scan(
		&i.UserID,
		&i.Vector,
		&i.VoteCount,
		&i.UpdatedAt,
	)
	return i, err
}
