// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: elo_matchup.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

const countVotesBetweenEntities = `-- name: CountVotesBetweenEntities :one
SELECT count(*)
FROM elo_votes
WHERE user_id = $1
  AND (
    (winner_type = $2::TEXT
       AND winner_id = $3::UUID
       AND loser_id = $4::UUID)
    OR (winner_type = $2::TEXT
       AND winner_id = $4::UUID
       AND loser_id = $3::UUID)
  )
`

type CountVotesBetweenEntitiesParams struct {
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	EntityType string    `db:"entity_type" json:"entity_type"`
	LeftID     uuid.UUID `db:"left_id" json:"left_id"`
	RightID    uuid.UUID `db:"right_id" json:"right_id"`
}

// How many times this user has already been shown this exact pair.
//
// Backs EloMatchup.timesOffered. Repetition is not a bug: SPEC §9 wants streaks
// and a daily reason to return, and a user who has seen a pair before and votes
// the same way twice is the strongest signal the system can get. The client
// labels a repeat matchup so the user knows the system is not pretending the
// pair is new.
func (q *Queries) CountVotesBetweenEntities(ctx context.Context, arg CountVotesBetweenEntitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVotesBetweenEntities,
		arg.UserID,
		arg.EntityType,
		arg.LeftID,
		arg.RightID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const queryMatchupCandidates = `-- name: QueryMatchupCandidates :many

SELECT p.id, p.name, p.disambiguation, p.gender, p.ethnicity, p.country, p.eye_color, p.hair_color, p.height, p.cup_size, p.band_size, p.hip_size, p.waist_size, p.breast_type, p.career_start_year, p.career_end_year, p.created_at, p.updated_at, p.deleted, p.birthdate, p.deathdate
FROM performers p
JOIN elo_ratings r ON r.entity_id = p.id AND r.entity_type = $1
WHERE p.deleted = FALSE
  AND p.id <> ALL($2::UUID[])
  AND NOT EXISTS (
    -- Already offered to this user. The whole EXISTS is skipped when the caller
    -- asks for repeats, which is how streaks and "taste maker" challenges in
    -- SPEC §9 get their re-shows.
    SELECT 1 FROM elo_votes v
    WHERE $3::BOOLEAN IS NOT TRUE
      AND v.user_id = $4
      AND (
        (v.winner_type = $1 AND v.winner_id = p.id)
        OR (v.loser_type = $1 AND v.loser_id = p.id)
      )
  )
ORDER BY r.rating DESC, p.name
LIMIT $5
`

type QueryMatchupCandidatesParams struct {
	EntityType     string      `db:"entity_type" json:"entity_type"`
	ExcludeIds     []uuid.UUID `db:"exclude_ids" json:"exclude_ids"`
	ExcludeOffered bool        `db:"exclude_offered" json:"exclude_offered"`
	UserID         uuid.UUID   `db:"user_id" json:"user_id"`
	LimitCount     int32       `db:"limit_count" json:"limit_count"`
}

// Matchup candidate selection (SPEC §9: "two performers side by side, who do you
// prefer, one click, next matchup").
// Draw a pool of performers eligible to appear in a matchup.
//
// Two eligibility rules, both load-bearing:
//
//  1. At least one vote already. A performer nobody has rated has a deviation of
//     350 (the default), and Glicko's whole signal-to-noise ratio collapses
//     against that: a matchup between two virgin entities produces two small
//     rating moves and no information about anyone. Requiring one vote means
//     every matchup involves at least one entity the system has a real opinion
//     about, so the user's choice lands on something meaningful.
//
//  2. Deleted performers are excluded explicitly, on the `deleted` BOOLEAN the
//     other performer queries use. elo_ratings has no foreign key and no
//     soft-delete awareness, so a deleted performer would otherwise still be
//     drawn and a user could spend a vote on a ghost.
//
// Ordered by the ELO rating rather than randomly at the SQL level. Two reasons,
// and the second is the important one: Postgres random() is not reproducible,
// which would make this method untestable, and a purely random draw would show a
// user the same obscure performers forever. Returning the best-rated window
// first and letting the caller SAMPLE within it gives a user mostly-known
// candidates with enough variety to be a choice.
//
// The join is on elo_ratings, not on a rating column: the Glicko rating is not
// stored on the performer at all, and querying for one is the first thing to
// check when a query like this fails to validate.
func (q *Queries) QueryMatchupCandidates(ctx context.Context, arg QueryMatchupCandidatesParams) ([]Performer, error) {
	rows, err := q.db.Query(ctx, queryMatchupCandidates,
		arg.EntityType,
		arg.ExcludeIds,
		arg.ExcludeOffered,
		arg.UserID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Performer{}
	for rows.Next() {
		var i Performer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Disambiguation,
			&i.Gender,
			&i.Ethnicity,
			&i.Country,
			&i.EyeColor,
			&i.HairColor,
			&i.Height,
			&i.CupSize,
			&i.BandSize,
			&i.HipSize,
			&i.WaistSize,
			&i.BreastType,
			&i.CareerStartYear,
			&i.CareerEndYear,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
			&i.Birthdate,
			&i.Deathdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
