// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: federation.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFederationPeer = `-- name: CreateFederationPeer :one

INSERT INTO federation_peers (name, base_url, instance_id, trust_weight, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, base_url, instance_id, trust_weight, enabled, last_seen_at, created_at, updated_at
`

type CreateFederationPeerParams struct {
	Name        string  `db:"name" json:"name"`
	BaseUrl     string  `db:"base_url" json:"base_url"`
	InstanceID  string  `db:"instance_id" json:"instance_id"`
	TrustWeight float64 `db:"trust_weight" json:"trust_weight"`
	Enabled     bool    `db:"enabled" json:"enabled"`
}

// Federation peer registry queries.
//
// Read-side only. The federation service owns creating and deleting peers; this
// file is what it reads through, and nothing outside the federation package
// should import these -- a peer list is an operator surface, not a public one.
func (q *Queries) CreateFederationPeer(ctx context.Context, arg CreateFederationPeerParams) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, createFederationPeer,
		arg.Name,
		arg.BaseUrl,
		arg.InstanceID,
		arg.TrustWeight,
		arg.Enabled,
	)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.InstanceID,
		&i.TrustWeight,
		&i.Enabled,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFederationPeer = `-- name: DeleteFederationPeer :exec
DELETE FROM federation_peers WHERE id = $1
`

func (q *Queries) DeleteFederationPeer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFederationPeer, id)
	return err
}

const getFederationPeer = `-- name: GetFederationPeer :one
SELECT id, name, base_url, instance_id, trust_weight, enabled, last_seen_at, created_at, updated_at FROM federation_peers WHERE id = $1
`

func (q *Queries) GetFederationPeer(ctx context.Context, id uuid.UUID) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, getFederationPeer, id)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.InstanceID,
		&i.TrustWeight,
		&i.Enabled,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFederationPeerByInstanceId = `-- name: GetFederationPeerByInstanceId :one
SELECT id, name, base_url, instance_id, trust_weight, enabled, last_seen_at, created_at, updated_at FROM federation_peers WHERE instance_id = $1
`

// The lookup that makes a reply attributable: an inbound answer is matched to
// a peer by the instance id it declares, so an unknown instance is rejected
// rather than silently recorded against nobody.
func (q *Queries) GetFederationPeerByInstanceId(ctx context.Context, instanceID string) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, getFederationPeerByInstanceId, instanceID)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.InstanceID,
		&i.TrustWeight,
		&i.Enabled,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledFederationPeers = `-- name: ListEnabledFederationPeers :many
SELECT id, name, base_url, instance_id, trust_weight, enabled, last_seen_at, created_at, updated_at FROM federation_peers WHERE enabled = TRUE ORDER BY name
`

// The candidate set for a broadcast. Filters `enabled` in SQL rather than in Go
// so the broadcast path cannot accidentally read a disabled peer.
func (q *Queries) ListEnabledFederationPeers(ctx context.Context) ([]FederationPeer, error) {
	rows, err := q.db.Query(ctx, listEnabledFederationPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FederationPeer{}
	for rows.Next() {
		var i FederationPeer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.InstanceID,
			&i.TrustWeight,
			&i.Enabled,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFederationPeers = `-- name: ListFederationPeers :many
SELECT id, name, base_url, instance_id, trust_weight, enabled, last_seen_at, created_at, updated_at FROM federation_peers ORDER BY name
`

// Operator surface, so ordering is by name rather than by id: a list whose
// order changes between calls is a list nobody can scan.
func (q *Queries) ListFederationPeers(ctx context.Context) ([]FederationPeer, error) {
	rows, err := q.db.Query(ctx, listFederationPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FederationPeer{}
	for rows.Next() {
		var i FederationPeer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.InstanceID,
			&i.TrustWeight,
			&i.Enabled,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleFederationPeers = `-- name: ListStaleFederationPeers :many
SELECT id, name, base_url, instance_id, trust_weight, enabled, last_seen_at, created_at, updated_at FROM federation_peers
WHERE last_seen_at IS NULL OR last_seen_at < $1
ORDER BY last_seen_at NULLS FIRST
`

// Peers that have not been seen inside the cutoff, for the operator's stale
// list. Never-contacted peers have a NULL last_seen_at and are returned by
// `last_seen_at IS NULL OR last_seen_at < $1` -- an unknown peer and a peer
// that has gone quiet are both "do not ask", but they are different facts and
// the operator surface shows them differently.
func (q *Queries) ListStaleFederationPeers(ctx context.Context, lastSeenAt pgtype.Timestamptz) ([]FederationPeer, error) {
	rows, err := q.db.Query(ctx, listStaleFederationPeers, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FederationPeer{}
	for rows.Next() {
		var i FederationPeer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.InstanceID,
			&i.TrustWeight,
			&i.Enabled,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchFederationPeer = `-- name: TouchFederationPeer :exec
UPDATE federation_peers SET last_seen_at = now(), updated_at = now() WHERE id = $1
`

// Records a successful contact. Separate from UpdateFederationPeer so a
// successful fetch cannot be confused with an operator edit, and so the
// updated_at churn of an edit does not look like liveness.
func (q *Queries) TouchFederationPeer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchFederationPeer, id)
	return err
}

const updateFederationPeer = `-- name: UpdateFederationPeer :one
UPDATE federation_peers
SET name = $2,
    base_url = $3,
    trust_weight = $4,
    enabled = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, base_url, instance_id, trust_weight, enabled, last_seen_at, created_at, updated_at
`

type UpdateFederationPeerParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	BaseUrl     string    `db:"base_url" json:"base_url"`
	TrustWeight float64   `db:"trust_weight" json:"trust_weight"`
	Enabled     bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) UpdateFederationPeer(ctx context.Context, arg UpdateFederationPeerParams) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, updateFederationPeer,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.TrustWeight,
		arg.Enabled,
	)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.InstanceID,
		&i.TrustWeight,
		&i.Enabled,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
