// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: identification_federation.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

const countForeignCandidatesByQuery = `-- name: CountForeignCandidatesByQuery :one
SELECT count(*) FROM identification_foreign_candidates WHERE query_id = $1
`

func (q *Queries) CountForeignCandidatesByQuery(ctx context.Context, queryID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countForeignCandidatesByQuery, queryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForeignCandidate = `-- name: CreateForeignCandidate :one

INSERT INTO identification_foreign_candidates
    (query_id, peer_id, entity_type, remote_entity_id, remote_entity_name, remote_vote_count)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (query_id, peer_id, entity_type, remote_entity_id) DO UPDATE
SET remote_entity_name = EXCLUDED.remote_entity_name,
    remote_vote_count  = EXCLUDED.remote_vote_count,
    fetched_at         = now()
RETURNING id, query_id, peer_id, entity_type, remote_entity_id, remote_entity_name, remote_vote_count, fetched_at
`

type CreateForeignCandidateParams struct {
	QueryID          uuid.UUID `db:"query_id" json:"query_id"`
	PeerID           uuid.UUID `db:"peer_id" json:"peer_id"`
	EntityType       string    `db:"entity_type" json:"entity_type"`
	RemoteEntityID   string    `db:"remote_entity_id" json:"remote_entity_id"`
	RemoteEntityName string    `db:"remote_entity_name" json:"remote_entity_name"`
	RemoteVoteCount  int       `db:"remote_vote_count" json:"remote_vote_count"`
}

// Foreign identification evidence — a peer's answer to one of our queries.
//
// SPEC F2, and this file is where that decision is enforced: the only INSERT
// here targets identification_foreign_candidates. There is deliberately no
// query in this file that writes identification_candidates, and no query that
// deletes or updates a local candidate, so there is no code path from a peer's
// answer into the local vote table. The test for that is
// TestForeignEvidenceCannotReachLocalVotePath.
func (q *Queries) CreateForeignCandidate(ctx context.Context, arg CreateForeignCandidateParams) (IdentificationForeignCandidate, error) {
	row := q.db.QueryRow(ctx, createForeignCandidate,
		arg.QueryID,
		arg.PeerID,
		arg.EntityType,
		arg.RemoteEntityID,
		arg.RemoteEntityName,
		arg.RemoteVoteCount,
	)
	var i IdentificationForeignCandidate
	err := row.Scan(
		&i.ID,
		&i.QueryID,
		&i.PeerID,
		&i.EntityType,
		&i.RemoteEntityID,
		&i.RemoteEntityName,
		&i.RemoteVoteCount,
		&i.FetchedAt,
	)
	return i, err
}

const deleteForeignCandidatesByPeer = `-- name: DeleteForeignCandidatesByPeer :exec
DELETE FROM identification_foreign_candidates WHERE peer_id = $1
`

// Used when a peer is removed from the registry. Without this, deleting a peer
// would either fail on the FK or leave orphaned evidence pointing at a peer the
// operator believes they have removed.
func (q *Queries) DeleteForeignCandidatesByPeer(ctx context.Context, peerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteForeignCandidatesByPeer, peerID)
	return err
}

const deleteForeignCandidatesByQuery = `-- name: DeleteForeignCandidatesByQuery :exec
DELETE FROM identification_foreign_candidates WHERE query_id = $1
`

// Used when a query is resolved or abandoned, so a peer cannot keep answering a
// question that no longer exists.
func (q *Queries) DeleteForeignCandidatesByQuery(ctx context.Context, queryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteForeignCandidatesByQuery, queryID)
	return err
}

const getForeignCandidate = `-- name: GetForeignCandidate :one
SELECT id, query_id, peer_id, entity_type, remote_entity_id, remote_entity_name, remote_vote_count, fetched_at FROM identification_foreign_candidates WHERE id = $1
`

func (q *Queries) GetForeignCandidate(ctx context.Context, id uuid.UUID) (IdentificationForeignCandidate, error) {
	row := q.db.QueryRow(ctx, getForeignCandidate, id)
	var i IdentificationForeignCandidate
	err := row.Scan(
		&i.ID,
		&i.QueryID,
		&i.PeerID,
		&i.EntityType,
		&i.RemoteEntityID,
		&i.RemoteEntityName,
		&i.RemoteVoteCount,
		&i.FetchedAt,
	)
	return i, err
}

const listForeignCandidatesByQuery = `-- name: ListForeignCandidatesByQuery :many

SELECT id, query_id, peer_id, entity_type, remote_entity_id, remote_entity_name, remote_vote_count, fetched_at FROM identification_foreign_candidates
WHERE query_id = $1
ORDER BY peer_id, remote_vote_count DESC, remote_entity_name
`

// ON CONFLICT DO UPDATE rather than DO NOTHING, because re-asking a peer is
// normal (the same query goes out on the next broadcast) and a peer's answer
// can legitimately have moved: more of its users may now agree. DO NOTHING
// would keep the first answer forever, which is the stale-evidence problem
// SPEC F3 exists to prevent -- just on a single row instead of a whole query.
func (q *Queries) ListForeignCandidatesByQuery(ctx context.Context, queryID uuid.UUID) ([]IdentificationForeignCandidate, error) {
	rows, err := q.db.Query(ctx, listForeignCandidatesByQuery, queryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentificationForeignCandidate{}
	for rows.Next() {
		var i IdentificationForeignCandidate
		if err := rows.Scan(
			&i.ID,
			&i.QueryID,
			&i.PeerID,
			&i.EntityType,
			&i.RemoteEntityID,
			&i.RemoteEntityName,
			&i.RemoteVoteCount,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
