// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: identification.sql

package queries

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const abandonIdentificationQuery = `-- name: AbandonIdentificationQuery :one
UPDATE identification_queries
SET status = 'abandoned', updated_at = NOW()
WHERE id = $1 AND status = 'open'
RETURNING id, target_type, target_id, description, collage_id, snapshot_id, created_by, status, resolved_type, resolved_id, resolved_by, resolved_at, created_at, updated_at
`

// Marks a query dead. Distinct from leaving it open: an abandoned query is one the
// community voted down, and re-surfacing it in the queue forever is how a board
// fills with questions nobody wants.
func (q *Queries) AbandonIdentificationQuery(ctx context.Context, id uuid.UUID) (IdentificationQuery, error) {
	row := q.db.QueryRow(ctx, abandonIdentificationQuery, id)
	var i IdentificationQuery
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.Description,
		&i.CollageID,
		&i.SnapshotID,
		&i.CreatedBy,
		&i.Status,
		&i.ResolvedType,
		&i.ResolvedID,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addIdentificationCandidate = `-- name: AddIdentificationCandidate :one
INSERT INTO identification_candidates
    (id, query_id, entity_type, entity_id, note, suggested_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, query_id, entity_type, entity_id, note, suggested_by, created_at
`

type AddIdentificationCandidateParams struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	QueryID     uuid.UUID     `db:"query_id" json:"query_id"`
	EntityType  string        `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID     `db:"entity_id" json:"entity_id"`
	Note        *string       `db:"note" json:"note"`
	SuggestedBy uuid.NullUUID `db:"suggested_by" json:"suggested_by"`
}

// Proposes a candidate.
//
// The unique (query_id, entity_type, entity_id) means one suggestion per entity
// per query: re-suggesting is not more signal, and allowing it would let one
// person weight the vote.
func (q *Queries) AddIdentificationCandidate(ctx context.Context, arg AddIdentificationCandidateParams) (IdentificationCandidate, error) {
	row := q.db.QueryRow(ctx, addIdentificationCandidate,
		arg.ID,
		arg.QueryID,
		arg.EntityType,
		arg.EntityID,
		arg.Note,
		arg.SuggestedBy,
	)
	var i IdentificationCandidate
	err := row.Scan(
		&i.ID,
		&i.QueryID,
		&i.EntityType,
		&i.EntityID,
		&i.Note,
		&i.SuggestedBy,
		&i.CreatedAt,
	)
	return i, err
}

const countIdentificationVotesForUser = `-- name: CountIdentificationVotesForUser :one
SELECT count(*)
FROM identification_candidate_votes v
JOIN identification_candidates c ON c.id = v.candidate_id
JOIN identification_queries q ON q.id = c.query_id
WHERE v.user_id = $1 AND q.status = 'open'
`

// How many candidates this user has voted on, anywhere.
//
// Backs §5's "Detective" leaderboard. Counting through the candidate table rather
// than straight at the votes, so a vote on a candidate whose query has been
// deleted does not count: the vote is evidence about a question that no longer
// exists.
func (q *Queries) CountIdentificationVotesForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIdentificationVotesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVotesForCandidate = `-- name: CountVotesForCandidate :one
SELECT count(user_id) FROM identification_candidate_votes
WHERE candidate_id = $1
`

// A single candidate's tally.
//
// Counted here rather than joined into GetIdentificationCandidate because a vote
// mutation needs this one row and the grouped per-query query would be a scan of
// every candidate on the query to answer "how many votes does this one have".
func (q *Queries) CountVotesForCandidate(ctx context.Context, candidateID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVotesForCandidate, candidateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdentificationQuery = `-- name: CreateIdentificationQuery :one

INSERT INTO identification_queries
    (id, target_type, target_id, description, collage_id, snapshot_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, target_type, target_id, description, collage_id, snapshot_id, created_by, status, resolved_type, resolved_id, resolved_by, resolved_at, created_at, updated_at
`

type CreateIdentificationQueryParams struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	TargetType  string        `db:"target_type" json:"target_type"`
	TargetID    uuid.NullUUID `db:"target_id" json:"target_id"`
	Description string        `db:"description" json:"description"`
	CollageID   uuid.NullUUID `db:"collage_id" json:"collage_id"`
	SnapshotID  uuid.NullUUID `db:"snapshot_id" json:"snapshot_id"`
	CreatedBy   uuid.NullUUID `db:"created_by" json:"created_by"`
}

// Identification board queries (SPEC §5, migration 79).
//
// Three tables with one rule running through all of them: a vote is EVIDENCE, not
// authority. Nothing here writes to scenes/performers/etc, and the resolution path
// records what a human decided rather than inferring it from a tally.
func (q *Queries) CreateIdentificationQuery(ctx context.Context, arg CreateIdentificationQueryParams) (IdentificationQuery, error) {
	row := q.db.QueryRow(ctx, createIdentificationQuery,
		arg.ID,
		arg.TargetType,
		arg.TargetID,
		arg.Description,
		arg.CollageID,
		arg.SnapshotID,
		arg.CreatedBy,
	)
	var i IdentificationQuery
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.Description,
		&i.CollageID,
		&i.SnapshotID,
		&i.CreatedBy,
		&i.Status,
		&i.ResolvedType,
		&i.ResolvedID,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentificationCandidate = `-- name: GetIdentificationCandidate :one
SELECT c.id, c.query_id, c.entity_type, c.entity_id, c.note, c.suggested_by, c.created_at, q.status AS query_status, q.target_type AS query_target_type
FROM identification_candidates c
JOIN identification_queries q ON q.id = c.query_id
WHERE c.id = $1
`

type GetIdentificationCandidateRow struct {
	ID              uuid.UUID     `db:"id" json:"id"`
	QueryID         uuid.UUID     `db:"query_id" json:"query_id"`
	EntityType      string        `db:"entity_type" json:"entity_type"`
	EntityID        uuid.UUID     `db:"entity_id" json:"entity_id"`
	Note            *string       `db:"note" json:"note"`
	SuggestedBy     uuid.NullUUID `db:"suggested_by" json:"suggested_by"`
	CreatedAt       time.Time     `db:"created_at" json:"created_at"`
	QueryStatus     string        `db:"query_status" json:"query_status"`
	QueryTargetType string        `db:"query_target_type" json:"query_target_type"`
}

// A single candidate, for the vote path.
//
// Joins the query so the caller can check the query is still open without a
// second round trip -- voting on a resolved query is meaningless and the vote
// would be counted for nothing.
func (q *Queries) GetIdentificationCandidate(ctx context.Context, id uuid.UUID) (GetIdentificationCandidateRow, error) {
	row := q.db.QueryRow(ctx, getIdentificationCandidate, id)
	var i GetIdentificationCandidateRow
	err := row.Scan(
		&i.ID,
		&i.QueryID,
		&i.EntityType,
		&i.EntityID,
		&i.Note,
		&i.SuggestedBy,
		&i.CreatedAt,
		&i.QueryStatus,
		&i.QueryTargetType,
	)
	return i, err
}

const getIdentificationQuery = `-- name: GetIdentificationQuery :one
SELECT id, target_type, target_id, description, collage_id, snapshot_id, created_by, status, resolved_type, resolved_id, resolved_by, resolved_at, created_at, updated_at FROM identification_queries WHERE id = $1
`

func (q *Queries) GetIdentificationQuery(ctx context.Context, id uuid.UUID) (IdentificationQuery, error) {
	row := q.db.QueryRow(ctx, getIdentificationQuery, id)
	var i IdentificationQuery
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.Description,
		&i.CollageID,
		&i.SnapshotID,
		&i.CreatedBy,
		&i.Status,
		&i.ResolvedType,
		&i.ResolvedID,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasVotedForCandidate = `-- name: HasVotedForCandidate :one
SELECT EXISTS (
    SELECT 1 FROM identification_candidate_votes
    WHERE candidate_id = $1 AND user_id = $2
)
`

type HasVotedForCandidateParams struct {
	CandidateID uuid.UUID `db:"candidate_id" json:"candidate_id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
}

// Whether THIS user already voted, so the UI can render a vote button as a state
// rather than as an action that silently does nothing.
func (q *Queries) HasVotedForCandidate(ctx context.Context, arg HasVotedForCandidateParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasVotedForCandidate, arg.CandidateID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listIdentificationCandidates = `-- name: ListIdentificationCandidates :many
SELECT c.id, c.query_id, c.entity_type, c.entity_id, c.note, c.suggested_by,
       c.created_at, count(v.user_id) AS vote_count
FROM identification_candidates c
LEFT JOIN identification_candidate_votes v ON v.candidate_id = c.id
WHERE c.query_id = $1
GROUP BY c.id
ORDER BY count(v.user_id) DESC, c.created_at ASC
LIMIT $2
`

type ListIdentificationCandidatesParams struct {
	QueryID uuid.UUID `db:"query_id" json:"query_id"`
	Limit   int32     `db:"limit" json:"limit"`
}

type ListIdentificationCandidatesRow struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	QueryID     uuid.UUID     `db:"query_id" json:"query_id"`
	EntityType  string        `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID     `db:"entity_id" json:"entity_id"`
	Note        *string       `db:"note" json:"note"`
	SuggestedBy uuid.NullUUID `db:"suggested_by" json:"suggested_by"`
	CreatedAt   time.Time     `db:"created_at" json:"created_at"`
	VoteCount   int64         `db:"vote_count" json:"vote_count"`
}

// A query's candidates WITH their tallies.
//
// LEFT JOIN plus count, so a candidate nobody has voted for still appears with
// zero. An INNER JOIN would silently hide every freshly-suggested candidate,
// which is exactly when someone needs to see it.
//
// count(DISTINCT v.user_id) rather than count(v.*): the vote table's primary key
// already makes the rows distinct, but the DISTINCT documents that the tally is
// of PEOPLE, which is the number §5's leaderboards are built from.
func (q *Queries) ListIdentificationCandidates(ctx context.Context, arg ListIdentificationCandidatesParams) ([]ListIdentificationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listIdentificationCandidates, arg.QueryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdentificationCandidatesRow{}
	for rows.Next() {
		var i ListIdentificationCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.QueryID,
			&i.EntityType,
			&i.EntityID,
			&i.Note,
			&i.SuggestedBy,
			&i.CreatedAt,
			&i.VoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentificationQueriesByCreator = `-- name: ListIdentificationQueriesByCreator :many
SELECT id, target_type, target_id, description, collage_id, snapshot_id, created_by, status, resolved_type, resolved_id, resolved_by, resolved_at, created_at, updated_at FROM identification_queries
WHERE created_by = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListIdentificationQueriesByCreatorParams struct {
	CreatedBy uuid.NullUUID `db:"created_by" json:"created_by"`
	Limit     int32         `db:"limit" json:"limit"`
}

// A user's own questions, so they can see what they asked and what got solved.
func (q *Queries) ListIdentificationQueriesByCreator(ctx context.Context, arg ListIdentificationQueriesByCreatorParams) ([]IdentificationQuery, error) {
	rows, err := q.db.Query(ctx, listIdentificationQueriesByCreator, arg.CreatedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentificationQuery{}
	for rows.Next() {
		var i IdentificationQuery
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.Description,
			&i.CollageID,
			&i.SnapshotID,
			&i.CreatedBy,
			&i.Status,
			&i.ResolvedType,
			&i.ResolvedID,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentificationQueriesByStatus = `-- name: ListIdentificationQueriesByStatus :many
SELECT id, target_type, target_id, description, collage_id, snapshot_id, created_by, status, resolved_type, resolved_id, resolved_by, resolved_at, created_at, updated_at FROM identification_queries
WHERE status = $1
ORDER BY created_at DESC, id
LIMIT $2
`

type ListIdentificationQueriesByStatusParams struct {
	Status string `db:"status" json:"status"`
	Limit  int32  `db:"limit" json:"limit"`
}

// Every query in a state, for moderation and for §5's "solved" archive view.
func (q *Queries) ListIdentificationQueriesByStatus(ctx context.Context, arg ListIdentificationQueriesByStatusParams) ([]IdentificationQuery, error) {
	rows, err := q.db.Query(ctx, listIdentificationQueriesByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentificationQuery{}
	for rows.Next() {
		var i IdentificationQuery
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.Description,
			&i.CollageID,
			&i.SnapshotID,
			&i.CreatedBy,
			&i.Status,
			&i.ResolvedType,
			&i.ResolvedID,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIdentificationQueries = `-- name: ListOpenIdentificationQueries :many
SELECT id, target_type, target_id, description, collage_id, snapshot_id, created_by, status, resolved_type, resolved_id, resolved_by, resolved_at, created_at, updated_at FROM identification_queries
WHERE status = 'open'
ORDER BY created_at DESC, id
LIMIT $1
`

// The board's queue: open queries, newest first.
//
// Bounded by the caller and defaulted in the service. An unbounded queue is a
// denial-of-service vector, and no UI renders more than a few hundred.
//
// The partial index on status='open' covers exactly this, so the filter is not
// costing a scan of solved and abandoned queries.
func (q *Queries) ListOpenIdentificationQueries(ctx context.Context, limit int32) ([]IdentificationQuery, error) {
	rows, err := q.db.Query(ctx, listOpenIdentificationQueries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentificationQuery{}
	for rows.Next() {
		var i IdentificationQuery
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.Description,
			&i.CollageID,
			&i.SnapshotID,
			&i.CreatedBy,
			&i.Status,
			&i.ResolvedType,
			&i.ResolvedID,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolvedQueriesForEntity = `-- name: ListResolvedQueriesForEntity :many
SELECT id, target_type, target_id, description, collage_id, snapshot_id, created_by, status, resolved_type, resolved_id, resolved_by, resolved_at, created_at, updated_at FROM identification_queries
WHERE resolved_type = $1 AND resolved_id = $2 AND status = 'solved'
ORDER BY resolved_at DESC
LIMIT $3
`

type ListResolvedQueriesForEntityParams struct {
	ResolvedType *string       `db:"resolved_type" json:"resolved_type"`
	ResolvedID   uuid.NullUUID `db:"resolved_id" json:"resolved_id"`
	Limit        int32         `db:"limit" json:"limit"`
}

// "Everything the community has worked out about this performer."
//
// This is the query that turns a solved query into a CANONICAL LINK, per §5: the
// answer is that the board's conclusions are indexed against real metadata, so
// finding an entity also finds what was learned about it.
func (q *Queries) ListResolvedQueriesForEntity(ctx context.Context, arg ListResolvedQueriesForEntityParams) ([]IdentificationQuery, error) {
	rows, err := q.db.Query(ctx, listResolvedQueriesForEntity, arg.ResolvedType, arg.ResolvedID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentificationQuery{}
	for rows.Next() {
		var i IdentificationQuery
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.Description,
			&i.CollageID,
			&i.SnapshotID,
			&i.CreatedBy,
			&i.Status,
			&i.ResolvedType,
			&i.ResolvedID,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveIdentificationQuery = `-- name: ResolveIdentificationQuery :one
UPDATE identification_queries
SET status = 'solved',
    resolved_type = $2,
    resolved_id = $3,
    resolved_by = $4,
    resolved_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND status = 'open'
RETURNING id, target_type, target_id, description, collage_id, snapshot_id, created_by, status, resolved_type, resolved_id, resolved_by, resolved_at, created_at, updated_at
`

type ResolveIdentificationQueryParams struct {
	ID           uuid.UUID     `db:"id" json:"id"`
	ResolvedType *string       `db:"resolved_type" json:"resolved_type"`
	ResolvedID   uuid.NullUUID `db:"resolved_id" json:"resolved_id"`
	ResolvedBy   uuid.NullUUID `db:"resolved_by" json:"resolved_by"`
}

// Records what a HUMAN decided a query was.
//
// The CHECK constraint enforces that a solved query names its resolution, so
// there is no way to mark one solved with nothing attached -- which is the
// failure that would make every consumer of the "solved" view re-verify it.
//
// Guarded on status='open' so a second resolution attempt is a no-op returning no
// rows rather than an overwrite. Two people clicking "accept" on different
// candidates at the same time is a real race, and last-write-wins would silently
// discard one person's work.
func (q *Queries) ResolveIdentificationQuery(ctx context.Context, arg ResolveIdentificationQueryParams) (IdentificationQuery, error) {
	row := q.db.QueryRow(ctx, resolveIdentificationQuery,
		arg.ID,
		arg.ResolvedType,
		arg.ResolvedID,
		arg.ResolvedBy,
	)
	var i IdentificationQuery
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.Description,
		&i.CollageID,
		&i.SnapshotID,
		&i.CreatedBy,
		&i.Status,
		&i.ResolvedType,
		&i.ResolvedID,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unvoteIdentificationCandidate = `-- name: UnvoteIdentificationCandidate :exec
DELETE FROM identification_candidate_votes
WHERE candidate_id = $1 AND user_id = $2
`

type UnvoteIdentificationCandidateParams struct {
	CandidateID uuid.UUID `db:"candidate_id" json:"candidate_id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UnvoteIdentificationCandidate(ctx context.Context, arg UnvoteIdentificationCandidateParams) error {
	_, err := q.db.Exec(ctx, unvoteIdentificationCandidate, arg.CandidateID, arg.UserID)
	return err
}

const voteForIdentificationCandidate = `-- name: VoteForIdentificationCandidate :exec
INSERT INTO identification_candidate_votes (candidate_id, user_id)
VALUES ($1, $2)
`

type VoteForIdentificationCandidateParams struct {
	CandidateID uuid.UUID `db:"candidate_id" json:"candidate_id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
}

// One vote. The composite primary key on the vote table is the rule: a second
// vote is a constraint violation rather than a silently doubled tally.
func (q *Queries) VoteForIdentificationCandidate(ctx context.Context, arg VoteForIdentificationCandidateParams) error {
	_, err := q.db.Exec(ctx, voteForIdentificationCandidate, arg.CandidateID, arg.UserID)
	return err
}
