// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: list.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

const addListItem = `-- name: AddListItem :one
INSERT INTO list_items (list_id, entity_type, entity_id, position)
VALUES ($1, $2, $3, $4)
RETURNING id, list_id, entity_type, entity_id, position, created_at
`

type AddListItemParams struct {
	ListID     uuid.UUID     `db:"list_id" json:"list_id"`
	EntityType *string       `db:"entity_type" json:"entity_type"`
	EntityID   uuid.NullUUID `db:"entity_id" json:"entity_id"`
	Position   int           `db:"position" json:"position"`
}

func (q *Queries) AddListItem(ctx context.Context, arg AddListItemParams) (ListItem, error) {
	row := q.db.QueryRow(ctx, addListItem,
		arg.ListID,
		arg.EntityType,
		arg.EntityID,
		arg.Position,
	)
	var i ListItem
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.EntityType,
		&i.EntityID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const countListItems = `-- name: CountListItems :one
SELECT count(*) FROM list_items WHERE list_id = $1
`

func (q *Queries) CountListItems(ctx context.Context, listID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countListItems, listID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedLists = `-- name: CountPublishedLists :one
SELECT count(*) FROM lists WHERE published_at IS NOT NULL
`

func (q *Queries) CountPublishedLists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedLists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createList = `-- name: CreateList :one
INSERT INTO lists (id, owner_id, name, description, owner_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, name, description, published_at, published_by, owner_name, created_at, updated_at
`

type CreateListParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	OwnerID     uuid.UUID `db:"owner_id" json:"owner_id"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
	OwnerName   string    `db:"owner_name" json:"owner_name"`
}

// A new list, PRIVATE by construction.
//
// `published_at` and `published_by` are absent from this statement entirely rather than
// set to NULL. A create that mentioned them would be a create that could publish, and the
// policy says publication is a separate, deliberate, auditable act -- so the way to make
// that structural is for the INSERT to have no column to publish through.
func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.OwnerName,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.OwnerName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM lists WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteList, id)
	return err
}

const findList = `-- name: FindList :one
SELECT id, owner_id, name, description, published_at, published_by, owner_name, created_at, updated_at FROM lists WHERE id = $1
`

func (q *Queries) FindList(ctx context.Context, id uuid.UUID) (List, error) {
	row := q.db.QueryRow(ctx, findList, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.OwnerName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findListAudit = `-- name: FindListAudit :many
SELECT id, list_id, actor_id, action, created_at FROM list_audit WHERE list_id = $1 ORDER BY created_at DESC, id DESC
`

// A list's publication history, newest first.
func (q *Queries) FindListAudit(ctx context.Context, listID uuid.UUID) ([]ListAudit, error) {
	rows, err := q.db.Query(ctx, findListAudit, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAudit{}
	for rows.Next() {
		var i ListAudit
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.ActorID,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findListByName = `-- name: FindListByName :one
SELECT id, owner_id, name, description, published_at, published_by, owner_name, created_at, updated_at FROM lists WHERE owner_id = $1 AND name = $2
`

type FindListByNameParams struct {
	OwnerID uuid.UUID `db:"owner_id" json:"owner_id"`
	Name    string    `db:"name" json:"name"`
}

// Lookup for the "you already have a list called this" check. Scoped to the owner because
// names are unique per owner, not globally.
func (q *Queries) FindListByName(ctx context.Context, arg FindListByNameParams) (List, error) {
	row := q.db.QueryRow(ctx, findListByName, arg.OwnerID, arg.Name)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.OwnerName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findListItems = `-- name: FindListItems :many
SELECT id, list_id, entity_type, entity_id, position, created_at FROM list_items WHERE list_id = $1 ORDER BY position ASC, id ASC
`

// A list's contents in display order.
//
// `position` then `id`: position is client-supplied and ties are common (every item added
// in one bulk request gets the same position), so id breaks them deterministically. Without
// the tiebreak, two clients paginating the same list can see different orders.
func (q *Queries) FindListItems(ctx context.Context, listID uuid.UUID) ([]ListItem, error) {
	rows, err := q.db.Query(ctx, findListItems, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItem{}
	for rows.Next() {
		var i ListItem
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.EntityType,
			&i.EntityID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findListsByIds = `-- name: FindListsByIds :many
SELECT id, owner_id, name, description, published_at, published_by, owner_name, created_at, updated_at FROM lists WHERE id = ANY($1::UUID[])
`

// Batch lookup by id, used to resolve the lists a caller may see.
//
// Deliberately NOT filtered on published_at. Visibility is decided by the caller with the
// full row in hand -- a draft is returned with its NULL published_at so the caller can tell
// "private" from "does not exist" -- and a filter here would erase that distinction.
func (q *Queries) FindListsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]List, error) {
	rows, err := q.db.Query(ctx, findListsByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.OwnerName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findListsByOwner = `-- name: FindListsByOwner :many
SELECT id, owner_id, name, description, published_at, published_by, owner_name, created_at, updated_at FROM lists WHERE owner_id = $1 ORDER BY name ASC
`

// Everything an owner has, drafts included. This is the one listing that shows private
// lists, and it is reachable only by someone entitled to see that owner's drafts.
func (q *Queries) FindListsByOwner(ctx context.Context, ownerID uuid.UUID) ([]List, error) {
	rows, err := q.db.Query(ctx, findListsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.OwnerName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPublishedLists = `-- name: FindPublishedLists :many
SELECT id, owner_id, name, description, published_at, published_by, owner_name, created_at, updated_at FROM lists
 WHERE published_at IS NOT NULL
 ORDER BY published_at DESC, id DESC
 LIMIT $1 OFFSET $2
`

type FindPublishedListsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

// The browse listing: PUBLISHED lists only, newest publication first.
//
// The WHERE is not decoration. It mirrors the partial index, so the query is answered by
// the index alone; a draft is not merely excluded from the result, it is not in the index.
func (q *Queries) FindPublishedLists(ctx context.Context, arg FindPublishedListsParams) ([]List, error) {
	rows, err := q.db.Query(ctx, findPublishedLists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.OwnerName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListItem = `-- name: GetListItem :one
SELECT id, list_id, entity_type, entity_id, position, created_at FROM list_items WHERE id = $1
`

// A single item by its own id.
//
// Needed by reorder and remove, which are addressed by ITEM id and must therefore
// resolve the item's list before deciding whether the caller may touch it. Without this,
// the only alternative is FindListItems(listID) -- which takes a LIST id -- so addressing
// an item would silently resolve the wrong row.
func (q *Queries) GetListItem(ctx context.Context, id uuid.UUID) (ListItem, error) {
	row := q.db.QueryRow(ctx, getListItem, id)
	var i ListItem
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.EntityType,
		&i.EntityID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const publishList = `-- name: PublishList :one
UPDATE lists SET published_at = now(), published_by = $2, updated_at = now()
WHERE id = $1 AND published_at IS NULL
RETURNING id, owner_id, name, description, published_at, published_by, owner_name, created_at, updated_at
`

type PublishListParams struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	PublishedBy uuid.NullUUID `db:"published_by" json:"published_by"`
}

// Publish, recording WHEN and WHO in the same statement.
//
// One statement rather than an UPDATE followed by an INSERT into list_audit, because the
// two must agree: a publication without its audit row is exactly the state the policy
// forbids, and splitting the write makes that state reachable if the second statement
// fails.
func (q *Queries) PublishList(ctx context.Context, arg PublishListParams) (List, error) {
	row := q.db.QueryRow(ctx, publishList, arg.ID, arg.PublishedBy)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.OwnerName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordListAudit = `-- name: RecordListAudit :exec
INSERT INTO list_audit (list_id, actor_id, action) VALUES ($1, $2, $3)
`

type RecordListAuditParams struct {
	ListID  uuid.UUID     `db:"list_id" json:"list_id"`
	ActorID uuid.NullUUID `db:"actor_id" json:"actor_id"`
	Action  string        `db:"action" json:"action"`
}

func (q *Queries) RecordListAudit(ctx context.Context, arg RecordListAuditParams) error {
	_, err := q.db.Exec(ctx, recordListAudit, arg.ListID, arg.ActorID, arg.Action)
	return err
}

const removeListItem = `-- name: RemoveListItem :exec
DELETE FROM list_items WHERE id = $1
`

func (q *Queries) RemoveListItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeListItem, id)
	return err
}

const removeListItemsByEntity = `-- name: RemoveListItemsByEntity :exec
DELETE FROM list_items WHERE list_id = $1 AND entity_id = $2
`

type RemoveListItemsByEntityParams struct {
	ListID   uuid.UUID     `db:"list_id" json:"list_id"`
	EntityID uuid.NullUUID `db:"entity_id" json:"entity_id"`
}

func (q *Queries) RemoveListItemsByEntity(ctx context.Context, arg RemoveListItemsByEntityParams) error {
	_, err := q.db.Exec(ctx, removeListItemsByEntity, arg.ListID, arg.EntityID)
	return err
}

const reorderListItems = `-- name: ReorderListItems :exec
UPDATE list_items SET position = $2 WHERE id = $1
`

type ReorderListItemsParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Position int       `db:"position" json:"position"`
}

// Set an explicit position for one item. Reordering is one row at a time rather than a bulk
// swap, because a list has no version column and a concurrent reorder would otherwise be
// last-write-wins across the whole list with no way to detect it.
func (q *Queries) ReorderListItems(ctx context.Context, arg ReorderListItemsParams) error {
	_, err := q.db.Exec(ctx, reorderListItems, arg.ID, arg.Position)
	return err
}

const unpublishList = `-- name: UnpublishList :one
UPDATE lists SET published_at = NULL, published_by = NULL, updated_at = now()
WHERE id = $1 AND published_at IS NOT NULL
RETURNING id, owner_id, name, description, published_at, published_by, owner_name, created_at, updated_at
`

// Return to private. The `published_at IS NOT NULL` guard means unpublishing something
// already private is a no-op returning no rows, so a caller cannot fabricate an
// unpublish event for a list that was never published.
func (q *Queries) UnpublishList(ctx context.Context, id uuid.UUID) (List, error) {
	row := q.db.QueryRow(ctx, unpublishList, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.OwnerName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateList = `-- name: UpdateList :one
UPDATE lists SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, owner_id, name, description, published_at, published_by, owner_name, created_at, updated_at
`

type UpdateListParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
}

// Rename / re-describe. NOT re-parenting and NOT publishing: publishing is its own
// statement so it can carry an audit row, and it takes an actor argument.
func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList, arg.ID, arg.Name, arg.Description)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.OwnerName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
