// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stashapp/stash-box/internal/models"
)

type ModAuditAction string

const (
	ModAuditActionEDITDELETE        ModAuditAction = "EDIT_DELETE"
	ModAuditActionEDITAMENDMENT     ModAuditAction = "EDIT_AMENDMENT"
	ModAuditActionEDITCOMMENTUPDATE ModAuditAction = "EDIT_COMMENT_UPDATE"
	ModAuditActionEDITCOMMENTHIDE   ModAuditAction = "EDIT_COMMENT_HIDE"
)

func (e *ModAuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModAuditAction(s)
	case string:
		*e = ModAuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for ModAuditAction: %T", src)
	}
	return nil
}

type NullModAuditAction struct {
	ModAuditAction ModAuditAction `json:"mod_audit_action"`
	Valid          bool           `json:"valid"` // Valid is true if ModAuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.ModAuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModAuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModAuditAction), nil
}

type NotificationType string

const (
	NotificationTypeFAVORITEPERFORMERSCENE NotificationType = "FAVORITE_PERFORMER_SCENE"
	NotificationTypeFAVORITEPERFORMEREDIT  NotificationType = "FAVORITE_PERFORMER_EDIT"
	NotificationTypeFAVORITESTUDIOSCENE    NotificationType = "FAVORITE_STUDIO_SCENE"
	NotificationTypeFAVORITESTUDIOEDIT     NotificationType = "FAVORITE_STUDIO_EDIT"
	NotificationTypeCOMMENTOWNEDIT         NotificationType = "COMMENT_OWN_EDIT"
	NotificationTypeDOWNVOTEOWNEDIT        NotificationType = "DOWNVOTE_OWN_EDIT"
	NotificationTypeFAILEDOWNEDIT          NotificationType = "FAILED_OWN_EDIT"
	NotificationTypeCOMMENTCOMMENTEDEDIT   NotificationType = "COMMENT_COMMENTED_EDIT"
	NotificationTypeCOMMENTVOTEDEDIT       NotificationType = "COMMENT_VOTED_EDIT"
	NotificationTypeUPDATEDEDIT            NotificationType = "UPDATED_EDIT"
	NotificationTypeFINGERPRINTEDSCENEEDIT NotificationType = "FINGERPRINTED_SCENE_EDIT"
	NotificationTypeFINGERPRINTMOVED       NotificationType = "FINGERPRINT_MOVED"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type AuthoredQuest struct {
	ID           uuid.UUID     `db:"id" json:"id"`
	EntityType   string        `db:"entity_type" json:"entity_type"`
	Field        string        `db:"field" json:"field"`
	Target       int           `db:"target" json:"target"`
	BountyPoints int           `db:"bounty_points" json:"bounty_points"`
	Reason       *string       `db:"reason" json:"reason"`
	AuthoredBy   uuid.NullUUID `db:"authored_by" json:"authored_by"`
	ExpiresAt    *time.Time    `db:"expires_at" json:"expires_at"`
	CreatedAt    time.Time     `db:"created_at" json:"created_at"`
}

type AuthoredQuestItem struct {
	ID         uuid.UUID     `db:"id" json:"id"`
	QuestID    uuid.UUID     `db:"quest_id" json:"quest_id"`
	EntityType string        `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID     `db:"entity_id" json:"entity_id"`
	ClaimedBy  uuid.NullUUID `db:"claimed_by" json:"claimed_by"`
	ClaimedAt  *time.Time    `db:"claimed_at" json:"claimed_at"`
	CreatedAt  time.Time     `db:"created_at" json:"created_at"`
}

type Collage struct {
	ID                uuid.UUID   `db:"id" json:"id"`
	SceneID           uuid.UUID   `db:"scene_id" json:"scene_id"`
	FrameCount        int         `db:"frame_count" json:"frame_count"`
	Strategy          string      `db:"strategy" json:"strategy"`
	SourceDurationMs  pgtype.Int8 `db:"source_duration_ms" json:"source_duration_ms"`
	CurrentDurationMs pgtype.Int8 `db:"current_duration_ms" json:"current_duration_ms"`
	GeneratedAt       time.Time   `db:"generated_at" json:"generated_at"`
}

type Draft struct {
	ID        uuid.UUID       `db:"id" json:"id"`
	UserID    uuid.UUID       `db:"user_id" json:"user_id"`
	Type      string          `db:"type" json:"type"`
	Data      json.RawMessage `db:"data" json:"data"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
}

type Edit struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	UserID      uuid.NullUUID `db:"user_id" json:"user_id"`
	Operation   string        `db:"operation" json:"operation"`
	TargetType  string        `db:"target_type" json:"target_type"`
	Data        []byte        `db:"data" json:"data"`
	Votes       int           `db:"votes" json:"votes"`
	Status      string        `db:"status" json:"status"`
	Applied     bool          `db:"applied" json:"applied"`
	CreatedAt   time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time    `db:"updated_at" json:"updated_at"`
	ClosedAt    *time.Time    `db:"closed_at" json:"closed_at"`
	Bot         bool          `db:"bot" json:"bot"`
	UpdateCount int           `db:"update_count" json:"update_count"`
}

type EditComment struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	EditID    uuid.UUID     `db:"edit_id" json:"edit_id"`
	UserID    uuid.NullUUID `db:"user_id" json:"user_id"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	Text      string        `db:"text" json:"text"`
	UpdatedAt *time.Time    `db:"updated_at" json:"updated_at"`
	IsHidden  bool          `db:"is_hidden" json:"is_hidden"`
}

type EditVote struct {
	EditID    uuid.UUID     `db:"edit_id" json:"edit_id"`
	UserID    uuid.NullUUID `db:"user_id" json:"user_id"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	Vote      string        `db:"vote" json:"vote"`
}

type EloRating struct {
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	Rating      int                `db:"rating" json:"rating"`
	Deviation   float64            `db:"deviation" json:"deviation"`
	Volatility  float64            `db:"volatility" json:"volatility"`
	LastRatedAt pgtype.Timestamptz `db:"last_rated_at" json:"last_rated_at"`
}

type EloVote struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	WinnerID   uuid.UUID          `db:"winner_id" json:"winner_id"`
	LoserID    uuid.UUID          `db:"loser_id" json:"loser_id"`
	WinnerType string             `db:"winner_type" json:"winner_type"`
	LoserType  string             `db:"loser_type" json:"loser_type"`
	PickedSide int16              `db:"picked_side" json:"picked_side"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Fingerprint struct {
	ID        int    `db:"id" json:"id"`
	Algorithm string `db:"algorithm" json:"algorithm"`
	Hash      int64  `db:"hash" json:"hash"`
}

type IdentificationCandidate struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	QueryID     uuid.UUID     `db:"query_id" json:"query_id"`
	EntityType  string        `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID     `db:"entity_id" json:"entity_id"`
	Note        *string       `db:"note" json:"note"`
	SuggestedBy uuid.NullUUID `db:"suggested_by" json:"suggested_by"`
	CreatedAt   time.Time     `db:"created_at" json:"created_at"`
}

type IdentificationCandidateVote struct {
	CandidateID uuid.UUID `db:"candidate_id" json:"candidate_id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

type IdentificationQuery struct {
	ID           uuid.UUID     `db:"id" json:"id"`
	TargetType   string        `db:"target_type" json:"target_type"`
	TargetID     uuid.NullUUID `db:"target_id" json:"target_id"`
	Description  string        `db:"description" json:"description"`
	CollageID    uuid.NullUUID `db:"collage_id" json:"collage_id"`
	SnapshotID   uuid.NullUUID `db:"snapshot_id" json:"snapshot_id"`
	CreatedBy    uuid.NullUUID `db:"created_by" json:"created_by"`
	Status       string        `db:"status" json:"status"`
	ResolvedType *string       `db:"resolved_type" json:"resolved_type"`
	ResolvedID   uuid.NullUUID `db:"resolved_id" json:"resolved_id"`
	ResolvedBy   uuid.NullUUID `db:"resolved_by" json:"resolved_by"`
	ResolvedAt   *time.Time    `db:"resolved_at" json:"resolved_at"`
	CreatedAt    time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time     `db:"updated_at" json:"updated_at"`
}

type Image struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Url      *string   `db:"url" json:"url"`
	Width    int       `db:"width" json:"width"`
	Height   int       `db:"height" json:"height"`
	Checksum string    `db:"checksum" json:"checksum"`
}

type InviteKey struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	GeneratedBy uuid.UUID  `db:"generated_by" json:"generated_by"`
	GeneratedAt time.Time  `db:"generated_at" json:"generated_at"`
	Uses        *int       `db:"uses" json:"uses"`
	ExpireTime  *time.Time `db:"expire_time" json:"expire_time"`
}

type ModAudit struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	Action     ModAuditAction  `db:"action" json:"action"`
	UserID     uuid.NullUUID   `db:"user_id" json:"user_id"`
	TargetID   uuid.UUID       `db:"target_id" json:"target_id"`
	TargetType string          `db:"target_type" json:"target_type"`
	Data       json.RawMessage `db:"data" json:"data"`
	Reason     *string         `db:"reason" json:"reason"`
	CreatedAt  time.Time       `db:"created_at" json:"created_at"`
}

type Notification struct {
	UserID    uuid.UUID        `db:"user_id" json:"user_id"`
	Type      NotificationType `db:"type" json:"type"`
	ID        uuid.UUID        `db:"id" json:"id"`
	CreatedAt time.Time        `db:"created_at" json:"created_at"`
	ReadAt    *time.Time       `db:"read_at" json:"read_at"`
	Data      *json.RawMessage `db:"data" json:"data"`
}

type Performer struct {
	ID              uuid.UUID              `db:"id" json:"id"`
	Name            string                 `db:"name" json:"name"`
	Disambiguation  *string                `db:"disambiguation" json:"disambiguation"`
	Gender          *models.GenderEnum     `db:"gender" json:"gender"`
	Ethnicity       *models.EthnicityEnum  `db:"ethnicity" json:"ethnicity"`
	Country         *string                `db:"country" json:"country"`
	EyeColor        *models.EyeColorEnum   `db:"eye_color" json:"eye_color"`
	HairColor       *models.HairColorEnum  `db:"hair_color" json:"hair_color"`
	Height          *int                   `db:"height" json:"height"`
	CupSize         *string                `db:"cup_size" json:"cup_size"`
	BandSize        *int                   `db:"band_size" json:"band_size"`
	HipSize         *int                   `db:"hip_size" json:"hip_size"`
	WaistSize       *int                   `db:"waist_size" json:"waist_size"`
	BreastType      *models.BreastTypeEnum `db:"breast_type" json:"breast_type"`
	CareerStartYear *int                   `db:"career_start_year" json:"career_start_year"`
	CareerEndYear   *int                   `db:"career_end_year" json:"career_end_year"`
	CreatedAt       time.Time              `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time              `db:"updated_at" json:"updated_at"`
	Deleted         bool                   `db:"deleted" json:"deleted"`
	Birthdate       *string                `db:"birthdate" json:"birthdate"`
	Deathdate       *string                `db:"deathdate" json:"deathdate"`
}

type PerformerAlias struct {
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	Alias       string    `db:"alias" json:"alias"`
}

type PerformerEdit struct {
	EditID      uuid.UUID `db:"edit_id" json:"edit_id"`
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
}

type PerformerFavorite struct {
	PerformerID uuid.UUID  `db:"performer_id" json:"performer_id"`
	UserID      uuid.UUID  `db:"user_id" json:"user_id"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
}

type PerformerImage struct {
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	ImageID     uuid.UUID `db:"image_id" json:"image_id"`
}

type PerformerPiercing struct {
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	Location    *string   `db:"location" json:"location"`
	Description *string   `db:"description" json:"description"`
}

type PerformerPopularityAllTime struct {
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	UserCount   int       `db:"user_count" json:"user_count"`
}

type PerformerRedirect struct {
	SourceID uuid.UUID `db:"source_id" json:"source_id"`
	TargetID uuid.UUID `db:"target_id" json:"target_id"`
}

type PerformerSearch struct {
	PerformerID    uuid.UUID `db:"performer_id" json:"performer_id"`
	Name           *string   `db:"name" json:"name"`
	Disambiguation *string   `db:"disambiguation" json:"disambiguation"`
	Aliases        []string  `db:"aliases" json:"aliases"`
	Gender         *string   `db:"gender" json:"gender"`
}

type PerformerTattoo struct {
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	Location    *string   `db:"location" json:"location"`
	Description *string   `db:"description" json:"description"`
}

type PerformerUrl struct {
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	Url         string    `db:"url" json:"url"`
	SiteID      uuid.UUID `db:"site_id" json:"site_id"`
}

type Review struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	AuthorID   uuid.UUID          `db:"author_id" json:"author_id"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID          `db:"entity_id" json:"entity_id"`
	Rating     *int               `db:"rating" json:"rating"`
	Body       string             `db:"body" json:"body"`
	Verified   bool               `db:"verified" json:"verified"`
	Status     string             `db:"status" json:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Scene struct {
	ID             uuid.UUID     `db:"id" json:"id"`
	Title          *string       `db:"title" json:"title"`
	Details        *string       `db:"details" json:"details"`
	StudioID       uuid.NullUUID `db:"studio_id" json:"studio_id"`
	CreatedAt      time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time     `db:"updated_at" json:"updated_at"`
	Duration       *int          `db:"duration" json:"duration"`
	Director       *string       `db:"director" json:"director"`
	Deleted        bool          `db:"deleted" json:"deleted"`
	Code           *string       `db:"code" json:"code"`
	Date           *string       `db:"date" json:"date"`
	ProductionDate *string       `db:"production_date" json:"production_date"`
}

type SceneEdit struct {
	EditID  uuid.UUID `db:"edit_id" json:"edit_id"`
	SceneID uuid.UUID `db:"scene_id" json:"scene_id"`
}

type SceneFingerprint struct {
	FingerprintID int       `db:"fingerprint_id" json:"fingerprint_id"`
	SceneID       uuid.UUID `db:"scene_id" json:"scene_id"`
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	Duration      int       `db:"duration" json:"duration"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	Vote          int16     `db:"vote" json:"vote"`
}

type SceneImage struct {
	SceneID uuid.UUID `db:"scene_id" json:"scene_id"`
	ImageID uuid.UUID `db:"image_id" json:"image_id"`
}

type ScenePerformer struct {
	SceneID     uuid.UUID `db:"scene_id" json:"scene_id"`
	As          *string   `db:"as" json:"as"`
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
}

type ScenePopularityAllTime struct {
	SceneID   uuid.UUID `db:"scene_id" json:"scene_id"`
	UserCount int       `db:"user_count" json:"user_count"`
}

type ScenePopularityTrending struct {
	SceneID       uuid.UUID `db:"scene_id" json:"scene_id"`
	TrendingCount int       `db:"trending_count" json:"trending_count"`
}

type SceneRedirect struct {
	SourceID uuid.UUID `db:"source_id" json:"source_id"`
	TargetID uuid.UUID `db:"target_id" json:"target_id"`
}

type SceneSearch struct {
	SceneID        uuid.UUID `db:"scene_id" json:"scene_id"`
	SceneTitle     *string   `db:"scene_title" json:"scene_title"`
	SceneDate      *string   `db:"scene_date" json:"scene_date"`
	StudioName     *string   `db:"studio_name" json:"studio_name"`
	NetworkName    *string   `db:"network_name" json:"network_name"`
	StudioAliases  []string  `db:"studio_aliases" json:"studio_aliases"`
	NetworkAliases []string  `db:"network_aliases" json:"network_aliases"`
	PerformerNames []string  `db:"performer_names" json:"performer_names"`
	SceneCode      *string   `db:"scene_code" json:"scene_code"`
}

type SceneSnapshot struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	SceneID     uuid.UUID     `db:"scene_id" json:"scene_id"`
	TimestampMs int64         `db:"timestamp_ms" json:"timestamp_ms"`
	CollageID   uuid.NullUUID `db:"collage_id" json:"collage_id"`
	CreatedBy   uuid.NullUUID `db:"created_by" json:"created_by"`
	CreatedAt   time.Time     `db:"created_at" json:"created_at"`
}

type SceneTag struct {
	SceneID uuid.UUID `db:"scene_id" json:"scene_id"`
	TagID   uuid.UUID `db:"tag_id" json:"tag_id"`
}

type SceneUrl struct {
	SceneID uuid.UUID `db:"scene_id" json:"scene_id"`
	Url     string    `db:"url" json:"url"`
	SiteID  uuid.UUID `db:"site_id" json:"site_id"`
}

type Site struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
	Url         *string   `db:"url" json:"url"`
	Regex       *string   `db:"regex" json:"regex"`
	ValidTypes  []string  `db:"valid_types" json:"valid_types"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
	CategoryID  *int      `db:"category_id" json:"category_id"`
	Highlighted bool      `db:"highlighted" json:"highlighted"`
}

type SiteAlternative struct {
	SiteID            uuid.UUID `db:"site_id" json:"site_id"`
	AlternativeSiteID uuid.UUID `db:"alternative_site_id" json:"alternative_site_id"`
}

type SiteCategory struct {
	ID          int       `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
	SortOrder   int       `db:"sort_order" json:"sort_order"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type SiteDetail struct {
	SiteID         uuid.UUID          `db:"site_id" json:"site_id"`
	Pricing        *string            `db:"pricing" json:"pricing"`
	PaymentMethods []string           `db:"payment_methods" json:"payment_methods"`
	Features       []string           `db:"features" json:"features"`
	Pros           []string           `db:"pros" json:"pros"`
	Cons           []string           `db:"cons" json:"cons"`
	EthicalLabels  []string           `db:"ethical_labels" json:"ethical_labels"`
	UpdatedBy      uuid.NullUUID      `db:"updated_by" json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Studio struct {
	ID             uuid.UUID     `db:"id" json:"id"`
	Name           string        `db:"name" json:"name"`
	ParentStudioID uuid.NullUUID `db:"parent_studio_id" json:"parent_studio_id"`
	CreatedAt      time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time     `db:"updated_at" json:"updated_at"`
	Deleted        bool          `db:"deleted" json:"deleted"`
}

type StudioAlias struct {
	StudioID uuid.UUID `db:"studio_id" json:"studio_id"`
	Alias    string    `db:"alias" json:"alias"`
}

type StudioEdit struct {
	EditID   uuid.UUID `db:"edit_id" json:"edit_id"`
	StudioID uuid.UUID `db:"studio_id" json:"studio_id"`
}

type StudioFavorite struct {
	StudioID  uuid.UUID  `db:"studio_id" json:"studio_id"`
	UserID    uuid.UUID  `db:"user_id" json:"user_id"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type StudioImage struct {
	StudioID uuid.UUID `db:"studio_id" json:"studio_id"`
	ImageID  uuid.UUID `db:"image_id" json:"image_id"`
}

type StudioRedirect struct {
	SourceID uuid.UUID `db:"source_id" json:"source_id"`
	TargetID uuid.UUID `db:"target_id" json:"target_id"`
}

type StudioSearch struct {
	StudioID uuid.UUID `db:"studio_id" json:"studio_id"`
	Name     *string   `db:"name" json:"name"`
	Network  *string   `db:"network" json:"network"`
	Aliases  []string  `db:"aliases" json:"aliases"`
}

type StudioUrl struct {
	StudioID uuid.UUID `db:"studio_id" json:"studio_id"`
	Url      string    `db:"url" json:"url"`
	SiteID   uuid.UUID `db:"site_id" json:"site_id"`
}

type Tag struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	Name        string        `db:"name" json:"name"`
	Description *string       `db:"description" json:"description"`
	CreatedAt   time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time     `db:"updated_at" json:"updated_at"`
	Deleted     bool          `db:"deleted" json:"deleted"`
	CategoryID  uuid.NullUUID `db:"category_id" json:"category_id"`
}

type TagAlias struct {
	TagID uuid.UUID `db:"tag_id" json:"tag_id"`
	Alias string    `db:"alias" json:"alias"`
}

type TagCategory struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Group       string    `db:"group" json:"group"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type TagEdit struct {
	EditID uuid.UUID `db:"edit_id" json:"edit_id"`
	TagID  uuid.UUID `db:"tag_id" json:"tag_id"`
}

type TagRedirect struct {
	SourceID uuid.UUID `db:"source_id" json:"source_id"`
	TargetID uuid.UUID `db:"target_id" json:"target_id"`
}

type TagSearch struct {
	TagID   uuid.UUID `db:"tag_id" json:"tag_id"`
	Name    *string   `db:"name" json:"name"`
	Aliases []string  `db:"aliases" json:"aliases"`
}

type TasteVector struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Vector    json.RawMessage    `db:"vector" json:"vector"`
	VoteCount int                `db:"vote_count" json:"vote_count"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TrustEvent struct {
	ID         int64              `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	Kind       string             `db:"kind" json:"kind"`
	EntityType *string            `db:"entity_type" json:"entity_type"`
	EntityID   uuid.NullUUID      `db:"entity_id" json:"entity_id"`
	Delta      int                `db:"delta" json:"delta"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID     `db:"id" json:"id"`
	Name         string        `db:"name" json:"name"`
	PasswordHash string        `db:"password_hash" json:"password_hash"`
	Email        string        `db:"email" json:"email"`
	ApiKey       string        `db:"api_key" json:"api_key"`
	ApiCalls     *int          `db:"api_calls" json:"api_calls"`
	LastApiCall  time.Time     `db:"last_api_call" json:"last_api_call"`
	CreatedAt    time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time     `db:"updated_at" json:"updated_at"`
	InvitedBy    uuid.NullUUID `db:"invited_by" json:"invited_by"`
	InviteTokens int           `db:"invite_tokens" json:"invite_tokens"`
}

type UserNotification struct {
	UserID uuid.UUID        `db:"user_id" json:"user_id"`
	Type   NotificationType `db:"type" json:"type"`
}

type UserRole struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Role   string    `db:"role" json:"role"`
}

type UserToken struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Data      []byte    `db:"data" json:"data"`
	Type      string    `db:"type" json:"type"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

type UserTrust struct {
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	Level                int                `db:"level" json:"level"`
	ApprovedEdits        int                `db:"approved_edits" json:"approved_edits"`
	RejectedEdits        int                `db:"rejected_edits" json:"rejected_edits"`
	IdentificationSolves int                `db:"identification_solves" json:"identification_solves"`
	QuestsCompleted      int                `db:"quests_completed" json:"quests_completed"`
	ReplicasHosted       int                `db:"replicas_hosted" json:"replicas_hosted"`
	ContentViewingOptIn  bool               `db:"content_viewing_opt_in" json:"content_viewing_opt_in"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	BonusPoints          int                `db:"bonus_points" json:"bonus_points"`
}

type WebhookDelivery struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EndpointID    uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	Payload       json.RawMessage    `db:"payload" json:"payload"`
	Attempt       int                `db:"attempt" json:"attempt"`
	NextAttemptAt time.Time          `db:"next_attempt_at" json:"next_attempt_at"`
	LastError     *string            `db:"last_error" json:"last_error"`
	DeliveredAt   pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	CreatedAt     time.Time          `db:"created_at" json:"created_at"`
}

type WebhookEndpoint struct {
	ID         uuid.UUID `db:"id" json:"id"`
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	SecretHash string    `db:"secret_hash" json:"secret_hash"`
	TargetUrl  string    `db:"target_url" json:"target_url"`
	EventTypes []string  `db:"event_types" json:"event_types"`
	Disabled   bool      `db:"disabled" json:"disabled"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}
