// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

type Querier interface {
	// Applies one event's effect to the rollup, creating the row if absent.
	//
	// The totals are incremented rather than recomputed by replaying events, so
	// recording a trust event is O(1) regardless of how much history a user has.
	// The signed delta works for both directions: a rejected edit decrements the
	// same column an approval incremented.
	//
	// ON CONFLICT (user_id) DO UPDATE is required because a user with no rollup row
	// yet (every new user) has to be created on first event.
	ApplyTrustEvent(ctx context.Context, arg ApplyTrustEventParams) (UserTrust, error)
	CancelUserEdits(ctx context.Context, userID uuid.NullUUID) error
	// Only clear once NO reject votes remain on the edit.
	//
	// A DOWNVOTE_OWN_EDIT notification is per (author, edit), not per vote, so it
	// must survive as long as ANY voter is still rejecting. Deleting it whenever
	// one voter flips to accept would silently hide a live rejection from the
	// author (issue #941 is the single-voter case; this guards the multi-voter
	// one).
	ClearDownvoteEditNotifications(ctx context.Context, id uuid.UUID) error
	ClearScenePerformerAlias(ctx context.Context, arg ClearScenePerformerAliasParams) error
	// How many votes an entity has taken part in, across both sides. Feeds the
	// leaderboard's "needs more votes" marker and any minimum-confidence filter.
	CountEloVotesForEntity(ctx context.Context, arg CountEloVotesForEntityParams) (int64, error)
	CountNotificationsByUser(ctx context.Context, arg CountNotificationsByUserParams) (int64, error)
	CountPerformerSearchMatches(ctx context.Context, arg CountPerformerSearchMatchesParams) (interface{}, error)
	CountScenesByPerformer(ctx context.Context, performerID uuid.UUID) (int64, error)
	CountScenesByPerformerIds(ctx context.Context, dollar_1 []uuid.UUID) ([]CountScenesByPerformerIdsRow, error)
	CountUnreadNotificationsByUserGroupedByType(ctx context.Context, userID uuid.UUID) ([]CountUnreadNotificationsByUserGroupedByTypeRow, error)
	CountUserEditsByStatus(ctx context.Context, userID uuid.NullUUID) ([]CountUserEditsByStatusRow, error)
	CountUserTrustEvents(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountVotesByType(ctx context.Context, userID uuid.NullUUID) ([]CountVotesByTypeRow, error)
	// Draft queries
	CreateDraft(ctx context.Context, arg CreateDraftParams) (Draft, error)
	// Edit queries
	CreateEdit(ctx context.Context, arg CreateEditParams) (Edit, error)
	// Edit comments
	CreateEditComment(ctx context.Context, arg CreateEditCommentParams) (EditComment, error)
	// Edit votes
	CreateEditVote(ctx context.Context, arg CreateEditVoteParams) error
	// Fingerprint queries (normalized schema)
	CreateFingerprint(ctx context.Context, arg CreateFingerprintParams) (Fingerprint, error)
	// Image queries
	//
	// ON CONFLICT (checksum) DO UPDATE is deliberate and is the #738 fix.
	//
	// images.checksum carries a UNIQUE index (images_checksum_idx), so two
	// submissions of the same file that interleave -- both pass the
	// FindByChecksum pre-check, both reach the insert -- previously made the
	// loser fail with a raw pq unique-violation surfaced to the user as
	// "pq: duplicate key value violates unique constraint images_checksum_idx".
	//
	// The service pre-check is not a substitute for the constraint: it is a
	// read followed by a write with no transaction between them, so it cannot
	// prevent the race. Only the database can.
	//
	// DO UPDATE rather than DO NOTHING because this query is :one and must
	// RETURNING a row. The set is a no-op (the existing row already holds these
	// values by definition of the conflict), but it lets a concurrent duplicate
	// resolve to the already-stored image instead of erroring. A draft submitted
	// with an image that another user uploaded a moment earlier should reuse that
	// image, which is exactly what the pre-check path already does.
	//
	// ON CONFLICT (checksum) does not cover the primary key: a repeated id would
	// still raise, which is correct -- that would be a bug, not a duplicate
	// upload.
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	// Invite key queries
	CreateInviteKey(ctx context.Context, arg CreateInviteKeyParams) (InviteKey, error)
	CreateModAudit(ctx context.Context, arg CreateModAuditParams) (ModAudit, error)
	CreateOrReplaceFingerprint(ctx context.Context, arg CreateOrReplaceFingerprintParams) error
	// Performer queries
	CreatePerformer(ctx context.Context, arg CreatePerformerParams) (Performer, error)
	CreatePerformerAliases(ctx context.Context, arg []CreatePerformerAliasesParams) (int64, error)
	CreatePerformerEdit(ctx context.Context, arg CreatePerformerEditParams) error
	CreatePerformerFavorite(ctx context.Context, arg CreatePerformerFavoriteParams) error
	CreatePerformerImages(ctx context.Context, arg []CreatePerformerImagesParams) (int64, error)
	CreatePerformerPiercings(ctx context.Context, arg []CreatePerformerPiercingsParams) (int64, error)
	// Performer redirects
	CreatePerformerRedirect(ctx context.Context, arg CreatePerformerRedirectParams) error
	CreatePerformerTattoos(ctx context.Context, arg []CreatePerformerTattoosParams) (int64, error)
	CreatePerformerURLs(ctx context.Context, arg []CreatePerformerURLsParams) (int64, error)
	// Scene queries
	CreateScene(ctx context.Context, arg CreateSceneParams) (Scene, error)
	CreateSceneEdit(ctx context.Context, arg CreateSceneEditParams) error
	CreateSceneFingerprints(ctx context.Context, arg []CreateSceneFingerprintsParams) (int64, error)
	CreateSceneImages(ctx context.Context, arg []CreateSceneImagesParams) (int64, error)
	// Scene performers
	CreateScenePerformers(ctx context.Context, arg []CreateScenePerformersParams) (int64, error)
	// Scene redirects
	CreateSceneRedirect(ctx context.Context, arg CreateSceneRedirectParams) error
	// Scene tags management
	CreateSceneTags(ctx context.Context, arg []CreateSceneTagsParams) (int64, error)
	// Scene URLs
	CreateSceneURLs(ctx context.Context, arg []CreateSceneURLsParams) (int64, error)
	// Site queries
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	// Site category queries
	CreateSiteCategory(ctx context.Context, arg CreateSiteCategoryParams) (SiteCategory, error)
	// Studio queries
	CreateStudio(ctx context.Context, arg CreateStudioParams) (Studio, error)
	// Studio aliases
	CreateStudioAliases(ctx context.Context, arg []CreateStudioAliasesParams) (int64, error)
	CreateStudioEdit(ctx context.Context, arg CreateStudioEditParams) error
	// Studio favorites
	CreateStudioFavorite(ctx context.Context, arg CreateStudioFavoriteParams) error
	// Studio images
	CreateStudioImages(ctx context.Context, arg []CreateStudioImagesParams) (int64, error)
	// Studio redirects
	CreateStudioRedirect(ctx context.Context, arg CreateStudioRedirectParams) error
	// Studio URLs
	CreateStudioURLs(ctx context.Context, arg []CreateStudioURLsParams) (int64, error)
	// Tag queries
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	// Tag aliases
	CreateTagAliases(ctx context.Context, arg []CreateTagAliasesParams) (int64, error)
	// Tag category queries
	CreateTagCategory(ctx context.Context, arg CreateTagCategoryParams) (TagCategory, error)
	CreateTagEdit(ctx context.Context, arg CreateTagEditParams) error
	// Tag redirects
	CreateTagRedirect(ctx context.Context, arg CreateTagRedirectParams) error
	// User queries
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// User notification subscriptions
	CreateUserNotificationSubscriptions(ctx context.Context, arg []CreateUserNotificationSubscriptionsParams) (int64, error)
	// User roles
	CreateUserRoles(ctx context.Context, arg []CreateUserRolesParams) (int64, error)
	// User token queries
	CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (UserToken, error)
	DeleteAllSceneFingerprintSubmissions(ctx context.Context, arg DeleteAllSceneFingerprintSubmissionsParams) (int64, error)
	DeleteDraft(ctx context.Context, id uuid.UUID) error
	DeleteEdit(ctx context.Context, id uuid.UUID) error
	DeleteExpiredDrafts(ctx context.Context, dollar_1 interface{}) error
	DeleteExpiredModAudits(ctx context.Context, dollar_1 interface{}) error
	DeleteExpiredUserTokens(ctx context.Context) error
	DeleteImage(ctx context.Context, id uuid.UUID) error
	DeleteInviteKey(ctx context.Context, id uuid.UUID) error
	DeleteNotificationsByEditComments(ctx context.Context, editID uuid.UUID) error
	DeleteNotificationsByTargetID(ctx context.Context, id uuid.UUID) error
	DeletePerformer(ctx context.Context, id uuid.UUID) error
	// Performer aliases
	DeletePerformerAliases(ctx context.Context, performerID uuid.UUID) error
	DeletePerformerFavorite(ctx context.Context, arg DeletePerformerFavoriteParams) error
	// Performer favorites
	DeletePerformerFavorites(ctx context.Context, performerID uuid.UUID) error
	DeletePerformerImages(ctx context.Context, performerID uuid.UUID) error
	// Performer piercings
	DeletePerformerPiercings(ctx context.Context, performerID uuid.UUID) error
	DeletePerformerScenes(ctx context.Context, performerID uuid.UUID) error
	// Performer tattoos
	DeletePerformerTattoos(ctx context.Context, performerID uuid.UUID) error
	// Performer URLs
	DeletePerformerURLs(ctx context.Context, performerID uuid.UUID) error
	DeleteScene(ctx context.Context, id uuid.UUID) error
	DeleteSceneFingerprint(ctx context.Context, arg DeleteSceneFingerprintParams) error
	DeleteSceneFingerprintsByScene(ctx context.Context, sceneID uuid.UUID) error
	// Scene images
	DeleteSceneImages(ctx context.Context, sceneID uuid.UUID) error
	DeleteScenePerformers(ctx context.Context, sceneID uuid.UUID) error
	DeleteSceneStudios(ctx context.Context, studioID uuid.NullUUID) error
	DeleteSceneTagsByScene(ctx context.Context, sceneID uuid.UUID) error
	DeleteSceneTagsByTag(ctx context.Context, tagID uuid.UUID) error
	DeleteSceneURLs(ctx context.Context, sceneID uuid.UUID) error
	DeleteSite(ctx context.Context, id uuid.UUID) error
	DeleteSiteCategory(ctx context.Context, id int) error
	DeleteStudio(ctx context.Context, id uuid.UUID) error
	DeleteStudioAliases(ctx context.Context, studioID uuid.UUID) error
	DeleteStudioFavorite(ctx context.Context, arg DeleteStudioFavoriteParams) error
	DeleteStudioFavorites(ctx context.Context, studioID uuid.UUID) error
	DeleteStudioImages(ctx context.Context, studioID uuid.UUID) error
	DeleteStudioURLs(ctx context.Context, studioID uuid.UUID) error
	DeleteTag(ctx context.Context, id uuid.UUID) error
	DeleteTagAliases(ctx context.Context, tagID uuid.UUID) error
	DeleteTagAliasesByNames(ctx context.Context, arg DeleteTagAliasesByNamesParams) error
	DeleteTagCategory(ctx context.Context, id uuid.UUID) error
	// Only used by a rebuild, so the row can be recreated from scratch rather than
	// merged. Merging a recomputed vector into an existing one would double-count
	// every feature.
	DeleteTasteVector(ctx context.Context, userID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserNotificationSubscriptions(ctx context.Context, userID uuid.UUID) error
	DeleteUserRoles(ctx context.Context, userID uuid.UUID) error
	DeleteUserToken(ctx context.Context, id uuid.UUID) error
	DestroyExpiredInvites(ctx context.Context) error
	DestroyExpiredNotifications(ctx context.Context) error
	// The pg-spgist_hamming custom-scan hook turns this UNNEST + <@ into a single
	// batch BK-tree traversal when ≤64 hashes are supplied; caller must chunk.
	// The scene_id join is intentionally NOT here: the planner overestimates the
	// customscan's row count and picks a hash-join + seq scan of scene_fingerprints.
	ExpandPhashNeighbors(ctx context.Context, arg ExpandPhashNeighborsParams) ([]ExpandPhashNeighborsRow, error)
	ExpandSceneCoMembers(ctx context.Context, sceneIds []uuid.UUID) ([]ExpandSceneCoMembersRow, error)
	FindActiveInviteKeysForUser(ctx context.Context, generatedBy uuid.UUID) ([]InviteKey, error)
	// Returns pending edits past either voting deadline, along with the tallies needed to
	// decide their outcome in Go. The `votes` column is unusable here: a net score cannot tell
	// a unanimous result apart from a contested one adding up to the same number.
	FindCompletedEdits(ctx context.Context, arg FindCompletedEditsParams) ([]FindCompletedEditsRow, error)
	FindDraft(ctx context.Context, id uuid.UUID) (Draft, error)
	FindDraftsByUser(ctx context.Context, userID uuid.UUID) ([]Draft, error)
	FindEdit(ctx context.Context, id uuid.UUID) (Edit, error)
	FindEditComment(ctx context.Context, id uuid.UUID) (EditComment, error)
	FindExistingPerformers(ctx context.Context, arg FindExistingPerformersParams) ([]Performer, error)
	FindExistingScenes(ctx context.Context, arg FindExistingScenesParams) ([]Scene, error)
	FindImage(ctx context.Context, id uuid.UUID) (Image, error)
	FindImageByChecksum(ctx context.Context, checksum string) (Image, error)
	FindImageIdsByPerformerIds(ctx context.Context, dollar_1 []uuid.UUID) ([]PerformerImage, error)
	FindImageIdsBySceneIds(ctx context.Context, dollar_1 []uuid.UUID) ([]SceneImage, error)
	FindImageIdsByStudioIds(ctx context.Context, dollar_1 []uuid.UUID) ([]StudioImage, error)
	FindImagesByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Image, error)
	FindImagesBySceneID(ctx context.Context, id uuid.UUID) ([]Image, error)
	FindImagesByStudioID(ctx context.Context, id uuid.UUID) ([]Image, error)
	FindInviteKey(ctx context.Context, id uuid.UUID) (InviteKey, error)
	// Find merge target IDs for performers (for merges where these are sources)
	FindMergeIDsByPerformerIds(ctx context.Context, performerIds []uuid.UUID) ([]FindMergeIDsByPerformerIdsRow, error)
	// Find merge source IDs for performers (for merges where these are targets)
	FindMergeIDsBySourcePerformerIds(ctx context.Context, performerIds []uuid.UUID) ([]FindMergeIDsBySourcePerformerIdsRow, error)
	// Notification queries
	FindNotificationsByUser(ctx context.Context, arg FindNotificationsByUserParams) ([]Notification, error)
	FindPendingPerformerCreation(ctx context.Context, arg FindPendingPerformerCreationParams) ([]Edit, error)
	FindPendingSceneCreation(ctx context.Context, arg FindPendingSceneCreationParams) ([]Edit, error)
	FindPerformer(ctx context.Context, id uuid.UUID) (Performer, error)
	// Get aliases for multiple performers
	FindPerformerAliasesByIds(ctx context.Context, performerIds []uuid.UUID) ([]PerformerAlias, error)
	FindPerformerByAlias(ctx context.Context, upper interface{}) (Performer, error)
	FindPerformerByName(ctx context.Context, upper interface{}) (Performer, error)
	// Check favorite status for multiple performers for a specific user
	FindPerformerFavoritesByIds(ctx context.Context, arg FindPerformerFavoritesByIdsParams) ([]FindPerformerFavoritesByIdsRow, error)
	// Get piercings for multiple performers
	FindPerformerPiercingsByIds(ctx context.Context, performerIds []uuid.UUID) ([]PerformerPiercing, error)
	// Get tattoos for multiple performers
	FindPerformerTattoosByIds(ctx context.Context, performerIds []uuid.UUID) ([]PerformerTattoo, error)
	// Get URLs for multiple performers
	FindPerformerUrlsByIds(ctx context.Context, performerIds []uuid.UUID) ([]PerformerUrl, error)
	FindPerformerWithRedirect(ctx context.Context, id uuid.UUID) ([]Performer, error)
	FindPerformersByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Performer, error)
	FindPerformersByURL(ctx context.Context, arg FindPerformersByURLParams) ([]Performer, error)
	FindScene(ctx context.Context, id uuid.UUID) (Scene, error)
	// Get performer appearances for multiple scenes
	FindSceneAppearancesByIds(ctx context.Context, sceneIds []uuid.UUID) ([]FindSceneAppearancesByIdsRow, error)
	FindSceneByURL(ctx context.Context, arg FindSceneByURLParams) ([]Scene, error)
	// Get URLs for multiple scenes
	FindSceneUrlsByIds(ctx context.Context, sceneIds []uuid.UUID) ([]SceneUrl, error)
	FindScenesByFingerprintsExactWithHash(ctx context.Context, hashes []int64) ([]FindScenesByFingerprintsExactWithHashRow, error)
	// Scene fingerprints (use fingerprint.sql for most fingerprint operations)
	FindScenesByFullFingerprintsWithHash(ctx context.Context, arg FindScenesByFullFingerprintsWithHashParams) ([]FindScenesByFullFingerprintsWithHashRow, error)
	FindSiteCategory(ctx context.Context, id int) (SiteCategory, error)
	FindSitesByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Site, error)
	FindStudio(ctx context.Context, id uuid.UUID) (Studio, error)
	// Get aliases for multiple studios
	FindStudioAliasesByIds(ctx context.Context, studioIds []uuid.UUID) ([]StudioAlias, error)
	FindStudioByAlias(ctx context.Context, upper interface{}) (Studio, error)
	FindStudioByName(ctx context.Context, upper interface{}) (Studio, error)
	// Check favorite status for multiple studios for a specific user
	FindStudioFavoritesByIds(ctx context.Context, arg FindStudioFavoritesByIdsParams) ([]FindStudioFavoritesByIdsRow, error)
	// Get URLs for multiple studios
	FindStudioUrlsByIds(ctx context.Context, studioIds []uuid.UUID) ([]StudioUrl, error)
	FindStudioWithRedirect(ctx context.Context, id uuid.UUID) (Studio, error)
	FindTag(ctx context.Context, id uuid.UUID) (Tag, error)
	// Get aliases for multiple tags
	FindTagAliasesByIds(ctx context.Context, tagIds []uuid.UUID) ([]TagAlias, error)
	FindTagByAlias(ctx context.Context, upper interface{}) (Tag, error)
	FindTagByName(ctx context.Context, upper interface{}) (Tag, error)
	FindTagByNameOrAlias(ctx context.Context, lower string) (Tag, error)
	FindTagCategory(ctx context.Context, id uuid.UUID) (TagCategory, error)
	// Bulk query to find tag IDs for multiple scene IDs
	FindTagIdsBySceneIds(ctx context.Context, sceneIds []uuid.UUID) ([]SceneTag, error)
	FindTagWithRedirect(ctx context.Context, id uuid.UUID) ([]Tag, error)
	FindTagsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Tag, error)
	FindTagsBySceneID(ctx context.Context, sceneID uuid.UUID) ([]Tag, error)
	FindUnreadNotificationsByUser(ctx context.Context, arg FindUnreadNotificationsByUserParams) ([]Notification, error)
	FindUnusedImages(ctx context.Context) ([]Image, error)
	FindUser(ctx context.Context, id uuid.UUID) (User, error)
	FindUserByEmail(ctx context.Context, upper interface{}) (User, error)
	FindUserByName(ctx context.Context, name string) (User, error)
	FindUserToken(ctx context.Context, id uuid.UUID) (UserToken, error)
	FindUserTokensByEmail(ctx context.Context, dollar_1 string) ([]UserToken, error)
	FindUserTokensByInviteKey(ctx context.Context, dollar_1 uuid.UUID) ([]UserToken, error)
	FindUserWithRoles(ctx context.Context, id uuid.UUID) (FindUserWithRolesRow, error)
	// Get all fingerprints for multiple scenes with aggregated vote data
	// When onlySubmitted is true, pass the actual user ID, when false pass NULL
	GetAllFingerprints(ctx context.Context, arg GetAllFingerprintsParams) ([]GetAllFingerprintsRow, error)
	GetAllSceneFingerprints(ctx context.Context, sceneID uuid.UUID) ([]GetAllSceneFingerprintsRow, error)
	GetAllSiteCategories(ctx context.Context) ([]SiteCategory, error)
	GetAllTagCategories(ctx context.Context) ([]TagCategory, error)
	// Every rollup row. Used when a threshold changes and every level must be
	// recomputed (see RebuildLevels in internal/service/trust).
	GetAllUserTrust(ctx context.Context) ([]UserTrust, error)
	GetChildStudios(ctx context.Context, parentStudioID uuid.NullUUID) ([]Studio, error)
	GetEditComments(ctx context.Context, editID uuid.UUID) ([]EditComment, error)
	GetEditCommentsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]EditComment, error)
	GetEditPerformerAliases(ctx context.Context, id uuid.UUID) ([]string, error)
	GetEditPerformerPiercings(ctx context.Context, id uuid.UUID) ([]GetEditPerformerPiercingsRow, error)
	GetEditPerformerTattoos(ctx context.Context, id uuid.UUID) ([]GetEditPerformerTattoosRow, error)
	GetEditTargetID(ctx context.Context, id uuid.UUID) (GetEditTargetIDRow, error)
	GetEditVotes(ctx context.Context, editID uuid.UUID) ([]EditVote, error)
	GetEditVotesByEditIDs(ctx context.Context, editIds []uuid.UUID) ([]EditVote, error)
	GetEditsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Edit, error)
	GetEditsByPerformer(ctx context.Context, performerID uuid.UUID) ([]Edit, error)
	// Get edits for multiple scenes
	GetEditsBySceneIds(ctx context.Context, sceneIds []uuid.UUID) ([]GetEditsBySceneIdsRow, error)
	GetEditsByStudio(ctx context.Context, studioID uuid.UUID) ([]Edit, error)
	GetEditsByTag(ctx context.Context, tagID uuid.UUID) ([]Edit, error)
	// Elo / Glicko-2 queries (SPEC §9, migration 77).
	//
	// elo_votes is the source of truth and is append-only; elo_ratings is a cache
	// with a defined rebuild path. These queries are the only places allowed to
	// write either table, for the same reason trust.sql owns trust_events and
	// user_trust.
	GetEloRating(ctx context.Context, arg GetEloRatingParams) (EloRating, error)
	// Takes a type plus a batch of ids, because ranking reads are always
	// per-entity-kind ("the ratings for these 50 performers"), never across kinds.
	GetEloRatingsByIDs(ctx context.Context, arg GetEloRatingsByIDsParams) ([]EloRating, error)
	// The user's own votes, newest first. Backs the taste vector (SPEC §2) and the
	// voting-consistency signal in SPEC §6.
	//
	// Ordered by created_at so a rebuild is deterministic: two rebuilds of the same
	// vote set must produce the same vector, and an unordered scan would let
	// floating-point rounding differ between runs.
	GetEloVotesForUser(ctx context.Context, userID uuid.UUID) ([]EloVote, error)
	GetFingerprint(ctx context.Context, arg GetFingerprintParams) (Fingerprint, error)
	// Gets current images for target entity and merges with edit's added_images/removed_images
	GetImagesForEdit(ctx context.Context, id uuid.UUID) ([]Image, error)
	// Gets current performers for target entity and merges with edit's added_performers/removed_performers
	GetMergedPerformersForEdit(ctx context.Context, id uuid.UUID) ([]GetMergedPerformersForEditRow, error)
	// Gets current aliases for target studio entity and merges with edit's added_aliases/removed_aliases
	GetMergedStudioAliasesForEdit(ctx context.Context, id uuid.UUID) ([]string, error)
	// Gets current aliases for target tag entity and merges with edit's added_aliases/removed_aliases
	GetMergedTagAliasesForEdit(ctx context.Context, id uuid.UUID) ([]string, error)
	// Gets current tags for target entity and merges with edit's added_tags/removed_tags
	GetMergedTagsForEdit(ctx context.Context, id uuid.UUID) ([]Tag, error)
	// URL merging queries for edits
	// Drop any URL whose site no longer exists.
	//
	// This is the #621 fix. current_urls is safe already: scene_urls/performer_urls/
	// studio_urls carry a foreign key to sites, so deleting a site cascades the
	// join rows away. But added_urls is read straight out of the edit's JSON
	// payload, which is not a foreign key and is not cascaded -- a site deleted
	// after the edit was filed left a dangling site_id behind.
	//
	// The dangling id then reached URL.site, which the schema declares non-null
	// (`site: Site!`), so the dataloader's nil became a GraphQL null-in-non-null
	// error and the whole /edits page failed to render -- one bad row taking out
	// every edit on the page. URL.type additionally dereferenced the nil site
	// without a check.
	//
	// Filtering here rather than relaxing the schema to `site: Site` is
	// deliberate: the frontend's URLFragment requires site { id name icon
	// category { ... } } to render a row at all, so a null site would not fix the
	// page, it would trade a loud failure for blank or broken rows. A URL whose
	// site is gone has no site to render, so it does not belong in the list.
	// result: URL
	// Gets current URLs for target entity and merges with edit's added_urls/removed_urls
	GetMergedURLsForEdit(ctx context.Context, id uuid.UUID) ([]GetMergedURLsForEditRow, error)
	GetModAuditCount(ctx context.Context, arg GetModAuditCountParams) (int64, error)
	GetPerformerAliases(ctx context.Context, performerID uuid.UUID) ([]string, error)
	// Performer images
	GetPerformerImages(ctx context.Context, performerID uuid.UUID) ([]Image, error)
	GetPerformerPiercings(ctx context.Context, performerID uuid.UUID) ([]GetPerformerPiercingsRow, error)
	GetPerformerSearchFacets(ctx context.Context, arg GetPerformerSearchFacetsParams) (interface{}, error)
	GetPerformerTattoos(ctx context.Context, performerID uuid.UUID) ([]GetPerformerTattoosRow, error)
	GetPerformerURLs(ctx context.Context, performerID uuid.UUID) ([]GetPerformerURLsRow, error)
	GetPrimaryEditCommentID(ctx context.Context, editID uuid.UUID) (uuid.UUID, error)
	GetSceneFingerprintScenes(ctx context.Context, fingerprintIds []int) ([]GetSceneFingerprintScenesRow, error)
	GetScenePerformers(ctx context.Context, sceneID uuid.UUID) ([]GetScenePerformersRow, error)
	GetScenePhashSeeds(ctx context.Context, sceneID uuid.UUID) ([]GetScenePhashSeedsRow, error)
	GetSceneTags(ctx context.Context, sceneID uuid.UUID) ([]Tag, error)
	GetSceneURLs(ctx context.Context, sceneID uuid.UUID) ([]GetSceneURLsRow, error)
	GetScenes(ctx context.Context, dollar_1 []uuid.UUID) ([]Scene, error)
	GetSite(ctx context.Context, id uuid.UUID) (Site, error)
	GetSiteCategoriesByIds(ctx context.Context, dollar_1 []int) ([]SiteCategory, error)
	GetStudioAliases(ctx context.Context, studioID uuid.UUID) ([]string, error)
	GetStudioImages(ctx context.Context, studioID uuid.UUID) ([]uuid.UUID, error)
	GetStudioURLs(ctx context.Context, studioID uuid.UUID) ([]StudioUrl, error)
	GetStudios(ctx context.Context, dollar_1 []uuid.UUID) ([]Studio, error)
	GetStudiosByPerformer(ctx context.Context, performerID uuid.UUID) ([]GetStudiosByPerformerRow, error)
	// Get studios where performer has scenes, filtered to a studio network (the studio, its parent, and children)
	GetStudiosByPerformerAndNetwork(ctx context.Context, arg GetStudiosByPerformerAndNetworkParams) ([]GetStudiosByPerformerAndNetworkRow, error)
	GetTagAliases(ctx context.Context, tagID uuid.UUID) ([]string, error)
	GetTagCategoriesByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]TagCategory, error)
	GetTasteVector(ctx context.Context, userID uuid.UUID) (TasteVector, error)
	GetUserNotificationSubscriptions(ctx context.Context, userID uuid.UUID) ([]NotificationType, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error)
	GetUserRolesByUserIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]UserRole, error)
	// Trust level queries (SPEC §6, migration 76).
	//
	// trust_events is the source of truth; user_trust is a denormalised rollup of
	// it. These queries keep the rollup in step with the events, and the two
	// upserts below are the only places in the codebase allowed to write either
	// table.
	GetUserTrust(ctx context.Context, userID uuid.UUID) (UserTrust, error)
	GetUserTrustByUserIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]UserTrust, error)
	GetUsers(ctx context.Context, dollar_1 []uuid.UUID) ([]User, error)
	InviteKeyUsed(ctx context.Context, id uuid.UUID) (*int, error)
	IsImageUnused(ctx context.Context, id uuid.UUID) (bool, error)
	// Over-fetches relative to the requested limit: the service re-sorts by
	// Rankable (rating, then vote count, then deviation) rather than by rating
	// alone, so a plain top-N-by-rating is not the top-N-by-Rankable. Over-fetching
	// by 4x inside the service covers that without teaching the query about the
	// tie-breaking rules.
	//
	// NULLS LAST matters: a rating row can exist with no votes if an entity was
	// seeded by the migration and never voted on, and in Postgres ASC puts NULLs
	// LAST by default but the explicit form documents that the ordering is
	// deliberate.
	ListEloRatings(ctx context.Context, arg ListEloRatingsParams) ([]EloRating, error)
	// One user's history, newest first. Used by the audit view and by tests that
	// assert the event log is the source of truth.
	ListUserTrustEvents(ctx context.Context, userID uuid.UUID) ([]TrustEvent, error)
	LoadClusterSubmissions(ctx context.Context, fingerprintIds []int) ([]LoadClusterSubmissionsRow, error)
	LoadLinkedOshashSubmissions(ctx context.Context, phashFingerprintIds []int) ([]LoadLinkedOshashSubmissionsRow, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	MoveSceneFingerprintSubmissions(ctx context.Context, arg MoveSceneFingerprintSubmissionsParams) ([]uuid.UUID, error)
	// Prepare a fingerprint move by dropping reports and dupe fingerprint submissions
	PruneSceneFingerprintsForMove(ctx context.Context, arg PruneSceneFingerprintsForMoveParams) ([]PruneSceneFingerprintsForMoveRow, error)
	QueryModAudits(ctx context.Context, arg QueryModAuditsParams) ([]ModAudit, error)
	ReassignPerformerAliases(ctx context.Context, arg ReassignPerformerAliasesParams) error
	ReassignPerformerFavorites(ctx context.Context, arg ReassignPerformerFavoritesParams) error
	ReassignStudioFavorites(ctx context.Context, arg ReassignStudioFavoritesParams) error
	// Reassign to the sentinel user only the deleted user's scene fingerprints that are unique
	ReassignUniqueSceneFingerprints(ctx context.Context, arg ReassignUniqueSceneFingerprintsParams) error
	// Rebuilds the totals from the event log.
	//
	// This is the recovery path, and the reason trust_events is append-only: if the
	// rollup ever drifts -- a threshold change, a bug in ApplyTrustEvent, a manual
	// database edit -- the truth is still replayable. Coalescing SUMs the signed
	// deltas per kind in one pass rather than replaying row by row.
	// No GROUP BY: an aggregate over an empty set still returns exactly one row,
	// with the COALESCE defaults above. GROUP BY made this return NOTHING for a
	// user with no events, which made it unusable for creating a zeroed rollup --
	// and that is exactly what SetContentViewingOptIn needs to do for a user
	// opting in before they are eligible.
	RecomputeUserTrustTotals(ctx context.Context, userID uuid.UUID) (UserTrust, error)
	// No ON CONFLICT: elo_votes has no natural key beyond its own id, and a
	// duplicate matchup is a legitimate thing for a user to do (they may change
	// their mind about the same pair). Deduplicating identical votes would discard
	// that signal, and the "don't double count" property comes from Glicko being
	// applied to the rating, not from refusing to store the vote.
	//
	// Returning the row lets the service report the resulting rating to the voter
	// without a second round trip.
	RecordEloVote(ctx context.Context, arg RecordEloVoteParams) (EloVote, error)
	// ON CONFLICT DO NOTHING makes a retried or duplicated event a no-op rather
	// than a silent double increment. The matching partial state is a real
	// concern: an edit can be applied twice by a retried request, and without this
	// the contributor's trust would grow twice for one contribution.
	//
	// Returning the row means a duplicate insert reports no rows, which the
	// service treats as "already recorded" rather than as an error.
	RecordTrustEvent(ctx context.Context, arg RecordTrustEventParams) (TrustEvent, error)
	ResetVotes(ctx context.Context, editID uuid.UUID) error
	// Resolves a set of UUIDs to the type of entity they belong to, used to turn
	// bare UUIDs in comments into links.
	ResolveEntityTypes(ctx context.Context, ids []uuid.UUID) ([]ResolveEntityTypesRow, error)
	// Keep the WHERE clause in sync across SearchPerformers, CountPerformerSearchMatches,
	// and GetPerformerSearchFacets so paging, counts, and facets stay consistent.
	SearchPerformers(ctx context.Context, arg SearchPerformersParams) ([]uuid.UUID, error)
	// Token-at-a-time scoring. The search term is tokenized by the caller and
	// passed as an array. Each token is scored independently against every field
	// via disjunction_max, so a token that hits several fields (e.g. a studio named
	// after its performer) only contributes from its single best field instead of
	// summing across them.
	//
	// Score = coverage tier + relevance tiebreak:
	//   * coverage: each distinct token that matches anywhere adds a flat 10000, so
	//     a scene matching more of the query always outranks one matching fewer,
	//     regardless of BM25/IDF weighting (stops a single rare token outscoring
	//     several common ones).
	//   * relevance: ordinary BM25 (performer-weighted) breaks ties within a tier.
	// The 10000 constant must exceed the max achievable BM25 sum; search terms are
	// short so the relevance total stays well under it.
	SearchScenes(ctx context.Context, arg SearchScenesParams) ([]SearchScenesRow, error)
	SearchStudios(ctx context.Context, arg SearchStudiosParams) ([]SearchStudiosRow, error)
	SearchTags(ctx context.Context, arg SearchTagsParams) ([]Tag, error)
	// The one user-writable field in this table (SPEC §6: high-trust users
	// EXPLICITLY opt in to viewing content).
	//
	// It is deliberately NOT gated on level here. Eligibility (level >= 4) is
	// derived at read time by the service, because a stored eligibility would go
	// stale the moment a threshold changed; a stored opt-in is just the user's
	// own choice and is safe to keep.
	SetContentViewingOptIn(ctx context.Context, arg SetContentViewingOptInParams) (UserTrust, error)
	SetEditCommentHidden(ctx context.Context, arg SetEditCommentHiddenParams) (EditComment, error)
	SetScenePerformerAlias(ctx context.Context, arg SetScenePerformerAliasParams) error
	// The level is written by the service after deriving it from the thresholds,
	// never by the database. The curve is a product decision and belongs in Go,
	// where it can be changed without a migration.
	SetUserTrustLevel(ctx context.Context, arg SetUserTrustLevelParams) (UserTrust, error)
	SoftDeletePerformer(ctx context.Context, id uuid.UUID) (Performer, error)
	SoftDeleteScene(ctx context.Context, id uuid.UUID) (Scene, error)
	SoftDeleteStudio(ctx context.Context, id uuid.UUID) (Studio, error)
	SoftDeleteTag(ctx context.Context, id uuid.UUID) (Tag, error)
	SubmittedHashExists(ctx context.Context, arg SubmittedHashExistsParams) (bool, error)
	TriggerDownvoteEditNotifications(ctx context.Context, id uuid.UUID) error
	TriggerEditCommentNotifications(ctx context.Context, id uuid.UUID) error
	TriggerFailedEditNotifications(ctx context.Context, id uuid.UUID) error
	TriggerFingerprintMovedNotifications(ctx context.Context, arg TriggerFingerprintMovedNotificationsParams) error
	TriggerPerformerEditNotifications(ctx context.Context, id uuid.UUID) error
	TriggerSceneCreationNotifications(ctx context.Context, id uuid.UUID) error
	//
	// One notification row per (user, type), NOT one per user.
	//
	// Each arm below is an independent reason this user should hear about this
	// edit, and the reader filters on the stored type
	// (FindNotificationsByUser: type = $n). Collapsing to a single row per user
	// with DISTINCT ON (user_id) therefore did not just pick a type, it DELETED
	// the others: a user who both favorited the scene's performer and had
	// submitted a fingerprint for the scene kept only whichever arm came first
	// out of an unordered set, so filtering by FINGERPRINTED_SCENE_EDIT returned
	// nothing (#1060).
	//
	// The arm without an ORDER BY made it worse -- which arm won was undefined,
	// so the bug appeared and disappeared with the query plan.
	//
	// DISTINCT ON (user_id, type) still collapses a user who qualifies twice for
	// the same type, which is the dedup that was actually wanted.
	TriggerSceneEditNotifications(ctx context.Context, id uuid.UUID) error
	TriggerStudioEditNotifications(ctx context.Context, id uuid.UUID) error
	TriggerUpdatedEditNotifications(ctx context.Context, id uuid.UUID) error
	UpdateEdit(ctx context.Context, arg UpdateEditParams) (Edit, error)
	UpdateEditCommentText(ctx context.Context, arg UpdateEditCommentTextParams) (EditComment, error)
	UpdateEditData(ctx context.Context, arg UpdateEditDataParams) (Edit, error)
	// Retarget PENDING performer edits from a merged-away performer to the merge survivor.
	//
	// Issue #943: a merge soft-deletes the source and adds a redirect, but edits still
	// pointing at the source are left addressing a deleted entity. They can never be
	// applied and never show up under the surviving performer's edit list.
	//
	// The target lives in performer_edits, not on edits, so this rewrites the join row.
	// Only PENDING is touched: an edit that already reached ACCEPTED/REJECTED has a
	// verdict whose meaning must not change under the author or voters, and rewriting
	// it would silently re-attribute history.
	//
	// Returns the number of rows retargeted so callers can log the effect.
	UpdatePendingPerformerEditsTarget(ctx context.Context, arg UpdatePendingPerformerEditsTargetParams) (int64, error)
	UpdatePendingSceneEditsTarget(ctx context.Context, arg UpdatePendingSceneEditsTargetParams) (int64, error)
	UpdatePendingStudioEditsTarget(ctx context.Context, arg UpdatePendingStudioEditsTargetParams) (int64, error)
	UpdatePendingTagEditsTarget(ctx context.Context, arg UpdatePendingTagEditsTargetParams) (int64, error)
	UpdatePerformer(ctx context.Context, arg UpdatePerformerParams) (Performer, error)
	UpdatePerformerRedirects(ctx context.Context, arg UpdatePerformerRedirectsParams) error
	UpdateScene(ctx context.Context, arg UpdateSceneParams) (Scene, error)
	UpdateSceneRedirects(ctx context.Context, arg UpdateSceneRedirectsParams) error
	UpdateSceneStudios(ctx context.Context, arg UpdateSceneStudiosParams) error
	UpdateSceneTagsForMerge(ctx context.Context, arg UpdateSceneTagsForMergeParams) error
	UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error)
	UpdateSiteCategory(ctx context.Context, arg UpdateSiteCategoryParams) (SiteCategory, error)
	UpdateStudio(ctx context.Context, arg UpdateStudioParams) (Studio, error)
	UpdateStudioRedirects(ctx context.Context, arg UpdateStudioRedirectsParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateTagCategory(ctx context.Context, arg UpdateTagCategoryParams) (TagCategory, error)
	UpdateTagRedirects(ctx context.Context, arg UpdateTagRedirectsParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAPIKey(ctx context.Context, arg UpdateUserAPIKeyParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserInviteTokenCount(ctx context.Context, arg UpdateUserInviteTokenCountParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Creates the row on first use, which is what makes a performer created AFTER
	// the migration work without a separate backfill: the seeding INSERT covers
	// performers that predate it, and this covers everyone after.
	//
	// last_rated_at is set on update as well as insert, so a rating that is
	// re-asserted with unchanged numbers still counts as "rated now" for the Glicko
	// time constant.
	// volatility is written, not just defaulted. Glickman's sigma is persistent
	// state: Step 5 of the paper reads the PREVIOUS value to bound how far sigma may
	// move this period. Omitting it here would silently reset every rating to 0.06
	// on every vote, which is the one thing the column exists to prevent.
	UpsertEloRating(ctx context.Context, arg UpsertEloRatingParams) (EloRating, error)
	UpsertTasteVector(ctx context.Context, arg UpsertTasteVectorParams) (TasteVector, error)
}

var _ Querier = (*Queries)(nil)
