// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scene.sql

package queries

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const countSceneSearchDrift = `-- name: CountSceneSearchDrift :one
SELECT
    (SELECT COUNT(*) FROM scenes WHERE deleted = false) AS scene_count,
    (SELECT COUNT(*) FROM scene_search)               AS indexed_count,
    COALESCE((
        SELECT ARRAY_AGG(S.id)
        FROM scenes S
        WHERE S.deleted = false
          AND NOT EXISTS (
              SELECT 1 FROM scene_search SS WHERE SS.scene_id = S.id
          )
    ), '{}'::UUID[])::UUID[] AS missing_ids
`

type CountSceneSearchDriftRow struct {
	SceneCount   int64       `db:"scene_count" json:"scene_count"`
	IndexedCount int64       `db:"indexed_count" json:"indexed_count"`
	MissingIds   []uuid.UUID `db:"missing_ids" json:"missing_ids"`
}

// SPEC §7.25.2. scene_search is maintained entirely by triggers, and a scene
// whose trigger did not fire is invisible to every search permanently -- the
// same class of fault as §7.24.1's verified-unknown markers, where absence
// could not be distinguished from empty.
//
// Two numbers and a list, because they answer different questions. The counts
// answer "is anything wrong"; the ids answer "what". scene_search has a PRIMARY
// KEY on scene_id and one row per scene, so equal counts imply equal sets -- but
// returning the ids anyway means a diagnosis does not require a second query
// somebody forgets to write when the alarm first goes off.
//
// NOT EXISTS, and not a LEFT JOIN ... IS NULL, because the join version has to
// re-state the join condition and the two can disagree.
//
// The CAST has to go on the OUTSIDE of COALESCE, and that is the whole trick.
// `COALESCE(ARRAY_AGG(S.id)::UUID[], '{}'::UUID[])` still infers text[] inside
// COALESCE and emits `MissingIds interface{}`; wrapping the whole expression
// `COALESCE(...)::UUID[]` is what resolves it to []uuid.UUID. Measured with a
// throwaway probe query rather than assumed -- fingerprint.sql:157 casts its
// own aggregate but has no COALESCE, which is why its cast works and this one
// needed two attempts.
//
// The consequence of getting it wrong is a type assertion in whichever caller
// reads the row, so it is a runtime failure somewhere else rather than a compile
// error here.
func (q *Queries) CountSceneSearchDrift(ctx context.Context) (CountSceneSearchDriftRow, error) {
	row := q.db.QueryRow(ctx, countSceneSearchDrift)
	var i CountSceneSearchDriftRow
	err := row.Scan(&i.SceneCount, &i.IndexedCount, &i.MissingIds)
	return i, err
}

const countScenesByPerformer = `-- name: CountScenesByPerformer :one
SELECT COUNT(*) FROM scene_performers WHERE performer_id = $1
`

func (q *Queries) CountScenesByPerformer(ctx context.Context, performerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countScenesByPerformer, performerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScenesByPerformerIds = `-- name: CountScenesByPerformerIds :many
SELECT performer_id, COUNT(*) AS scene_count
FROM scene_performers
WHERE performer_id = ANY($1::UUID[])
GROUP BY performer_id
`

type CountScenesByPerformerIdsRow struct {
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	SceneCount  int64     `db:"scene_count" json:"scene_count"`
}

func (q *Queries) CountScenesByPerformerIds(ctx context.Context, dollar_1 []uuid.UUID) ([]CountScenesByPerformerIdsRow, error) {
	rows, err := q.db.Query(ctx, countScenesByPerformerIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountScenesByPerformerIdsRow{}
	for rows.Next() {
		var i CountScenesByPerformerIdsRow
		if err := rows.Scan(&i.PerformerID, &i.SceneCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createScene = `-- name: CreateScene :one

INSERT INTO scenes (id, title, details, date, production_date, studio_id, duration, director, code, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now())
RETURNING id, title, details, studio_id, created_at, updated_at, duration, director, deleted, code, date, production_date
`

type CreateSceneParams struct {
	ID             uuid.UUID     `db:"id" json:"id"`
	Title          *string       `db:"title" json:"title"`
	Details        *string       `db:"details" json:"details"`
	Date           *string       `db:"date" json:"date"`
	ProductionDate *string       `db:"production_date" json:"production_date"`
	StudioID       uuid.NullUUID `db:"studio_id" json:"studio_id"`
	Duration       *int          `db:"duration" json:"duration"`
	Director       *string       `db:"director" json:"director"`
	Code           *string       `db:"code" json:"code"`
}

// Scene queries
func (q *Queries) CreateScene(ctx context.Context, arg CreateSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, createScene,
		arg.ID,
		arg.Title,
		arg.Details,
		arg.Date,
		arg.ProductionDate,
		arg.StudioID,
		arg.Duration,
		arg.Director,
		arg.Code,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Details,
		&i.StudioID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Director,
		&i.Deleted,
		&i.Code,
		&i.Date,
		&i.ProductionDate,
	)
	return i, err
}

type CreateSceneImagesParams struct {
	SceneID uuid.UUID `db:"scene_id" json:"scene_id"`
	ImageID uuid.UUID `db:"image_id" json:"image_id"`
}

type CreateScenePerformersParams struct {
	SceneID     uuid.UUID `db:"scene_id" json:"scene_id"`
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	As          *string   `db:"as" json:"as"`
}

const createSceneRedirect = `-- name: CreateSceneRedirect :exec

INSERT INTO scene_redirects (source_id, target_id) VALUES ($1, $2)
`

type CreateSceneRedirectParams struct {
	SourceID uuid.UUID `db:"source_id" json:"source_id"`
	TargetID uuid.UUID `db:"target_id" json:"target_id"`
}

// Scene redirects
func (q *Queries) CreateSceneRedirect(ctx context.Context, arg CreateSceneRedirectParams) error {
	_, err := q.db.Exec(ctx, createSceneRedirect, arg.SourceID, arg.TargetID)
	return err
}

type CreateSceneURLsParams struct {
	SceneID uuid.UUID `db:"scene_id" json:"scene_id"`
	Url     string    `db:"url" json:"url"`
	SiteID  uuid.UUID `db:"site_id" json:"site_id"`
}

const deleteScene = `-- name: DeleteScene :exec
DELETE FROM scenes WHERE id = $1
`

func (q *Queries) DeleteScene(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScene, id)
	return err
}

const deleteSceneImages = `-- name: DeleteSceneImages :exec

DELETE FROM scene_images WHERE scene_id = $1
`

// Scene images
func (q *Queries) DeleteSceneImages(ctx context.Context, sceneID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSceneImages, sceneID)
	return err
}

const deleteScenePerformers = `-- name: DeleteScenePerformers :exec
DELETE FROM scene_performers WHERE scene_id = $1
`

func (q *Queries) DeleteScenePerformers(ctx context.Context, sceneID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScenePerformers, sceneID)
	return err
}

const deleteSceneStudios = `-- name: DeleteSceneStudios :exec
UPDATE scenes SET studio_id = NULL WHERE studio_id = $1
`

func (q *Queries) DeleteSceneStudios(ctx context.Context, studioID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteSceneStudios, studioID)
	return err
}

const deleteSceneURLs = `-- name: DeleteSceneURLs :exec
DELETE FROM scene_urls WHERE scene_id = $1
`

func (q *Queries) DeleteSceneURLs(ctx context.Context, sceneID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSceneURLs, sceneID)
	return err
}

const findExistingScenes = `-- name: FindExistingScenes :many
SELECT id, title, details, studio_id, created_at, updated_at, duration, director, deleted, code, date, production_date FROM scenes WHERE (
    ($1::text IS NOT NULL AND $2::uuid IS NOT NULL
     AND TRIM(LOWER(title)) = TRIM(LOWER($1))
     AND studio_id = $2)
    OR
    ($3::BIGINT[] IS NOT NULL AND array_length($3::BIGINT[], 1) > 0
     AND id IN (
        SELECT scene_id
        FROM scene_fingerprints SFP
        JOIN fingerprints FP ON SFP.fingerprint_id = FP.id
        WHERE FP.hash = ANY($3::BIGINT[])
        GROUP BY scene_id
    ))
)
AND deleted = FALSE
`

type FindExistingScenesParams struct {
	Title    *string       `db:"title" json:"title"`
	StudioID uuid.NullUUID `db:"studio_id" json:"studio_id"`
	Hashes   []int64       `db:"hashes" json:"hashes"`
}

func (q *Queries) FindExistingScenes(ctx context.Context, arg FindExistingScenesParams) ([]Scene, error) {
	rows, err := q.db.Query(ctx, findExistingScenes, arg.Title, arg.StudioID, arg.Hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scene{}
	for rows.Next() {
		var i Scene
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Details,
			&i.StudioID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.Director,
			&i.Deleted,
			&i.Code,
			&i.Date,
			&i.ProductionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findScene = `-- name: FindScene :one
SELECT id, title, details, studio_id, created_at, updated_at, duration, director, deleted, code, date, production_date FROM scenes WHERE id = $1
`

func (q *Queries) FindScene(ctx context.Context, id uuid.UUID) (Scene, error) {
	row := q.db.QueryRow(ctx, findScene, id)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Details,
		&i.StudioID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Director,
		&i.Deleted,
		&i.Code,
		&i.Date,
		&i.ProductionDate,
	)
	return i, err
}

const findSceneAppearancesByIds = `-- name: FindSceneAppearancesByIds :many
SELECT scene_id, performer_id, "as" FROM scene_performers WHERE scene_id = ANY($1::UUID[])
`

type FindSceneAppearancesByIdsRow struct {
	SceneID     uuid.UUID `db:"scene_id" json:"scene_id"`
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	As          *string   `db:"as" json:"as"`
}

// Get performer appearances for multiple scenes
func (q *Queries) FindSceneAppearancesByIds(ctx context.Context, sceneIds []uuid.UUID) ([]FindSceneAppearancesByIdsRow, error) {
	rows, err := q.db.Query(ctx, findSceneAppearancesByIds, sceneIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSceneAppearancesByIdsRow{}
	for rows.Next() {
		var i FindSceneAppearancesByIdsRow
		if err := rows.Scan(&i.SceneID, &i.PerformerID, &i.As); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSceneByURL = `-- name: FindSceneByURL :many
SELECT s.id, s.title, s.details, s.studio_id, s.created_at, s.updated_at, s.duration, s.director, s.deleted, s.code, s.date, s.production_date
FROM scenes S
JOIN scene_urls SU ON SU.scene_id = S.id
WHERE LOWER(SU.url) = LOWER($1)
AND S.deleted = FALSE
LIMIT $2
`

type FindSceneByURLParams struct {
	Url   *string `db:"url" json:"url"`
	Limit int32   `db:"limit" json:"limit"`
}

func (q *Queries) FindSceneByURL(ctx context.Context, arg FindSceneByURLParams) ([]Scene, error) {
	rows, err := q.db.Query(ctx, findSceneByURL, arg.Url, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scene{}
	for rows.Next() {
		var i Scene
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Details,
			&i.StudioID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.Director,
			&i.Deleted,
			&i.Code,
			&i.Date,
			&i.ProductionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSceneUrlsByIds = `-- name: FindSceneUrlsByIds :many
SELECT scene_id, url, site_id FROM scene_urls WHERE scene_id = ANY($1::UUID[])
`

// Get URLs for multiple scenes
func (q *Queries) FindSceneUrlsByIds(ctx context.Context, sceneIds []uuid.UUID) ([]SceneUrl, error) {
	rows, err := q.db.Query(ctx, findSceneUrlsByIds, sceneIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneUrl{}
	for rows.Next() {
		var i SceneUrl
		if err := rows.Scan(&i.SceneID, &i.Url, &i.SiteID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findScenesByFingerprintsExactWithHash = `-- name: FindScenesByFingerprintsExactWithHash :many
SELECT scenes.id, scenes.title, scenes.details, scenes.studio_id, scenes.created_at, scenes.updated_at, scenes.duration, scenes.director, scenes.deleted, scenes.code, scenes.date, scenes.production_date, matches.hash FROM (
    SELECT SFP.scene_id AS id, FP.hash
    FROM scene_fingerprints SFP
    JOIN fingerprints FP ON SFP.fingerprint_id = FP.id
    WHERE FP.hash = ANY($1::BIGINT[])
        AND $1::BIGINT[] IS NOT NULL AND array_length($1::BIGINT[], 1) > 0
    GROUP BY SFP.scene_id, FP.hash
) matches
JOIN scenes ON scenes.id = matches.id AND scenes.deleted = FALSE
`

type FindScenesByFingerprintsExactWithHashRow struct {
	Scene Scene `db:"scene" json:"scene"`
	Hash  int64 `db:"hash" json:"hash"`
}

func (q *Queries) FindScenesByFingerprintsExactWithHash(ctx context.Context, hashes []int64) ([]FindScenesByFingerprintsExactWithHashRow, error) {
	rows, err := q.db.Query(ctx, findScenesByFingerprintsExactWithHash, hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindScenesByFingerprintsExactWithHashRow{}
	for rows.Next() {
		var i FindScenesByFingerprintsExactWithHashRow
		if err := rows.Scan(
			&i.Scene.ID,
			&i.Scene.Title,
			&i.Scene.Details,
			&i.Scene.StudioID,
			&i.Scene.CreatedAt,
			&i.Scene.UpdatedAt,
			&i.Scene.Duration,
			&i.Scene.Director,
			&i.Scene.Deleted,
			&i.Scene.Code,
			&i.Scene.Date,
			&i.Scene.ProductionDate,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findScenesByFullFingerprintsWithHash = `-- name: FindScenesByFullFingerprintsWithHash :many

SELECT scenes.id, scenes.title, scenes.details, scenes.studio_id, scenes.created_at, scenes.updated_at, scenes.duration, scenes.director, scenes.deleted, scenes.code, scenes.date, scenes.production_date, matches.hash FROM (
    -- Return the query phash from UNNEST so callers can route results back to
    -- the input fingerprint when distance > 0 and the stored hash differs.
    SELECT SFP.scene_id AS id, phash::BIGINT AS hash
    FROM UNNEST($1::BIGINT[]) phash
    JOIN fingerprints FP ON FP.hash <@ (phash, $2::INTEGER)
        AND FP.algorithm = 'PHASH'
    JOIN scene_fingerprints SFP ON SFP.fingerprint_id = FP.id
    WHERE $1::BIGINT[] IS NOT NULL AND array_length($1::BIGINT[], 1) > 0
    GROUP BY SFP.scene_id, phash

    UNION

    SELECT SFP.scene_id AS id, FP.hash
    FROM scene_fingerprints SFP
    JOIN fingerprints FP ON SFP.fingerprint_id = FP.id
    WHERE FP.hash = ANY($3::BIGINT[])
        AND $3::BIGINT[] IS NOT NULL AND array_length($3::BIGINT[], 1) > 0
    GROUP BY SFP.scene_id, FP.hash
) matches
JOIN scenes ON scenes.id = matches.id AND scenes.deleted = FALSE
`

type FindScenesByFullFingerprintsWithHashParams struct {
	Phashes  []int64 `db:"phashes" json:"phashes"`
	Distance int     `db:"distance" json:"distance"`
	Hashes   []int64 `db:"hashes" json:"hashes"`
}

type FindScenesByFullFingerprintsWithHashRow struct {
	Scene Scene `db:"scene" json:"scene"`
	Hash  int64 `db:"hash" json:"hash"`
}

// Scene fingerprints (use fingerprint.sql for most fingerprint operations)
func (q *Queries) FindScenesByFullFingerprintsWithHash(ctx context.Context, arg FindScenesByFullFingerprintsWithHashParams) ([]FindScenesByFullFingerprintsWithHashRow, error) {
	rows, err := q.db.Query(ctx, findScenesByFullFingerprintsWithHash, arg.Phashes, arg.Distance, arg.Hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindScenesByFullFingerprintsWithHashRow{}
	for rows.Next() {
		var i FindScenesByFullFingerprintsWithHashRow
		if err := rows.Scan(
			&i.Scene.ID,
			&i.Scene.Title,
			&i.Scene.Details,
			&i.Scene.StudioID,
			&i.Scene.CreatedAt,
			&i.Scene.UpdatedAt,
			&i.Scene.Duration,
			&i.Scene.Director,
			&i.Scene.Deleted,
			&i.Scene.Code,
			&i.Scene.Date,
			&i.Scene.ProductionDate,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScenePerformers = `-- name: GetScenePerformers :many
SELECT p.id, p.name, p.disambiguation, p.gender, p.ethnicity, p.country, p.eye_color, p.hair_color, p.height, p.cup_size, p.band_size, p.hip_size, p.waist_size, p.breast_type, p.career_start_year, p.career_end_year, p.created_at, p.updated_at, p.deleted, p.birthdate, p.deathdate, p.genitals, p.penis_length, p.weight, "as" FROM scene_performers SP JOIN performers P ON SP.performer_id = P.id WHERE scene_id = $1
`

type GetScenePerformersRow struct {
	Performer Performer `db:"performer" json:"performer"`
	As        *string   `db:"as" json:"as"`
}

func (q *Queries) GetScenePerformers(ctx context.Context, sceneID uuid.UUID) ([]GetScenePerformersRow, error) {
	rows, err := q.db.Query(ctx, getScenePerformers, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScenePerformersRow{}
	for rows.Next() {
		var i GetScenePerformersRow
		if err := rows.Scan(
			&i.Performer.ID,
			&i.Performer.Name,
			&i.Performer.Disambiguation,
			&i.Performer.Gender,
			&i.Performer.Ethnicity,
			&i.Performer.Country,
			&i.Performer.EyeColor,
			&i.Performer.HairColor,
			&i.Performer.Height,
			&i.Performer.CupSize,
			&i.Performer.BandSize,
			&i.Performer.HipSize,
			&i.Performer.WaistSize,
			&i.Performer.BreastType,
			&i.Performer.CareerStartYear,
			&i.Performer.CareerEndYear,
			&i.Performer.CreatedAt,
			&i.Performer.UpdatedAt,
			&i.Performer.Deleted,
			&i.Performer.Birthdate,
			&i.Performer.Deathdate,
			&i.Performer.Genitals,
			&i.Performer.PenisLength,
			&i.Performer.Weight,
			&i.As,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSceneSearchRow = `-- name: GetSceneSearchRow :one
SELECT scene_id,
       scene_details,
       scene_director,
       tag_names,
       performer_names
FROM scene_search
WHERE scene_id = $1
`

type GetSceneSearchRowRow struct {
	SceneID        uuid.UUID `db:"scene_id" json:"scene_id"`
	SceneDetails   *string   `db:"scene_details" json:"scene_details"`
	SceneDirector  *string   `db:"scene_director" json:"scene_director"`
	TagNames       []string  `db:"tag_names" json:"tag_names"`
	PerformerNames []string  `db:"performer_names" json:"performer_names"`
}

// Reads one scene's search row, for the tests that assert what the triggers
// wrote and for the §7.25.2 diagnosis path.
//
// The generated `queries.SceneSearch` struct is NOT this row: it predates
// migration 103 and carries nine columns, because no query selects the table
// bare, so sqlc keeps emitting a shape from an earlier schema. Selecting the
// three recall columns explicitly is what makes a test fail when a trigger stops
// writing them — a struct that silently lacked the fields would compile and
// assert nothing.
//
// :one and not :many, so "the trigger did not fire" surfaces as ErrNoRows at the
// call site instead of an empty slice somebody has to remember to check.
func (q *Queries) GetSceneSearchRow(ctx context.Context, sceneID uuid.UUID) (GetSceneSearchRowRow, error) {
	row := q.db.QueryRow(ctx, getSceneSearchRow, sceneID)
	var i GetSceneSearchRowRow
	err := row.Scan(
		&i.SceneID,
		&i.SceneDetails,
		&i.SceneDirector,
		&i.TagNames,
		&i.PerformerNames,
	)
	return i, err
}

const getSceneURLs = `-- name: GetSceneURLs :many
SELECT url, site_id FROM scene_urls WHERE scene_id = $1
`

type GetSceneURLsRow struct {
	Url    string    `db:"url" json:"url"`
	SiteID uuid.UUID `db:"site_id" json:"site_id"`
}

func (q *Queries) GetSceneURLs(ctx context.Context, sceneID uuid.UUID) ([]GetSceneURLsRow, error) {
	rows, err := q.db.Query(ctx, getSceneURLs, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSceneURLsRow{}
	for rows.Next() {
		var i GetSceneURLsRow
		if err := rows.Scan(&i.Url, &i.SiteID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScenes = `-- name: GetScenes :many
SELECT id, title, details, studio_id, created_at, updated_at, duration, director, deleted, code, date, production_date FROM scenes WHERE id = ANY($1::UUID[]) ORDER BY title
`

func (q *Queries) GetScenes(ctx context.Context, dollar_1 []uuid.UUID) ([]Scene, error) {
	rows, err := q.db.Query(ctx, getScenes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scene{}
	for rows.Next() {
		var i Scene
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Details,
			&i.StudioID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.Director,
			&i.Deleted,
			&i.Code,
			&i.Date,
			&i.ProductionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sceneChangelog = `-- name: SceneChangelog :many
SELECT S.id, S.updated_at, S.deleted, R.target_id AS redirect_to
FROM scenes S
LEFT JOIN scene_redirects R ON R.source_id = S.id
WHERE (S.updated_at, S.id) > ($1::timestamp, $2::uuid)
ORDER BY S.updated_at, S.id
LIMIT $3
`

type SceneChangelogParams struct {
	Since   time.Time `db:"since" json:"since"`
	AfterID uuid.UUID `db:"after_id" json:"after_id"`
	Limit   int32     `db:"limit" json:"limit"`
}

type SceneChangelogRow struct {
	ID         uuid.UUID     `db:"id" json:"id"`
	UpdatedAt  time.Time     `db:"updated_at" json:"updated_at"`
	Deleted    bool          `db:"deleted" json:"deleted"`
	RedirectTo uuid.NullUUID `db:"redirect_to" json:"redirect_to"`
}

// Keyset-paginated feed of scenes changed since (since, after_id), including
// tombstones. redirect_to is the surviving scene for merged-away scenes.
func (q *Queries) SceneChangelog(ctx context.Context, arg SceneChangelogParams) ([]SceneChangelogRow, error) {
	rows, err := q.db.Query(ctx, sceneChangelog, arg.Since, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneChangelogRow{}
	for rows.Next() {
		var i SceneChangelogRow
		if err := rows.Scan(
			&i.ID,
			&i.UpdatedAt,
			&i.Deleted,
			&i.RedirectTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchScenes = `-- name: SearchScenes :many
SELECT
    scene_id,
    pdb.agg('{"value_count": {"field": "scene_id"}}') OVER () as total_count
FROM scene_search
WHERE scene_id @@@ paradedb.boolean(should =>
    ARRAY(
        SELECT paradedb.const_score(10000.0, paradedb.disjunction_max(disjuncts => ARRAY[
            paradedb.match(field => 'scene_title', value => tok),
            paradedb.match(field => 'scene_code', value => tok),
            paradedb.match(field => 'scene_date', value => tok),
            paradedb.match(field => 'performer_names', value => tok),
            paradedb.match(field => 'studio_name', value => tok),
            paradedb.match(field => 'studio_aliases', value => tok),
            paradedb.match(field => 'network_name', value => tok),
            paradedb.match(field => 'network_aliases', value => tok),
            paradedb.match(field => 'scene_details', value => tok),
            paradedb.match(field => 'scene_director', value => tok),
            paradedb.match(field => 'tag_names', value => tok)
        ]))
        FROM unnest($1::TEXT[]) AS tok
    ) || ARRAY(
        SELECT paradedb.disjunction_max(disjuncts => ARRAY[
            paradedb.boost(factor => 2.0, query => paradedb.match(field => 'performer_names', value => tok)),
            -- SPEC §7.25.1 R1: tags above studio. For a vague query -- the whole
            -- point of this feature -- what happened in the scene discriminates
            -- better than who released it. tag_names is boosted for the same
            -- reason performer_names already is: it is a keyword list, and a
            -- scene with one tag should not outrank one with six on field length.
            paradedb.boost(factor => 1.5, query => paradedb.match(field => 'tag_names', value => tok)),
            paradedb.match(field => 'scene_title', value => tok),
            paradedb.match(field => 'scene_code', value => tok),
            paradedb.match(field => 'scene_date', value => tok),
            paradedb.match(field => 'scene_details', value => tok),
            paradedb.match(field => 'scene_director', value => tok),
            paradedb.match(field => 'studio_name', value => tok),
            paradedb.match(field => 'studio_aliases', value => tok),
            paradedb.match(field => 'network_name', value => tok),
            paradedb.match(field => 'network_aliases', value => tok)
        ])
        FROM unnest($1::TEXT[]) AS tok
    )
)
ORDER BY pdb.score(scene_id) DESC, scene_id
LIMIT $3 OFFSET $2
`

type SearchScenesParams struct {
	Tokens []string `db:"tokens" json:"tokens"`
	Offset int32    `db:"offset" json:"offset"`
	Limit  int32    `db:"limit" json:"limit"`
}

type SearchScenesRow struct {
	SceneID    uuid.UUID   `db:"scene_id" json:"scene_id"`
	TotalCount interface{} `db:"total_count" json:"total_count"`
}

// Token-at-a-time scoring. The search term is tokenized by the caller and
// passed as an array. Each token is scored independently against every field
// via disjunction_max, so a token that hits several fields (e.g. a studio named
// after its performer) only contributes from its single best field instead of
// summing across them.
//
// Score = coverage tier + relevance tiebreak:
//   - coverage: each distinct token that matches anywhere adds a flat 10000, so
//     a scene matching more of the query always outranks one matching fewer,
//     regardless of BM25/IDF weighting (stops a single rare token outscoring
//     several common ones).
//   - relevance: ordinary BM25 breaks ties within a tier, with the two fields
//     that describe WHAT HAPPENED boosted above the fields that describe WHO
//     RELEASED IT.
//
// SPEC §7.25.1. scene_details, scene_director and tag_names were added to
// scene_search by migration 103 and are matched here. The coverage array and the
// relevance array must list the SAME fields: the coverage tier is what decides
// "matches more of the query", so a field present in only one array contributes
// to one tier and not the other, and the score stops meaning what its own comment
// says it means.
//
// The 10000 constant must exceed the max achievable BM25 sum; search terms are
// short so the relevance total stays well under it. Do not raise a field's
// relevance weight to change which scenes match -- relevance only orders WITHIN
// a coverage tier, so boosting a field can never bring in a scene the coverage
// array excluded.
func (q *Queries) SearchScenes(ctx context.Context, arg SearchScenesParams) ([]SearchScenesRow, error) {
	rows, err := q.db.Query(ctx, searchScenes, arg.Tokens, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchScenesRow{}
	for rows.Next() {
		var i SearchScenesRow
		if err := rows.Scan(&i.SceneID, &i.TotalCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteScene = `-- name: SoftDeleteScene :one
UPDATE scenes SET deleted = true, updated_at = NOW() WHERE id = $1
RETURNING id, title, details, studio_id, created_at, updated_at, duration, director, deleted, code, date, production_date
`

func (q *Queries) SoftDeleteScene(ctx context.Context, id uuid.UUID) (Scene, error) {
	row := q.db.QueryRow(ctx, softDeleteScene, id)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Details,
		&i.StudioID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Director,
		&i.Deleted,
		&i.Code,
		&i.Date,
		&i.ProductionDate,
	)
	return i, err
}

const updateScene = `-- name: UpdateScene :one
UPDATE scenes 
SET title = $2, details = $3, date = $4, production_date = $5, studio_id = $6, 
    duration = $7, director = $8, code = $9, updated_at = now()
WHERE id = $1
RETURNING id, title, details, studio_id, created_at, updated_at, duration, director, deleted, code, date, production_date
`

type UpdateSceneParams struct {
	ID             uuid.UUID     `db:"id" json:"id"`
	Title          *string       `db:"title" json:"title"`
	Details        *string       `db:"details" json:"details"`
	Date           *string       `db:"date" json:"date"`
	ProductionDate *string       `db:"production_date" json:"production_date"`
	StudioID       uuid.NullUUID `db:"studio_id" json:"studio_id"`
	Duration       *int          `db:"duration" json:"duration"`
	Director       *string       `db:"director" json:"director"`
	Code           *string       `db:"code" json:"code"`
}

func (q *Queries) UpdateScene(ctx context.Context, arg UpdateSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, updateScene,
		arg.ID,
		arg.Title,
		arg.Details,
		arg.Date,
		arg.ProductionDate,
		arg.StudioID,
		arg.Duration,
		arg.Director,
		arg.Code,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Details,
		&i.StudioID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Director,
		&i.Deleted,
		&i.Code,
		&i.Date,
		&i.ProductionDate,
	)
	return i, err
}

const updateSceneRedirects = `-- name: UpdateSceneRedirects :exec
UPDATE scene_redirects SET target_id = $1 WHERE target_id = $2
`

type UpdateSceneRedirectsParams struct {
	NewTargetID uuid.UUID `db:"new_target_id" json:"new_target_id"`
	OldTargetID uuid.UUID `db:"old_target_id" json:"old_target_id"`
}

func (q *Queries) UpdateSceneRedirects(ctx context.Context, arg UpdateSceneRedirectsParams) error {
	_, err := q.db.Exec(ctx, updateSceneRedirects, arg.NewTargetID, arg.OldTargetID)
	return err
}

const updateSceneStudios = `-- name: UpdateSceneStudios :exec
UPDATE scenes SET studio_id = $1 WHERE studio_id = $2
`

type UpdateSceneStudiosParams struct {
	TargetID uuid.NullUUID `db:"target_id" json:"target_id"`
	SourceID uuid.NullUUID `db:"source_id" json:"source_id"`
}

func (q *Queries) UpdateSceneStudios(ctx context.Context, arg UpdateSceneStudiosParams) error {
	_, err := q.db.Exec(ctx, updateSceneStudios, arg.TargetID, arg.SourceID)
	return err
}
