// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: trust.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

const applyTrustEvent = `-- name: ApplyTrustEvent :one
INSERT INTO user_trust (user_id, approved_edits, rejected_edits, identification_solves, quests_completed, replicas_hosted, updated_at)
VALUES (
    $1,
    CASE WHEN $2::TEXT = 'edit_approved' THEN 1 ELSE 0 END,
    CASE WHEN $2::TEXT = 'edit_rejected' THEN 1 ELSE 0 END,
    CASE WHEN $2::TEXT = 'identification_solved' THEN 1 ELSE 0 END,
    CASE WHEN $2::TEXT = 'quest_completed' THEN 1 ELSE 0 END,
    CASE WHEN $2::TEXT = 'replica_hosted' THEN 1 ELSE 0 END,
    NOW()
)
ON CONFLICT (user_id) DO UPDATE SET
    approved_edits = user_trust.approved_edits + EXCLUDED.approved_edits,
    rejected_edits = user_trust.rejected_edits + EXCLUDED.rejected_edits,
    identification_solves = user_trust.identification_solves + EXCLUDED.identification_solves,
    quests_completed = user_trust.quests_completed + EXCLUDED.quests_completed,
    replicas_hosted = user_trust.replicas_hosted + EXCLUDED.replicas_hosted,
    updated_at = NOW()
RETURNING user_id, level, approved_edits, rejected_edits, identification_solves, quests_completed, replicas_hosted, content_viewing_opt_in, updated_at
`

type ApplyTrustEventParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	EventKind string    `db:"event_kind" json:"event_kind"`
}

// Applies one event's effect to the rollup, creating the row if absent.
//
// The totals are incremented rather than recomputed by replaying events, so
// recording a trust event is O(1) regardless of how much history a user has.
// The signed delta works for both directions: a rejected edit decrements the
// same column an approval incremented.
//
// ON CONFLICT (user_id) DO UPDATE is required because a user with no rollup row
// yet (every new user) has to be created on first event.
func (q *Queries) ApplyTrustEvent(ctx context.Context, arg ApplyTrustEventParams) (UserTrust, error) {
	row := q.db.QueryRow(ctx, applyTrustEvent, arg.UserID, arg.EventKind)
	var i UserTrust
	err := row.Scan(
		&i.UserID,
		&i.Level,
		&i.ApprovedEdits,
		&i.RejectedEdits,
		&i.IdentificationSolves,
		&i.QuestsCompleted,
		&i.ReplicasHosted,
		&i.ContentViewingOptIn,
		&i.UpdatedAt,
	)
	return i, err
}

const countUserTrustEvents = `-- name: CountUserTrustEvents :one
SELECT count(*) FROM trust_events WHERE user_id = $1
`

func (q *Queries) CountUserTrustEvents(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTrustEvents, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllUserTrust = `-- name: GetAllUserTrust :many
SELECT user_id, level, approved_edits, rejected_edits, identification_solves, quests_completed, replicas_hosted, content_viewing_opt_in, updated_at FROM user_trust
`

// Every rollup row. Used when a threshold changes and every level must be
// recomputed (see RebuildLevels in internal/service/trust).
func (q *Queries) GetAllUserTrust(ctx context.Context) ([]UserTrust, error) {
	rows, err := q.db.Query(ctx, getAllUserTrust)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTrust{}
	for rows.Next() {
		var i UserTrust
		if err := rows.Scan(
			&i.UserID,
			&i.Level,
			&i.ApprovedEdits,
			&i.RejectedEdits,
			&i.IdentificationSolves,
			&i.QuestsCompleted,
			&i.ReplicasHosted,
			&i.ContentViewingOptIn,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTrust = `-- name: GetUserTrust :one

SELECT user_id, level, approved_edits, rejected_edits, identification_solves, quests_completed, replicas_hosted, content_viewing_opt_in, updated_at FROM user_trust WHERE user_id = $1
`

// Trust level queries (SPEC §6, migration 76).
//
// trust_events is the source of truth; user_trust is a denormalised rollup of
// it. These queries keep the rollup in step with the events, and the two
// upserts below are the only places in the codebase allowed to write either
// table.
func (q *Queries) GetUserTrust(ctx context.Context, userID uuid.UUID) (UserTrust, error) {
	row := q.db.QueryRow(ctx, getUserTrust, userID)
	var i UserTrust
	err := row.Scan(
		&i.UserID,
		&i.Level,
		&i.ApprovedEdits,
		&i.RejectedEdits,
		&i.IdentificationSolves,
		&i.QuestsCompleted,
		&i.ReplicasHosted,
		&i.ContentViewingOptIn,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTrustByUserIDs = `-- name: GetUserTrustByUserIDs :many
SELECT user_id, level, approved_edits, rejected_edits, identification_solves, quests_completed, replicas_hosted, content_viewing_opt_in, updated_at FROM user_trust WHERE user_id = ANY($1::UUID[])
`

func (q *Queries) GetUserTrustByUserIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]UserTrust, error) {
	rows, err := q.db.Query(ctx, getUserTrustByUserIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTrust{}
	for rows.Next() {
		var i UserTrust
		if err := rows.Scan(
			&i.UserID,
			&i.Level,
			&i.ApprovedEdits,
			&i.RejectedEdits,
			&i.IdentificationSolves,
			&i.QuestsCompleted,
			&i.ReplicasHosted,
			&i.ContentViewingOptIn,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTrustEvents = `-- name: ListUserTrustEvents :many
SELECT id, user_id, kind, entity_type, entity_id, delta, created_at FROM trust_events
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

// One user's history, newest first. Used by the audit view and by tests that
// assert the event log is the source of truth.
func (q *Queries) ListUserTrustEvents(ctx context.Context, userID uuid.UUID) ([]TrustEvent, error) {
	rows, err := q.db.Query(ctx, listUserTrustEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustEvent{}
	for rows.Next() {
		var i TrustEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.EntityType,
			&i.EntityID,
			&i.Delta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeUserTrustTotals = `-- name: RecomputeUserTrustTotals :one
INSERT INTO user_trust (user_id, approved_edits, rejected_edits, identification_solves, quests_completed, replicas_hosted, updated_at)
SELECT
    $1,
    COALESCE(SUM(CASE WHEN kind = 'edit_approved' THEN delta ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN kind = 'edit_rejected' THEN -delta ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN kind = 'identification_solved' THEN delta ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN kind = 'quest_completed' THEN delta ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN kind = 'replica_hosted' THEN delta ELSE 0 END), 0),
    NOW()
FROM trust_events
WHERE user_id = $1
ON CONFLICT (user_id) DO UPDATE SET
    approved_edits = EXCLUDED.approved_edits,
    rejected_edits = EXCLUDED.rejected_edits,
    identification_solves = EXCLUDED.identification_solves,
    quests_completed = EXCLUDED.quests_completed,
    replicas_hosted = EXCLUDED.replicas_hosted,
    updated_at = NOW()
RETURNING user_id, level, approved_edits, rejected_edits, identification_solves, quests_completed, replicas_hosted, content_viewing_opt_in, updated_at
`

// Rebuilds the totals from the event log.
//
// This is the recovery path, and the reason trust_events is append-only: if the
// rollup ever drifts -- a threshold change, a bug in ApplyTrustEvent, a manual
// database edit -- the truth is still replayable. Coalescing SUMs the signed
// deltas per kind in one pass rather than replaying row by row.
// No GROUP BY: an aggregate over an empty set still returns exactly one row,
// with the COALESCE defaults above. GROUP BY made this return NOTHING for a
// user with no events, which made it unusable for creating a zeroed rollup --
// and that is exactly what SetContentViewingOptIn needs to do for a user
// opting in before they are eligible.
func (q *Queries) RecomputeUserTrustTotals(ctx context.Context, userID uuid.UUID) (UserTrust, error) {
	row := q.db.QueryRow(ctx, recomputeUserTrustTotals, userID)
	var i UserTrust
	err := row.Scan(
		&i.UserID,
		&i.Level,
		&i.ApprovedEdits,
		&i.RejectedEdits,
		&i.IdentificationSolves,
		&i.QuestsCompleted,
		&i.ReplicasHosted,
		&i.ContentViewingOptIn,
		&i.UpdatedAt,
	)
	return i, err
}

const recordTrustEvent = `-- name: RecordTrustEvent :one
INSERT INTO trust_events (user_id, kind, entity_type, entity_id, delta)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
RETURNING id, user_id, kind, entity_type, entity_id, delta, created_at
`

type RecordTrustEventParams struct {
	UserID     uuid.UUID     `db:"user_id" json:"user_id"`
	Kind       string        `db:"kind" json:"kind"`
	EntityType *string       `db:"entity_type" json:"entity_type"`
	EntityID   uuid.NullUUID `db:"entity_id" json:"entity_id"`
	Delta      int           `db:"delta" json:"delta"`
}

// ON CONFLICT DO NOTHING makes a retried or duplicated event a no-op rather
// than a silent double increment. The matching partial state is a real
// concern: an edit can be applied twice by a retried request, and without this
// the contributor's trust would grow twice for one contribution.
//
// Returning the row means a duplicate insert reports no rows, which the
// service treats as "already recorded" rather than as an error.
func (q *Queries) RecordTrustEvent(ctx context.Context, arg RecordTrustEventParams) (TrustEvent, error) {
	row := q.db.QueryRow(ctx, recordTrustEvent,
		arg.UserID,
		arg.Kind,
		arg.EntityType,
		arg.EntityID,
		arg.Delta,
	)
	var i TrustEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.EntityType,
		&i.EntityID,
		&i.Delta,
		&i.CreatedAt,
	)
	return i, err
}

const setContentViewingOptIn = `-- name: SetContentViewingOptIn :one
UPDATE user_trust
SET content_viewing_opt_in = $2, updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, level, approved_edits, rejected_edits, identification_solves, quests_completed, replicas_hosted, content_viewing_opt_in, updated_at
`

type SetContentViewingOptInParams struct {
	UserID              uuid.UUID `db:"user_id" json:"user_id"`
	ContentViewingOptIn bool      `db:"content_viewing_opt_in" json:"content_viewing_opt_in"`
}

// The one user-writable field in this table (SPEC §6: high-trust users
// EXPLICITLY opt in to viewing content).
//
// It is deliberately NOT gated on level here. Eligibility (level >= 4) is
// derived at read time by the service, because a stored eligibility would go
// stale the moment a threshold changed; a stored opt-in is just the user's
// own choice and is safe to keep.
func (q *Queries) SetContentViewingOptIn(ctx context.Context, arg SetContentViewingOptInParams) (UserTrust, error) {
	row := q.db.QueryRow(ctx, setContentViewingOptIn, arg.UserID, arg.ContentViewingOptIn)
	var i UserTrust
	err := row.Scan(
		&i.UserID,
		&i.Level,
		&i.ApprovedEdits,
		&i.RejectedEdits,
		&i.IdentificationSolves,
		&i.QuestsCompleted,
		&i.ReplicasHosted,
		&i.ContentViewingOptIn,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserTrustLevel = `-- name: SetUserTrustLevel :one
UPDATE user_trust
SET level = $2, updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, level, approved_edits, rejected_edits, identification_solves, quests_completed, replicas_hosted, content_viewing_opt_in, updated_at
`

type SetUserTrustLevelParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Level  int       `db:"level" json:"level"`
}

// The level is written by the service after deriving it from the thresholds,
// never by the database. The curve is a product decision and belongs in Go,
// where it can be changed without a migration.
func (q *Queries) SetUserTrustLevel(ctx context.Context, arg SetUserTrustLevelParams) (UserTrust, error) {
	row := q.db.QueryRow(ctx, setUserTrustLevel, arg.UserID, arg.Level)
	var i UserTrust
	err := row.Scan(
		&i.UserID,
		&i.Level,
		&i.ApprovedEdits,
		&i.RejectedEdits,
		&i.IdentificationSolves,
		&i.QuestsCompleted,
		&i.ReplicasHosted,
		&i.ContentViewingOptIn,
		&i.UpdatedAt,
	)
	return i, err
}
