// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: webhook.sql

package queries

import (
	"context"
	"encoding/json"
	"time"

	"github.com/gofrs/uuid"
)

const abandonWebhookDelivery = `-- name: AbandonWebhookDelivery :exec
UPDATE webhook_deliveries
SET last_error = $2
WHERE id = $1 AND delivered_at IS NULL
`

type AbandonWebhookDeliveryParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	LastError *string   `db:"last_error" json:"last_error"`
}

// Gives up permanently. The row is KEPT, not deleted, because "this endpoint
// failed four times and was abandoned" is the answer to the question a user asks
// when their integration silently stopped working.
func (q *Queries) AbandonWebhookDelivery(ctx context.Context, arg AbandonWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, abandonWebhookDelivery, arg.ID, arg.LastError)
	return err
}

const countWebhookDeliveries = `-- name: CountWebhookDeliveries :one
SELECT count(*)::int FROM webhook_deliveries
WHERE endpoint_id = $1 AND delivered_at IS NULL
`

// How many are still pending for an endpoint. Shown on the settings page so a user
// can see their queue is backing up BEFORE deliveries start failing.
func (q *Queries) CountWebhookDeliveries(ctx context.Context, endpointID uuid.UUID) (int, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveries, endpointID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (id, endpoint_id, event_type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, endpoint_id, event_type, payload, attempt, next_attempt_at, last_error, delivered_at, created_at
`

type CreateWebhookDeliveryParams struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	EndpointID uuid.UUID       `db:"endpoint_id" json:"endpoint_id"`
	EventType  string          `db:"event_type" json:"event_type"`
	Payload    json.RawMessage `db:"payload" json:"payload"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.ID,
		arg.EndpointID,
		arg.EventType,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EventType,
		&i.Payload,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one

INSERT INTO webhook_endpoints (id, user_id, secret_hash, target_url, event_types)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, secret_hash, target_url, event_types, disabled, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	SecretHash string    `db:"secret_hash" json:"secret_hash"`
	TargetUrl  string    `db:"target_url" json:"target_url"`
	EventTypes []string  `db:"event_types" json:"event_types"`
}

// Webhook queries (SPEC §7.11, phase 3 step 3).
func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.ID,
		arg.UserID,
		arg.SecretHash,
		arg.TargetUrl,
		arg.EventTypes,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretHash,
		&i.TargetUrl,
		&i.EventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :one
DELETE FROM webhook_endpoints WHERE id = $1 AND user_id = $2 RETURNING id, user_id, secret_hash, target_url, event_types, disabled, created_at, updated_at
`

type DeleteWebhookEndpointParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

// Returns the row so the caller can report WHICH endpoint was removed.
func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, deleteWebhookEndpoint, arg.ID, arg.UserID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretHash,
		&i.TargetUrl,
		&i.EventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWebhookEndpoint = `-- name: FindWebhookEndpoint :one
SELECT id, user_id, secret_hash, target_url, event_types, disabled, created_at, updated_at FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) FindWebhookEndpoint(ctx context.Context, id uuid.UUID) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, findWebhookEndpoint, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretHash,
		&i.TargetUrl,
		&i.EventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWebhookEndpointByUser = `-- name: FindWebhookEndpointByUser :one
SELECT id, user_id, secret_hash, target_url, event_types, disabled, created_at, updated_at FROM webhook_endpoints WHERE id = $1 AND user_id = $2
`

type FindWebhookEndpointByUserParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

// Scoped by user on purpose. An endpoint id is a UUID and a GraphQL client cannot
// be assumed to pass the caller's own, so a lookup that does not check ownership
// is a way to read another user's webhook configuration -- including the target
// URL, which is often an internal address.
func (q *Queries) FindWebhookEndpointByUser(ctx context.Context, arg FindWebhookEndpointByUserParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, findWebhookEndpointByUser, arg.ID, arg.UserID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretHash,
		&i.TargetUrl,
		&i.EventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueWebhookDeliveries = `-- name: ListDueWebhookDeliveries :many
SELECT id, endpoint_id, event_type, payload, attempt, next_attempt_at, last_error, delivered_at, created_at FROM webhook_deliveries
WHERE delivered_at IS NULL AND next_attempt_at <= $1
ORDER BY next_attempt_at ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListDueWebhookDeliveriesParams struct {
	NextAttemptAt time.Time `db:"next_attempt_at" json:"next_attempt_at"`
	Limit         int32     `db:"limit" json:"limit"`
}

// The queue read: pending, due, oldest first.
//
// `FOR UPDATE SKIP LOCKED` and NOT a plain SELECT. Two dispatchers running at once
// -- a second instance, or an overlapping tick -- must not both claim the same
// row, or the same event is delivered twice. SKIP LOCKED makes the second one step
// over the locked row and take the next, which turns "two dispatchers" into "one
// dispatcher and one slightly behind", with no coordination and no failure.
//
// A plain SELECT here is the single most common way a queue double-delivers, and
// the symptom -- a consumer seeing every event twice -- is usually blamed on the
// consumer.
func (q *Queries) ListDueWebhookDeliveries(ctx context.Context, arg ListDueWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDueWebhookDeliveries, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.EventType,
			&i.Payload,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesForEndpoint = `-- name: ListWebhookDeliveriesForEndpoint :many
SELECT id, endpoint_id, event_type, payload, attempt, next_attempt_at, last_error, delivered_at, created_at FROM webhook_deliveries
WHERE endpoint_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesForEndpointParams struct {
	EndpointID uuid.UUID `db:"endpoint_id" json:"endpoint_id"`
	Limit      int32     `db:"limit" json:"limit"`
	Offset     int32     `db:"offset" json:"offset"`
}

// A user's delivery history for one endpoint, newest first.
func (q *Queries) ListWebhookDeliveriesForEndpoint(ctx context.Context, arg ListWebhookDeliveriesForEndpointParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesForEndpoint, arg.EndpointID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.EventType,
			&i.Payload,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, user_id, secret_hash, target_url, event_types, disabled, created_at, updated_at FROM webhook_endpoints
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookEndpointsParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListWebhookEndpoints(ctx context.Context, arg ListWebhookEndpointsParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SecretHash,
			&i.TargetUrl,
			&i.EventTypes,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpointsForEvent = `-- name: ListWebhookEndpointsForEvent :many
SELECT id, user_id, secret_hash, target_url, event_types, disabled, created_at, updated_at FROM webhook_endpoints
WHERE NOT disabled AND event_types && ARRAY[$1]::TEXT[]
`

// The dispatch set: live endpoints subscribed to this event type.
//
// The overlap operator again, and the reason is the same as the directory's array
// filters: an endpoint subscribed to ["scene.added", "scene.updated"] wants
// scene.added, and containment (@>) would require an exact list match.
func (q *Queries) ListWebhookEndpointsForEvent(ctx context.Context, dollar_1 []string) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpointsForEvent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SecretHash,
			&i.TargetUrl,
			&i.EventTypes,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :one
UPDATE webhook_deliveries
SET delivered_at = now(), last_error = NULL
WHERE id = $1
RETURNING id, endpoint_id, event_type, payload, attempt, next_attempt_at, last_error, delivered_at, created_at
`

func (q *Queries) MarkWebhookDelivered(ctx context.Context, id uuid.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookDelivered, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EventType,
		&i.Payload,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const markWebhookFailed = `-- name: MarkWebhookFailed :one
UPDATE webhook_deliveries
SET attempt = $2, next_attempt_at = $3, last_error = $4
WHERE id = $1
RETURNING id, endpoint_id, event_type, payload, attempt, next_attempt_at, last_error, delivered_at, created_at
`

type MarkWebhookFailedParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	Attempt       int       `db:"attempt" json:"attempt"`
	NextAttemptAt time.Time `db:"next_attempt_at" json:"next_attempt_at"`
	LastError     *string   `db:"last_error" json:"last_error"`
}

// Records a failed attempt and schedules the next one.
//
// next_attempt_at is computed by the service and passed in, not by the database.
// The backoff schedule is a POLICY -- changing it should not be a migration --
// and the service is where the policy lives. The database's job is only to store
// when.
func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookFailed,
		arg.ID,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.LastError,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EventType,
		&i.Payload,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const rotateWebhookSecret = `-- name: RotateWebhookSecret :one
UPDATE webhook_endpoints SET secret_hash = $2, updated_at = now() WHERE id = $1
RETURNING id, user_id, secret_hash, target_url, event_types, disabled, created_at, updated_at
`

type RotateWebhookSecretParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	SecretHash string    `db:"secret_hash" json:"secret_hash"`
}

// Replaces the hash. The OLD secret stops working immediately, which is the point:
// a rotation is what a user does after suspecting a leak, and a rotation that
// left the old secret valid would give no protection at all.
func (q *Queries) RotateWebhookSecret(ctx context.Context, arg RotateWebhookSecretParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, rotateWebhookSecret, arg.ID, arg.SecretHash)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretHash,
		&i.TargetUrl,
		&i.EventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setWebhookEndpointDisabled = `-- name: SetWebhookEndpointDisabled :one
UPDATE webhook_endpoints SET disabled = $2, updated_at = now() WHERE id = $1
RETURNING id, user_id, secret_hash, target_url, event_types, disabled, created_at, updated_at
`

type SetWebhookEndpointDisabledParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Disabled bool      `db:"disabled" json:"disabled"`
}

func (q *Queries) SetWebhookEndpointDisabled(ctx context.Context, arg SetWebhookEndpointDisabledParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, setWebhookEndpointDisabled, arg.ID, arg.Disabled)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretHash,
		&i.TargetUrl,
		&i.EventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
